### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by vapayt** [PepperCode1/Continuity#101]
even with texture pack, with any mod

https://user-images.githubusercontent.com/105302632/170820218-d0af7ad0-469c-473c-a034-db0e94a6a4c8.mp4

s

**Comment by BunnySilly** [comment]
Same issue

**Comment by Julienraptor01** [comment]
Could you give latest.log please

**Comment by BunnySilly** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/8791124/latest.log)

**Comment by Julienraptor01** [comment]
Thanks, with that it'll be easier to find your problem.

**Comment by Julienraptor01** [comment]
you need [indium](https://modrinth.com/mod/indium) when using sodium

**Comment by BunnySilly** [comment]
Thanks for letting me know

**Comment by BunnySilly** [comment]
Working fully with indium thanks for the help

**Comment by vapayt** [comment]
> you need [indium](https://modrinth.com/mod/indium) when using sodium

it's crashes

**Comment by AlsoSylv** [comment]
We need a log file before we can actually help

**Comment by vapayt** [comment]
> We need a log file before we can actually help

ok wait

**Comment by vapayt** [comment]
> We need a log file before we can actually help

forgot to mention, it crashes when i've entered the world

**Comment by vapayt** [comment]
> We need a log file before we can actually help

but now i've entered the world, but it still don't work
UPD:sorry, forgot texture pack
