### ISSUE TITLE
Continuity not working for me 

### ISSUE THREAD

**Issue by Chubachubs1337** [PepperCode1/Continuity#102]
I decided to change from optifine to sodium and other performance improving mods, I downloaded continuity and Indium (both latest versions) and the mod wont work(yes i enabled the texture packs, are there any mods Continuity doesn't like ? 
Here are the mods I use:
![image](https://user-images.githubusercontent.com/65852559/172028405-765a2c0c-1181-482b-8cc5-8c5b134800a2.png)

**Comment by PepperCode1** [comment]
Update Ok Zoomer to beta 6 or higher.
