### ISSUE TITLE
port to 1.19

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#106]

**Comment by HarvelsX** [comment]
Try use https://github.com/IMS212/Continuity/tree/1.19/dev

**Comment by WiseNoobCrusher** [comment]
> Try use https://github.com/IMS212/Continuity/tree/1.19/dev

This doesnt work, I tried, the textures don't connect sadly. Will have to wait for it to be updated by the devs.

**Comment by HarvelsX** [comment]
You can try build fork 1.19 + 2.0.0: https://github.com/HarvelsX/Continuity/actions/runs/2458486178

**Comment by WiseNoobCrusher** [comment]
> You can try build fork 1.19 + 2.0.0: https://github.com/HarvelsX/Continuity/actions/runs/2458486178

This also, does not work. Actually it stops my resource pack from loading.

**Comment by HarvelsX** [comment]
@WiseNoobCrusher, which resource pack are you trying to include?

**Comment by WiseNoobCrusher** [comment]
> @WiseNoobCrusher, which resource pack are you trying to include?

FaithfulVenom, its the 1.18 version, but it should have still worked.

**Comment by HarvelsX** [comment]
@WiseNoobCrusher, it seems to work for me, for further discussion, please open a ticket in https://github.com/HarvelsX/Continuity/issues

![image](https://user-images.githubusercontent.com/90945793/172518222-7cb225ab-5bb1-4bff-a5b7-c3d666c8e08b.png)

**Comment by PepperCode1** [comment]
Resolved with commit d9c05615509db804bb818e30a77a207dd5f2b86a.

**Comment by ghost** [comment]
indium has to be up to date too that is probably the problem.
