### ISSUE TITLE
Doesn't work with Sodium

### ISSUE THREAD

**Issue by JacobWasTaken** [PepperCode1/Continuity#107]
Using Continuity without Sodium works just fine but when I add Sodium the connected textures stop working.

**Comment by Mattabase** [comment]
You must use indium alongside sodium


https://github.com/IMS212/Indium/actions/runs/2458463120 you can find a temporary solution until an official update is released. 

I have confirmed the fork worked for me

**Comment by JacobWasTaken** [comment]
I was looking at indium but it's only for 1.18.2 currently and I'm on 1.19. Does that version still work in 1.19?

**Comment by PepperCode1** [comment]
No, use the linked build.

**Comment by JacobWasTaken** [comment]
How do I download it using the linked build?

**Comment by Mattabase** [comment]
@JacobWasTaken 

![image](https://user-images.githubusercontent.com/2126947/172715415-a67b5e27-b70a-4268-be17-97a3ba04a89b.png)
 
and then

![image](https://user-images.githubusercontent.com/2126947/172715547-b2b3f062-6246-4f64-a3df-ec84a489abe5.png)

**Comment by JacobWasTaken** [comment]
Ok, thank you!
