### ISSUE TITLE
NPE Crash in 1.19

### ISSUE THREAD

**Issue by Shnupbups** [PepperCode1/Continuity#110]
Version: 2.0.0+1.19
Minecraft Version: 1.19
Using the Fabulously Optimized modpack version 4.0.0-alpha.1
Crash log: https://paste.ee/p/Z5vqv
Relevant section:
```
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
```
Not entirely sure how to reproduce as I was just walking around in a newly created world, but the crash indicates it involves falling gravel blocks. Likely just a simple null check needed.

**Comment by PepperCode1** [comment]
Install Indium. The CurseForge and Modrinth pages explicitly say this in bold letters.

**Comment by Shnupbups** [comment]
If Indium is required to not crash, then shouldn't it be specified in the fabric.mod.json?

**Comment by PepperCode1** [comment]
No, because it is only required if Sodium is installed.

**Comment by Shnupbups** [comment]
I have been informed that Indium doesn't work in 1.19 yet. So...

**Comment by PepperCode1** [comment]
There is an unofficial port that you can use or you can wait or uninstall Sodium.
