### ISSUE TITLE
Top face of blocks with emissive textures renders incorrectly as inventory icon

### ISSUE THREAD

**Issue by JustinTimeCuber** [PepperCode1/Continuity#113]
Continuity 2.0.0
Minecraft 1.18.2
Sodium 0.4.1
Indium 1.0.2
Example resource pack: https://www.curseforge.com/minecraft/texture-packs/emissive-ores-1-17
![2022-06-09_00 47 12](https://user-images.githubusercontent.com/46458276/172773524-d6acb5de-f58e-4aaa-8936-5949920a6933.png)
See the ore blocks in my inventory.

**Comment by PepperCode1** [comment]
Update Indium to 1.0.3.
