### ISSUE TITLE
Loading Loop on 1.19

### ISSUE THREAD

**Issue by OuroborosBoy** [PepperCode1/Continuity#115]
It seems something is causing the game to get stuck in a loading loop at the Mojang screen when launched with this mod in 1.19. I can't tell if it's some kind of conflict, but it only happens when Continuity is installed and it stops when I remove it.

[latest.log](https://github.com/PepperCode1/Continuity/files/8883542/latest.log)

**Comment by Funtimes909** [comment]
It's an issue with resource packs, I am also having this exact same issue

**Comment by PepperCode1** [comment]
Looks like an incompatibility with Forgero.

**Comment by SigmundGranaas** [comment]
Forgero 0.9.0 has been released which I am pretty sure resolves this error. I think the issue can be closed.

**Comment by verdantspell** [comment]
I'm getting a loading loop on 1.19 without forgero, Not sure what mod is causing it cause I haven't had time to troubleshoot

**Comment by Sweenus** [comment]
> I'm getting a loading loop on 1.19 without forgero, Not sure what mod is causing it cause I haven't had time to troubleshoot

The loading loop also occurs if you forgot to install Indium while running Sodium. Might want to double check... I thought I had it installed but didn't.

**Comment by PepperCode1** [comment]
I assume this issue has been resolved. If anyone is having problems, open a new issue.
