### ISSUE TITLE
Game taking upwards of 9 minutes to load assets with continuity installed

### ISSUE THREAD

**Issue by Funtimes909** [PepperCode1/Continuity#116]
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain top->top in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain side1->side1 in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain side2->side2 in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain double1->double1 in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain top->top in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain inner->inner in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain side1->side1 in minecraft:item/waxed_stairs
18:05:27.981
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain side2->side2 in minecraft:item/waxed_stairs
18:05:27.982
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain top->top in minecraft:item/waxed_stairs
18:05:27.982
net.minecraft.class_793
Worker-Main-1
Unable to resolve texture due to reference chain top->top in minecraft:item/waxed_stairs
Crash report

**Comment by PepperCode1** [comment]
Full log? This is not enough information.

**Comment by PepperCode1** [comment]
Any performance issues can be attributed to Fabric API's resource loader. If you disable all built-in packs that are loaded through it, your reload time will return to normal. I am trying to resolve this from Fabric's side.
