### ISSUE TITLE
Framerate Lags heavily after going through portals

### ISSUE THREAD

**Issue by RSteinebrunner** [PepperCode1/Continuity#117]
Framerate will read ok after a few minutes, but after loading through a nether portal, the game skips heavily, at aprox. 1-5 fps. The game must be fully rebooted to work normally again. This affects the 1.19 version, running fabric, sodium, indum, and a shader using emissive lighting.

**Comment by PepperCode1** [comment]
Log?

**Comment by PepperCode1** [comment]
I am closing this because no additional information was provided.
