### ISSUE TITLE
Support for the textures in Better Vanilla Building Texture Pack 1.19?

### ISSUE THREAD

**Issue by SanctusStreams** [PepperCode1/Continuity#119]
Wanted to know if there was a way to get the connected textures in Better Vanilla Building Texture Pack 1.19 to work? Stay True works with this resource pack, but Better Vanilla Building Texture Pack 1.19 doesn't. 
Thanks!
![2022-06-13_11 14 48](https://user-images.githubusercontent.com/105398391/173386567-5b34b86b-3fe3-4535-bdb4-041d4743334b.png)
![2022-06-13_11 14 04](https://user-images.githubusercontent.com/105398391/173386583-793d1b45-9532-47f5-9971-43096c480d17.png)

**Comment by SanctusStreams** [comment]
Also for contrast here is the Stay True connected textures working as they should:
![2022-06-13_11 16 37](https://user-images.githubusercontent.com/105398391/173386873-3baeacd7-3b40-40f2-ab64-cf3f59d74c9b.png)
![2022-06-13_11 16 17](https://user-images.githubusercontent.com/105398391/173386886-751c5bae-5d78-48f1-a0f9-b8475e7de9c3.png)
![2022-06-13_11 16 25](https://user-images.githubusercontent.com/105398391/173386896-d4746941-b9fd-4550-b5c8-d909bf07b801.png)

**Comment by PepperCode1** [comment]
From the screenshots it looks like it is working. BVB does not contain overlay textures anymore; they are in an [addon](https://www.curseforge.com/minecraft/texture-packs/bvb-overlays) that must be installed separately.

**Comment by PepperCode1** [comment]
I have tested BVB + the overlay addon on the latest development version and it is working correctly.
