### ISSUE TITLE
Resource load failed

### ISSUE THREAD

**Issue by HoodieRocks** [PepperCode1/Continuity#12]
For some reason when loading BetterVanillaBuilding, it won't load, and displays the error "Resource reload failed", is there a reason for this or is it actually a bug

**Comment by PepperCode1** [comment]
Please provide a log. We cannot help if we do not know what went wrong.

**Comment by HoodieRocks** [comment]
Sorry, forgot
https://pastebin.com/CUWi3mtg

**Comment by PepperCode1** [comment]
Sorry, forgot to reply to this. CITResewn is causing the errors, which can be fixed by enabling the configuration option that allows for invalid identifiers.

**Comment by HoodieRocks** [comment]
There isn't an option in the ingame config or the actual continuity.json for allowing invalid identifiers?

**Comment by PepperCode1** [comment]
No, they are always on for Continuity.

**Comment by MadDog443** [comment]
Wait, then if it's always on, then how is this bug still apparent? (ie. "Turn on config that is always on to fix issue")

**Comment by PepperCode1** [comment]
It seems my original response was ambiguous. I meant to enable the option in CIT Resewn, because it is the mod that is causing the problem.

**Comment by MadDog443** [comment]
AH
