### ISSUE TITLE
Emissive resource packs that all/some of the emissive blocks in the pack won't glow

### ISSUE THREAD

**Issue by EGOIST1372** [PepperCode1/Continuity#123]
https://www.curseforge.com/minecraft/texture-packs/emissive-light-glow
none of the blocks glows

**Comment by PepperCode1** [comment]
Send a comparison screenshot between Optifine and Continuity with this pack.

**Comment by EGOIST1372** [comment]
@PepperCode1 
with optifine
![image](https://user-images.githubusercontent.com/86555131/173890609-41bb5dc6-8778-4137-886d-c7f53c7b2e7f.png)

without optifine + all other mods that replace optifine like continuity, ETF, CITresewn, CEM, puzzle, chime , etc ...
image place holder: no emmisive blocks :)

asking for image comparison is no good here since this is an emmisive resource pack when it works means has emissive textures and when it doesn't mean no emmisive textures.

before continuity upgrades to support emmisive textures I tried all of the emmisive texture resource packs and as we speak I'm testing all of them again.

So far this packs working great: (none of these worked before)
https://www.curseforge.com/minecraft/texture-packs/additional-emissives
https://www.curseforge.com/minecraft/texture-packs/radiant-pack
https://www.curseforge.com/minecraft/texture-packs/emissive-txf

and these packs still not working:
https://www.curseforge.com/minecraft/texture-packs/emissive-light-glow
https://www.curseforge.com/minecraft/texture-packs/luceo

I'm still testing and will create a unified issue for all of the packs that not working. it seems one by one is so cluttering

**Comment by EGOIST1372** [comment]
should I report them all here? and change the title? or you can change it and I provide results or not?
let me know
also thank you for your hard work that made this possible for us <3

**Comment by BigManMatice** [comment]
I have the same issue with a other resource pack

**Comment by PepperCode1** [comment]
The image with Continuity was not uploaded. Any packs that do not work can be added to this issue.

**Comment by EGOIST1372** [comment]
https://www.curseforge.com/minecraft/texture-packs/glowing-bits-and-bobs
this packs also works great but there are some issues with some blocks in hand
some ore blocks in hand doesn't glow but some other glow but when you place them on ground they all glow
![image](https://user-images.githubusercontent.com/86555131/173911164-7f0d8fa4-0743-4ff7-89b2-d5d4a5fea36b.png)
![image](https://user-images.githubusercontent.com/86555131/173911232-1e8428e2-c05e-49cc-8ca8-22c901d4e2d5.png)
![image](https://user-images.githubusercontent.com/86555131/173911283-c3ec18e5-ecbb-41ab-be8d-79b92ad763f6.png)
![image](https://user-images.githubusercontent.com/86555131/173911341-85a82a38-be7f-4f02-95d8-6e9df840429e.png)

**Comment by PepperCode1** [comment]
Make sure you are testing these packs one at a time and not all at once because resource pack conflicts are not Continuity's problem.

**Comment by EGOIST1372** [comment]
yeah I Know
I test them one by one

**Comment by EGOIST1372** [comment]
these 2 resource packs works great with no problem(these packs has no emissive coal ore)
https://www.curseforge.com/minecraft/texture-packs/classic-emissive-ores
https://www.curseforge.com/minecraft/texture-packs/emissive-vanilla-textures

**Comment by EGOIST1372** [comment]
https://www.curseforge.com/minecraft/texture-packs/glowing-ores
works with no problem (has emissive coal ore)

**Comment by EGOIST1372** [comment]
https://www.curseforge.com/minecraft/texture-packs/new-glowing-ores
this pack has 2 variants. one is normal and the other has emissive borders as well
normal one works great with no problem but border one doesn't work at all. no glow(also normal one has no emissive gilded black stone)

**Comment by PepperCode1** [comment]
Can you send a log from using any one of the packs that don't quite work?

**Comment by EGOIST1372** [comment]
[2022-06-13-6.log.gz](https://github.com/PepperCode1/Continuity/files/8913220/2022-06-13-6.log.gz)
[2022-06-15-1.log.gz](https://github.com/PepperCode1/Continuity/files/8913222/2022-06-15-1.log.gz)
[2022-06-15-2.log.gz](https://github.com/PepperCode1/Continuity/files/8913223/2022-06-15-2.log.gz)
[latest.log](https://github.com/PepperCode1/Continuity/files/8913225/latest.log)
all the logs of this session (but idk if all of the logs are helpful or not)

**Comment by EGOIST1372** [comment]
https://www.curseforge.com/minecraft/texture-packs/shaderless-glowing-ores
this mod doesn't have nether ores included it seems(also no coal ore)
but everything works great and on top of that ores have animations that fades to dark then brighten that works flawlessly (nice :D)

**Comment by EGOIST1372** [comment]
https://www.curseforge.com/minecraft/texture-packs/visible-ores
https://www.curseforge.com/minecraft/texture-packs/pure-visible-ores
both works flawlessly. from same author and both has no emissive gilded black stone

**Comment by PepperCode1** [comment]
> https://www.curseforge.com/minecraft/texture-packs/glowing-bits-and-bobs this packs also works great but there are some issues with some blocks in hand some ore blocks in hand doesn't glow but some other glow but when you place them on ground they all glow ![image](https://user-images.githubusercontent.com/86555131/173911164-7f0d8fa4-0743-4ff7-89b2-d5d4a5fea36b.png) ![image](https://user-images.githubusercontent.com/86555131/173911232-1e8428e2-c05e-49cc-8ca8-22c901d4e2d5.png) ![image](https://user-images.githubusercontent.com/86555131/173911283-c3ec18e5-ecbb-41ab-be8d-79b92ad763f6.png) ![image](https://user-images.githubusercontent.com/86555131/173911341-85a82a38-be7f-4f02-95d8-6e9df840429e.png)

The ore texture in the hand looks nothing like the texture when placed, and I assume the pack only has emissive textures for the textures of the placed blocks, so this is cannot be an issue with Continuity. I expect this pack to work exactly the same way on Optifine.

**Comment by PepperCode1** [comment]
Also, while doing testing on Optifine vs. Continuity, make sure that Optifine's "Alternate Blocks" option is set to "On" and that the "Connected Textures" option matches on both setups. Continuity's option being set to "On" is equivalent to Optifine's option being set to "Fancy".

**Comment by EGOIST1372** [comment]
> The ore texture in the hand looks nothing like the texture when placed, and I assume the pack only has emissive textures for the textures of the placed blocks, so this is cannot be an issue with Continuity. I expect this pack to work exactly the same way on Optifine.

but as you can see I put an example of copper that has emissive texture in hand. there are ores that have emissive texture in hand but seems some of them doesn't glow for some reason that IDK. but it might be continuity

**Comment by PepperCode1** [comment]
Copper works because the textures of the block and item are the same. This is not true for the rest of the items.

**Comment by EGOIST1372** [comment]
ahhhhh that might be it. good eyes
also
https://www.curseforge.com/minecraft/texture-packs/classic-emissives
all the items in this resource pack works with no problem. so many items was there to test ;-;
I contiune the test another time. time to rest

**Comment by PepperCode1** [comment]
It would be much more useful to test the original few packs that did not work on Continuity on Optifine instead with the settings that I described a few replies ago. There is no point in testing every pack, especially if most of them work.

**Comment by PepperCode1** [comment]
I have tested the first pack and it works correctly. It may not have worked for you because you had DashLoader installed, so try without it. If you are certain that the cause is DashLoader (after testing), open a new issue here or on the DashLoader repository.

**Comment by EGOIST1372** [comment]
> I have tested the first pack and it works correctly. It may not have worked for you because you had DashLoader installed, so try without it. If you are certain that the cause is DashLoader (after testing), open a new issue here or on the DashLoader repository.

I just tested without dashloader and still it's not working
how it works for you?!

**Comment by EGOIST1372** [comment]
Are you sure you tested this pack? and you had no optifabric/optifine installed?
https://www.curseforge.com/minecraft/texture-packs/emissive-light-glow

**Comment by PepperCode1** [comment]
Yes, I am sure. I also still do not know what did not work for you because you did not send the screenshot.
> image place holder: no emmisive blocks :)

**Comment by EGOIST1372** [comment]
nothing works. that's why I did not send any.
But here you go. no dashloader no optifine
![image](https://user-images.githubusercontent.com/86555131/174333705-fe98f37f-c267-4527-a9ab-d9711ad2d396.png)

and after I removed dashloader loading resource packs takes up to 2 min. WTH!!!

**Comment by PepperCode1** [comment]
All of those blocks worked correctly for me, so either this is a mod conflict or your configuration/setup is incorrect.

**Comment by EGOIST1372** [comment]
anyway, beside that pack thses 2 pack also did not work as well. have you tested them?
https://www.curseforge.com/minecraft/texture-packs/luceo
https://www.curseforge.com/minecraft/texture-packs/new-glowing-ores (border variant doesn't work)

**Comment by EGOIST1372** [comment]
OK, I re-downloaded the ELG pack and installed dashloader back and tried again. seems now working lol
but redstone block (9x9 redstone dust) is not working . no glow at all

**Comment by EGOIST1372** [comment]
Also it seems Luceo pack works too now after re-download :| 
but the "new glowing ores border variant" doesn't work. it seems this is the only one that doesn't work

**Comment by EGOIST1372** [comment]
ok now I went ahead and looked into ELG's files. and it seems there is no redstone block there :||||||||||
there is one in the images in image tab of the mod but ... 
ok now the only problem is 
https://www.curseforge.com/minecraft/texture-packs/new-glowing-ores (border variant doesn't work)

**Comment by EGOIST1372** [comment]
nevermind at all :|
what is wrong with these packs today
the border variant has no file in it at all :||||||||||||
I'm done. I'm gonna retire from testing stuff. too old for these shenanigans 
sorry for wasting your time meanwhile ;-;

**Comment by EGOIST1372** [comment]
BTW I found an interesting resource pack that claims doesn't need optifine for emissive stuff
https://www.curseforge.com/minecraft/texture-packs/coredynamicemissives
https://github.com/ShockMicro/VanillaDynamicEmissives

**Comment by TheNukeLore** [comment]
that resourcepack uses core shaders which wont work with sodium.

**Comment by EGOIST1372** [comment]
@TheNukeLore it seems it works with continuity + sodium
but has a bug, when you place it down it doesn't glow But 
when you held the item it glow and when you destroy it also has glowing particles 
destroying and helding example:
![image](https://user-images.githubusercontent.com/86555131/174345843-622d219a-c384-40a8-be41-202ee378e88b.png)

**Comment by TheNukeLore** [comment]
anything placed down wont glow, as anything using something called "terrain core shaders" simply wont work with sodium, which is things like blocks placed in the world, it works in your hand due to the fact that core shaders for situations like gui and hud rendering still work.

**Comment by EGOIST1372** [comment]
thanks for the info
it seems all the items in the pack doesn't even work in hand, like ice and blaze rod
but lime concrete super glows :D
![image](https://user-images.githubusercontent.com/86555131/174347498-444f3ee3-bbb8-4d00-a2f9-688c0c753a90.png)

**Comment by EGOIST1372** [comment]
@PepperCode1 I didn't want to make another issue but you need to take a look at this [issue](https://github.com/Traben-0/Entity_Texture_Features/issues/71)

**Comment by PepperCode1** [comment]
Continuity does not support emissives for custom rendered items. This is not a bug and is not planned.
Edit: the 2D model of the trident is not custom rendered so it should work. I will investigate this later.

**Comment by PepperCode1** [comment]
Tridents and spyglasses specifically will not work due to an Indigo/Indium oversight. I will see if this can be fixed.

**Comment by PepperCode1** [comment]
I have helped Indigo and Indium resolve the 2D trident (and spyglass) issue, which will allow it to work correctly with Continuity. Fabric API 0.56.1 and Indium 1.0.6 for 1.18.2/1.19 contain the fix.

**Comment by EGOIST1372** [comment]
thanks already updated both <3
