### ISSUE TITLE
Some random block texture overlays dont have transparency.

### ISSUE THREAD

**Issue by Terminxa** [PepperCode1/Continuity#124]
For context, I am using JustTimm's Vanilla Additions and in the nether, the random block texture overlays are supposed to have transparency. For some reason, using the mod replaces the transparency with just orange. This only happens in the nether, as there are other random block texture overlays in the overworld that do not have this issue. 
![2022-06-15_19 57 22](https://user-images.githubusercontent.com/106455196/173961358-60ee9d57-cc60-49ef-88b6-bdb891785e40.png)
![2022-06-15_19 57 55](https://user-images.githubusercontent.com/106455196/173961409-21532afc-d790-451e-b16e-024e321ed211.png)
The overworld texture also has transparency

**Comment by Terminxa** [comment]
Another thing, the nether one has an animation, but the overworld one does not. I can still see the animation though. Also, my mod list is the following: 
CompleteConfig
ClothConfig
FastOpenLinksAndFolders
Puzzle
ToroHealth
CIT Resewn
LambDynamicLights
WorldEdit
Entity Culling
Fabric API
3D skin layers
Continuity obviously
Indium
Capes
Colormatic
Xaeros Minimap and Worldmap
Starlight
Sodium
Shulker Box Tooltip
OptiGUI
ModMenu
Iris
Logical Zoom
Fabric Language Kotlin
Entity Texture Features
CEM
Advancement Info

**Comment by PepperCode1** [comment]
Try with only Continuity and Fabric API.
