### ISSUE TITLE
Problem with texture binding, always takes one texture

### ISSUE THREAD

**Issue by ccyounga** [PepperCode1/Continuity#131]
Greetings to all! A very strange thing is observed on version 1.18.2 fabric. On the server, all linked textures are linked using the ground texture. How to fix it?
Structures do not contain earth blocks. Resourcepack: conquest reforged.
https://imgur.com/AwZuxXk
https://imgur.com/li9hNi2

**Comment by PepperCode1** [comment]
I have tested this with the latest version and it works correctly. Update Continuity to the latest version.
