### ISSUE TITLE
Not having connected textures vertically

### ISSUE THREAD

**Issue by POLAR40** [PepperCode1/Continuity#133]
For some reason when I place panes ( it works fine with the main block ),  vertically it doesn't connected the texture. Now I don't know if this is just supposed to happen - as part of the pack but on youtubers videos they use continuity and it doesn't seem to do the same thing . . . ? Does anyone know why this is happening ?
![bug issue](https://user-images.githubusercontent.com/108180734/175772643-3fef1c99-88a9-4044-80b1-14f6fb58fd26.png)

**Comment by PepperCode1** [comment]
Enable the `continuity/glass_pane_culling_fix` resource pack included with the mod.
