### ISSUE TITLE
Missing color when using connected textures

### ISSUE THREAD

**Issue by SeineEloquenz** [PepperCode1/Continuity#134]
Hello there,

I'm having a problem with Continuity when using connected textures. Whenever I turn the setting on, wool, concrete, concrete powder, terracotta turn to the same texture which always is a shade of gray.
I can't find any errors related to Continuity in the game logs.
I'm running Continuity on Linux using X11 on an Nvidia card.

<details>
  <summary>Screenshots</summary>
The upper row contains some wool types, the lower row terracotta.
While in the screenshots i have different mods turned on as well, the problem also occurs when only running fabric and Continuity.

![2022-06-28_19 22 00](https://user-images.githubusercontent.com/34923333/176246279-4a3d3106-400e-4a2e-b28e-1dea7b3fc157.png)

![2022-06-28_19 22 10](https://user-images.githubusercontent.com/34923333/176246287-b9b9799e-f9f1-4d66-9cde-c12955bc872d.png)

  
</details>

**Comment by PepperCode1** [comment]
You need Colormatic for color features, which are not a goal of Continuity. Installing Colormatic will fix your issue.

**Comment by SeineEloquenz** [comment]
I would then propose to add the info to the mod's pages that Continuity alone might break block colors and Colormatic fixes this, as this was not obvious for me.

**Comment by PepperCode1** [comment]
Continuity does not break them. It just doesn't support them. Continuity never claims to support these features.

**Comment by SeineEloquenz** [comment]
I'm confused. The colors I mentioned are the colors used in vanilla minecraft, no modded features.
As a user I would expect colors to stay the same if I install a mod for an unrelated feature like connected textures.
Do as you like, but I'd consider this useful information a potential user should be told about.
