### ISSUE TITLE
Would you like to make Template to make Overlay Texture for Modded Block?

### ISSUE THREAD

**Issue by ardissaps** [PepperCode1/Continuity#136]
Hello thank you for the great mod you made there!
I wish I could make overlay for block from [Unearthed](https://www.curseforge.com/minecraft/mc-mods/unearthed). Would you like to give example 1 block as a template? I was able to make vanilla block to have overlay on their block (using [Stay True](https://www.curseforge.com/minecraft/texture-packs/stay-true) template for personal use), but cannot vice-versa, need template that can make Unearthed have overlay on vanilla block or other mod block.

**Comment by PepperCode1** [comment]
I might make new CTM documentation at some point, but it is a lot of work. I do not have time to work on this right now.

**Comment by DarianLStephens** [comment]
Is it even possible to make overlays for modded blocks?
There's no namespace in the properties file, and I can't get it working by either omitting or including it for modded blocks.

Being one long line in one giant file is also a bit annoying, but workable for a modpack.

**Comment by DarianLStephens** [comment]
There's also no wiki that I can find, which is a problem.
The link on Github just leads to a non-existent Github wiki page here, which gets redirected back to the main page.

**Comment by vinnyg0621** [comment]
this is what I'm looking for! please answer this question

**Comment by PepperCode1** [comment]
I published the Continuity wiki around June of this year. It contains the differences between how OptiFine CTM and Continuity CTM work. I will not be making completely new documentation for OptiFine CTM because good documentation for this feature is [already available](<https://optifine.readthedocs.io/ctm.html>).
