### ISSUE TITLE
Patrix Resource Pack: Coloured blocks (wool and concrete) always appear white

### ISSUE THREAD

**Issue by SledgeDragon** [PepperCode1/Continuity#141]
Specific coloured blocks always appear white when using Patrix with this mod. 
They include:
- Wool
- Concrete
- Terracotta
- Concrete Powder

For some reason, other coloured blocks don't have this issue. 
This includes:
- Glass
- Glass Panes
- Shulker Boxes
- Beds
- Candle

Continuity Without Patrix:
![2022-07-15_14 47 34](https://user-images.githubusercontent.com/96208449/179291328-057161f8-3b75-4460-839a-6c879b33133a.png)

Continuity With Patrix
![2022-07-15_14 48 24](https://user-images.githubusercontent.com/96208449/179291434-a167c7a7-af61-4f78-9c68-b446cb3f73ab.png)

Let me know if anyone else can recreate this issue and if not, I will experiment with some other mods I have installed. 

I have Sodium, Iris, Indium, Continuum, Distant Horizons, Starlight, and Lithium. These are all of the graphical and performance mods I have installed.

**Comment by PepperCode1** [comment]
Install Colormatic. Continuity does not provide support for Optifine's color features.
