### ISSUE TITLE
Continuity 1 18 2 Fabric - Не удалось загрузить пакет ресурсов

### ISSUE THREAD

**Issue by usemauroy** [PepperCode1/Continuity#144]
При установке мода Continuity - пакеты ресурсов установились, но не работают. Если их выбрать в пакетах ресурсов - ничего не поменяеться. А если использовать с другими пакетами ресурсов - вылетает игра.

**Comment by amwao** [comment]
Скачай INDIUM без него мод не работает, это написано в дискорде разработчика мода. Если что индиум это мод.

**Comment by PepperCode1** [comment]
Duplicate of #107.
