### ISSUE TITLE
Skipped language file: continuity:lang/ru_ru.json

### ISSUE THREAD

**Issue by MJRamon** [PepperCode1/Continuity#148]
continuity-2.0.0+1.19

Skipped language file: continuity:lang/ru_ru.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 9 column 2 path $.options.continuity.custom_block_layers.tooltip)

**Comment by PepperCode1** [comment]
This was fixed in 2.0.1.
