### ISSUE TITLE
Connected Textures arent even working

### ISSUE THREAD

**Issue by xandercreates** [PepperCode1/Continuity#15]
So I installed Continuity, and loaded the built in packs only to see no change in any of the glass.
Here is a screenshot

Version: 1.17.1
Fabric Version: 0.11.7
![2021-10-13_21 47 54](https://user-images.githubusercontent.com/69139978/137236852-d9d6c7b8-e926-471c-90c5-7d8c3296de0b.png)
![image](https://user-images.githubusercontent.com/69139978/137236930-b926d400-9151-4ef4-9500-0c9bca7759a0.png)

**Comment by TheNukeLore** [comment]
Do you have sodium? If so make sure to install indium

**Comment by xandercreates** [comment]
I already have it installed.

**Comment by FwuffyPetsOwO** [comment]
give a full mods list please

**Comment by xandercreates** [comment]
I dont have modmenu or anything to show my mods ingame so here.

![image](https://user-images.githubusercontent.com/69139978/137237358-86fae2f9-a33d-4abb-bd32-7184829b9178.png)

**Comment by FwuffyPetsOwO** [comment]
and the log file as well, it can be found in the .minecraft/logs folder (latest.log will usually do fine)

**Comment by xandercreates** [comment]
well first heres a part of it from my game output

21:36:05.604
Using missing texture, unable to load minecraft:textures/continuity_reserved/7628902bd3224fe8e8c47b7dc988d0ea.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/7628902bd3224fe8e8c47b7dc988d0ea.png
21:36:05.605
Using missing texture, unable to load minecraft:textures/continuity_reserved/986ae73997e36d8795c3d533eba37d61.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/986ae73997e36d8795c3d533eba37d61.png
21:36:05.606
Using missing texture, unable to load minecraft:textures/continuity_reserved/12640a08c84d1381a21ee06de2152edb.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/12640a08c84d1381a21ee06de2152edb.png
21:36:05.606
Using missing texture, unable to load minecraft:textures/continuity_reserved/3b41f31a7f9cd82b1de6e7ac39ecb7a7.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/3b41f31a7f9cd82b1de6e7ac39ecb7a7.png
21:36:05.607
Using missing texture, unable to load minecraft:textures/continuity_reserved/27ac02fda664eaee09c03272f0bcad0c.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/27ac02fda664eaee09c03272f0bcad0c.png
21:36:05.607
Using missing texture, unable to load minecraft:textures/continuity_reserved/5541f1874eb66f53419f4a3ed66cf6b1.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/5541f1874eb66f53419f4a3ed66cf6b1.png
21:36:05.610
Using missing texture, unable to load minecraft:textures/continuity_reserved/d1e24a04ed2e6c263049e885a84bcb19.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/d1e24a04ed2e6c263049e885a84bcb19.png
21:36:05.611
Using missing texture, unable to load minecraft:textures/continuity_reserved/ced7733b2762ddd3ef916d7d334c3dbe.png : java.io.FileNotFoundException: minecraft:textures/continuity_reserved/ced7733b2762ddd3ef916d7d334c3dbe.png

**Comment by xandercreates** [comment]
Narrowed down to three mods. Attempting to pin it to one mod

**Comment by xandercreates** [comment]
Confirmed, MoreMcMeta caused the issue. Wonder what exactly makes it incompatible
