### ISSUE TITLE
Animation Desync

### ISSUE THREAD

**Issue by scutoel** [PepperCode1/Continuity#151]
Animations can sometimes get desync'd. I believe it happens when you pass through a portal
![image](https://user-images.githubusercontent.com/67754858/183139310-cf1141ff-c9ce-486c-9b02-94f19112133f.png)

**Comment by PepperCode1** [comment]
Continuity does not load or directly interact with animated textures in any way. Just in case though, which resource pack is this? I will do some testing to ensure that it cannot be fixed.

**Comment by scutoel** [comment]
https://www.planetminecraft.com/texture-pack/faithful-ctm-32x/
Here is the pack I was using. The animations line up within the files

**Comment by Julienraptor01** [comment]
if you want animated textures you need this mod alongside the ones you have
https://modrinth.com/mod/animatica/

**Comment by scutoel** [comment]
animated block textures are a vanilla feature

**Comment by PepperCode1** [comment]
Also are you using Sodium and if so does removing it fix the issue?

**Comment by Julienraptor01** [comment]
> animated block textures are a vanilla feature

oh yeah i forgot that oops

**Comment by PepperCode1** [comment]
I believe this is a Sodium issue that will be addressed soon. If this happens without Sodium, open a new issue.
