### ISSUE TITLE
Textures Not Connecting In 1.19

### ISSUE THREAD

**Issue by Wizchilla** [PepperCode1/Continuity#153]
So I recently followed a tutorial on how to setup connected textures for Iris, because that was the one feature from Optifine I greatly missed. Upon opening up the game, all the mods I was told to installed were properly there (namely: Continuity, Iridium, Iris, Mods Menu, and Sodium). However, once entering a world the textures were not connecting. I checked the options in the mod menu for Continuity and all of them were properly set to connect the game's textures.

I have attached a list of the mods my latest log includes, if any other information is needed that I am leaving out just let me know.
[listOfLoggedMods.txt](https://github.com/PepperCode1/Continuity/files/9277663/listOfLoggedMods.txt)

**Comment by PepperCode1** [comment]
Did you enable the default resource packs?

**Comment by Wizchilla** [comment]
Ah there we go, did not see those before. The issue has been solved, thank you!
