### ISSUE TITLE
Game crashes when falling blocks are rendered

### ISSUE THREAD

**Issue by be4ryllium** [PepperCode1/Continuity#155]
Platform:
Quilt Loader 1.19.1

Error message:

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
Exit Code: -1

**Comment by PepperCode1** [comment]
Duplicate of #107.
