### ISSUE TITLE
Glass Rendering in Water

### ISSUE THREAD

**Issue by Emeraldog** [PepperCode1/Continuity#157]
![Screenshot 2022-08-14 150106](https://user-images.githubusercontent.com/111246629/184551279-abf22d1a-5738-42a7-a2d1-27cdf4350655.png)

There is a rendering issue when there is water behind glass. The middle area of the glass appears fine, but on the curves of the glass circle I made, it looks weird.

**Comment by PepperCode1** [comment]
CaffeineMC/sodium-fabric#38
