### ISSUE TITLE
Scaffolding drop

### ISSUE THREAD

**Issue by CsD4vid** [PepperCode1/Continuity#159]
Hello!
I found a bug with scaffolding falling.
If the scaffhold is reached its limit and want to start to fall (6 blocks) then the game stops and crashes.
The video shows it.

https://user-images.githubusercontent.com/111366912/185340597-e6559707-2002-48a0-9743-c73451a50fa7.mp4

**Comment by PepperCode1** [comment]
Duplicate of #107.
