### ISSUE TITLE
Continuity 1.0.1 release version changed something, that broke NAPP textures with corner upside down stairs

### ISSUE THREAD

**Issue by SplendidAlakey** [PepperCode1/Continuity#16]
**MC** 1.17.1
**Fabric API** 0.41.0
**Continuity** 1.0.1
~~**[MineGate](https://www.curseforge.com/minecraft/mc-mods/minegate-moreblocks)** 1.1.6~~ Not necessary, see comment below.
**[NAPP](https://www.curseforge.com/minecraft/texture-packs/napp-free-version-1-01)** 3.5 (tested with 3.4 too)

1. Install Continuity, ~~MineGate~~ and NAPP
2. Activate only NAPP texture pack
3. Place vertical stairs from the MineGate mod in such a way where you can see the bottom part of it, or place vanilla stairs upside down in a corner

With Continuity 1.0.0 and 1.0.1 build10, everything appears as intended. But with Continuity 1.0.1 release, the bottom part is culled. I didn't test with other texture packs, so it might be a problem with NAPP, again, but since it didn't happen on previous versions on Continuity, I figured I'd report it here.

That's how it looks with 1.0.1 release: [removed]
![2021-10-19_19 31 34](https://user-images.githubusercontent.com/86702831/137964752-529c18d6-9eb5-48f5-bbe4-1418643eef49.png)

That's how it should be and how it used to look with 1.0.0 and 1.0.1 build 10: [removed]
![2021-10-19_19 33 40](https://user-images.githubusercontent.com/86702831/137964766-c8b83685-15ed-40e7-80f7-a3c6d9f6c66e.png)

**Comment by SplendidAlakey** [comment]
Actually, the issue happens with vanilla stairs placed upside down in a corner, so MineGate has nothing to do with it, it was just easier to spot.

![2021-10-19_20 06 42](https://user-images.githubusercontent.com/86702831/137966451-3bf8a67c-3082-4d59-b92d-845611993212.png)

**Comment by PepperCode1** [comment]
I forgot to add a single line when I replaced the culling code, which causes only the first quad on a cull face to cull correctly and the rest to always cull. Sorry about that. I'll try to fix this and release 1.0.2 today.

**Comment by PepperCode1** [comment]
This should be fixed with commit af05590. I will do a full release as well, since this is a critical bug.
