### ISSUE TITLE
Continuity doesn't allow me to use resource packs.

### ISSUE THREAD

**Issue by vitor37137** [PepperCode1/Continuity#161]
When i have the Continuity mod enabled, all my resource packs get disabled and i'm only able to enable them again when i disable the mod.

The game version is 1.19.2 (also not working on 1.19.1)
The mod version is 2.0.1.

In 1.19 i was able to use those resource packs, they only stopped working on the versions mentioned above

The packs are: Vanilla Tweaks custom pack and Visible Ores.

**Comment by PepperCode1** [comment]
Send a log.

**Comment by PepperCode1** [comment]
I am closing this because no additional information was provided.
