### ISSUE TITLE
Cannot use Continuity with other resource packs

### ISSUE THREAD

**Issue by billiegoats** [PepperCode1/Continuity#165]
If I try to turn on either of the Continuity resource packs while using any other pack (specifically Motschen's Better Leaves & Leaf Culling + LambdaBetterGrass), the game gets stuck on the loading screen until it either crashes or I force quit. I was able to use other resource packs with Continuity just fine in 1.18, but in 1.19.2 I can't.

**Comment by PepperCode1** [comment]
Send a log.

**Comment by PepperCode1** [comment]
I am closing this because no additional information was provided.
