### ISSUE TITLE
Glass panes rendering weird

### ISSUE THREAD

**Issue by jucogjucogi** [PepperCode1/Continuity#167]
There's weird lines beetwen glass panes, here's screenshot:
![a](https://user-images.githubusercontent.com/113132803/189189179-adaf61c2-e8f0-46b8-bb87-28e20f5ed96f.png)
also i use sodium with indium and default mod's pack on top

**Comment by PepperCode1** [comment]
Enable the built-in glass pane culling fix resource pack.
