### ISSUE TITLE
Glass Panes are not seamless [bug?]

### ISSUE THREAD

**Issue by Juno133701** [PepperCode1/Continuity#169]
Version 1.19.0 - using Sodium - I downloded this for the Glass blocks mainly, but I noticed that the glass panes have a ugly texture on the bottom and top that doest connect when you stack them on top of each other like the blocks do, screenshots attached.

![Screenshot 2022-09-17 152608](https://user-images.githubusercontent.com/113781453/190860756-6ad9a494-04f7-487c-811f-a28e48f37d92.png)
![Screenshot 2022-09-17 152718](https://user-images.githubusercontent.com/113781453/190860770-910dc0d6-d7a2-437a-a6cd-af27ddbd48c3.png)

**Comment by PepperCode1** [comment]
Enable the built-in glass pane fix pack.

**Comment by Juno133701** [comment]
> Enable the built-in glass pane fix pack.

Thx for answering, do I find that in the Mod menu, or is it a command or something?

**Comment by PepperCode1** [comment]
It is a resource pack, found in the resource pack menu.

**Comment by Juno133701** [comment]
> It is a resource pack, found in the resource pack menu.

Thx, I didn't even notice there was a new resource pack.

It works now.
