### ISSUE TITLE
Water trough glass glitched

### ISSUE THREAD

**Issue by Aeldit** [PepperCode1/Continuity#17]
This doesn't happend without continuity (there is the exact same bug with CTMF)
![2021-10-20_14 00 10](https://user-images.githubusercontent.com/81476169/138088920-0bcb97b0-a4a7-4381-8cf6-1cf452b1129e.png)
![2021-10-20_14 00 13](https://user-images.githubusercontent.com/81476169/138088924-0b0d95df-3a8b-4218-b67c-5c9b8bcf50b3.png)

**Comment by TheNukeLore** [comment]
Sounds like a sodium #38 bug

**Comment by Aeldit** [comment]
Well the thing is that it happens without sodium

**Comment by PepperCode1** [comment]
It only happens with Sodium for me. Indigo and Canvas work correctly. What mods and resource packs are you using?

**Comment by Aeldit** [comment]
The mods that touches the graphical part of the game are : sodium, sodium extra, light overlay, iris, starlight, continuity, indium

**Comment by PepperCode1** [comment]
Does it still happen if you remove Sodium, Sodium Extras, and Indium?

**Comment by Aeldit** [comment]
I'll try this this afternoon

**Comment by Aeldit** [comment]
Yep, my bad. Doesn't happens without sodium so i'm going to close this issue.
