### ISSUE TITLE
Cannot set Vanila Tweaks Resourcepack

### ISSUE THREAD

**Issue by futag** [PepperCode1/Continuity#170]
Some selector from vanila tweaks resourcepack, make this set resourepack failed when install continuity mod even though the continuity resousespack hasn't been installed yet

**Comment by futag** [comment]
Resource pack: [VanillaTweaks_r137394.zip](https://github.com/PepperCode1/Continuity/files/9621274/VanillaTweaks_r137394.zip)

**Comment by PepperCode1** [comment]
Logs?

**Comment by yarndinasti** [comment]
[2022-09-22-3.log](https://github.com/PepperCode1/Continuity/files/9626212/2022-09-22-3.log)

**Comment by futag** [comment]
Logs: [2022-09-22-5.log](https://github.com/PepperCode1/Continuity/files/9626214/2022-09-22-5.log)

**Comment by PepperCode1** [comment]
Duplicate of #107; install Indium.
