### ISSUE TITLE
Resource reload loop with Supplementaries

### ISSUE THREAD

**Issue by NyakoFox** [PepperCode1/Continuity#171]
Fabric 0.14.9, Supplementaries 2.2.3, Continuity 2.0.1
When these mods are added together, it causes a resource reload loop on startup. (The progress bar fills up, and then resets and starts again)

Original issue here: https://github.com/MehVahdJukaar/Supplementaries/issues/386

**Comment by PepperCode1** [comment]
A log is needed to debug this.

**Comment by NyakoFox** [comment]
tried to grab a log today and it no longer happens, somehow, despite being consistent yesterday
