### ISSUE TITLE
Using vanilla tweaks causes unloading resourcepacks and/or crashing

### ISSUE THREAD

**Issue by edgvrl** [PepperCode1/Continuity#173]
I have been using continuity for a while now but i still cant figure out whats wrong with the texture pack
Log:
[latest.log](https://github.com/PepperCode1/Continuity/files/9693240/latest.log)

Texture pack:
[VanillaTweaks_r223740.zip](https://github.com/PepperCode1/Continuity/files/9693247/VanillaTweaks_r223740.zip)

Aparently it has smth to do with with emmissive texture rendering, but even after turning it of it wont work

**Comment by Julienraptor01** [comment]
Don't use the connected packs since they are made in a vanilla broken way
And remove packs that use vanilla shaders since they break with sodium and lead to problems

**Comment by PepperCode1** [comment]
Turning off the emissive textures option does not prevent them from being loaded.

**Comment by edgvrl** [comment]
> remove packs that use vanilla shaders

i never ever used vanilla shaders and my vanilla tweaks pack doesnt use vanilla shaders so that probably isnt the problem


> Turning off the emissive textures option does not prevent them from being loaded.

ye makes sense on a programming view to load everything and just disable rendering of emissive textures

Were you two able to replicate the issue?

**Comment by Julienraptor01** [comment]
> > remove packs that use vanilla shaders
> 
> i never ever used vanilla shaders and my vanilla tweaks pack doesnt use vanilla shaders so that probably isnt the problem

You DO use vanilla shaders in your vanilla tweaks pack
There is by example the fog fix pack which use it, but also other ones
Just look in `VanillaTweaks_r223740.zip/assets/minecraft/shaders`

**Comment by edgvrl** [comment]
Oh well then sorry i will try to remove them and close the issue when it has been resolved

**Comment by edgvrl** [comment]
Okay so unpacked the zip and removed the whole shader folder and it didnt change a thing :/

still the same error unfortunaly

**Comment by Julienraptor01** [comment]
> Okay so unpacked the zip and removed the whole shader folder and it didnt change a thing :/
> 
> still the same error unfortunaly

Remove the emmissive.properties in the optifine folder to remove emmissives

**Comment by edgvrl** [comment]
that solved the issues

**Comment by PepperCode1** [comment]
I just double checked the log and tested this myself and I realized that you don't have Indium. Install it and everything will work. Duplicate of #107.
