### ISSUE TITLE
Connected textures don't work

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#176]
I don't know why but none of the connected textures works except for glass, I've got them enabled and have no texture packs on.
![2022-10-11_12 17 40](https://user-images.githubusercontent.com/115548212/195076443-ea09eb20-c2d8-4967-94f3-89ca9b57b2e1.png)
![2022-10-11_12 18 09](https://user-images.githubusercontent.com/115548212/195076539-6a1efbed-cf70-429c-b1d7-3afc6ba05312.png)

**Comment by PepperCode1** [comment]
The default pack only contains connected textures for glass, bookshelves, and sandstone. Grass and sand overlays like shown in the mod icon are not part of the mod or the default resource pack. Other packs like Xali's Enhanced Vanilla or BetterVanillaBuilding + BVB Overlays can get you those.
