### ISSUE TITLE
Wool overlays not working

### ISSUE THREAD

**Issue by Lalit64** [PepperCode1/Continuity#178]
I've downloaded a wool overlay resource pack. Most of these require optifine for connected textures, but is there a way to make them work with continuity.

Expected: 
<img width="1234" alt="Screenshot 2022-10-15 at 19 24 56" src="https://user-images.githubusercontent.com/79628080/195990277-ebd42aa9-e18b-4847-a3da-af990e3a7182.png">

What I get: 
<img width="1234" alt="Screenshot 2022-10-15 at 19 27 16" src="https://user-images.githubusercontent.com/79628080/195990379-0384b9f0-8426-4ec0-bbc9-7c10acae95ac.png">

**Comment by PepperCode1** [comment]
I need a link to the pack to debug this.

**Comment by Lalit64** [comment]
https://www.mediafire.com/file/eo09gbl9ihtjbjx/%2521_%25C2%25A74So%25C2%25A76ft_%25C2%25A72Wo%25C2%25A79ol_%25C2%25A7dOver%25C2%25A75lay.zip/file

**Comment by PepperCode1** [comment]
The linked pack uses the `mcpatcher` directory instead of the `optifine` directory, which is not supported. Are you sure you are using Optifine and exactly the same pack? Optifine does not support the `mcpatcher` directory either.

**Comment by Lalit64** [comment]
Yes I am using OptiFine. Also is it possible to rename the folder to optifine

**Comment by PepperCode1** [comment]
Which Minecraft version are you on? Old versions like Optifine 1.8.9 might support the `mcpatcher` directory. If you want to change the directory to make it work with Continuity and modern versions of Optifine, you can unzip the pack, rename the `mcpatcher` directory (under `/assets/minecraft`) to `optifine`, and re-zip the pack.
