### ISSUE TITLE
Game + Launcher crashing when gravel falls

### ISSUE THREAD

**Issue by DEMEMZEA** [PepperCode1/Continuity#180]
[2022-10-18-6.log.gz](https://github.com/PepperCode1/Continuity/files/9815716/2022-10-18-6.log.gz)
[crash-2022-10-18_20.23.34-client.txt](https://github.com/PepperCode1/Continuity/files/9815717/crash-2022-10-18_20.23.34-client.txt)

**Comment by PepperCode1** [comment]
Duplicate of #107; install Indium.

**Comment by DEMEMZEA** [comment]
Sorry, i thought I had already done that.
