### ISSUE TITLE
No Connected Texture

### ISSUE THREAD

**Issue by uddipmayur** [PepperCode1/Continuity#181]
It is not working in any connected texture

**Comment by PepperCode1** [comment]
Minecraft version? Mods used? Mod versions? Resource packs enabled? You cannot expect a resolution to your issue if you do not provide any information.

**Comment by drewsuhferr** [comment]
Hello!
Not sure if this was brought up before but I'm finding a continuity issue pertaining glass panes. They look to be working flush and as expected when placed horizontally together however they rendering their frame borders on the tops and bottom (screenshot attached). I'm currently using the Better Minecraft 1.19.2 modpack on curseforge and am unsure if their could be conflicting mods at the moment (first time on modded minecraft). Please let me know if there is more information needed! 
![2022-10-24_22 58 59](https://user-images.githubusercontent.com/116617543/197679526-5f5aede6-fbbe-404d-b603-d24c6f53f8dc.png)

**Comment by PepperCode1** [comment]
You need to enable the second built-in resource pack (glass_pane_culling_fix).

**Comment by drewsuhferr** [comment]
ahh an already built fix! awesome thank you!

**Comment by PepperCode1** [comment]
I am closing this because no additional information was provided.
