### ISSUE TITLE
connected textures only working in single player? 

### ISSUE THREAD

**Issue by netcore10** [PepperCode1/Continuity#187]
whenever i join server side connected textures don't display, does it need to be on the server? -

**Comment by PepperCode1** [comment]
What are "server side connected textures"?

**Comment by Julienraptor01** [comment]
> whenever i join server side connected textures don't display, does it need to be on the server? -
> 

Continuity is a client-side mod (no need to put it on server), maybe give logs, screenshots, etc

**Comment by netcore10** [comment]
Well it just makes me more confused, since the connected textures don't show on a server, only single player worlds.

**Comment by PepperCode1** [comment]
If the server forces resource packs it might disable ones that provide connected textures. Send a screenshot of your resource packs menu while connected to the server.

**Comment by netcore10** [comment]
![image](https://user-images.githubusercontent.com/181536/202329111-18899f1c-a696-4076-9213-4ba628bf5d4d.png)
![image](https://user-images.githubusercontent.com/181536/202329164-51af11a7-5ccd-4531-84df-f342d9cbb971.png)

and sp
![image](https://user-images.githubusercontent.com/181536/202329270-22177648-455f-45de-8a8d-387b8a4cb348.png)

**Comment by netcore10** [comment]
here's a client log too https://paste.atlauncher.com/view/d7f083c7-d638-4da4-a94c-9f5dfc1b1271

**Comment by PepperCode1** [comment]
Are you able to disable "World Specific Resources"?

**Comment by netcore10** [comment]
No, it's server sided, but the only thing it has is item models.

**Comment by PepperCode1** [comment]
That can't be right if the connected textures stop working. Is there a way I can get the pack?

**Comment by netcore10** [comment]
Here's the exported pack. (we use at launcher)
https://www.dropbox.com/s/0ggqgtrtn6zxgcd/1.19.2%20-%20HaywenSMP%20V9.1%20v9.1.mrpack?dl=1

**Comment by netcore10** [comment]
oops! Wrong one

**Comment by netcore10** [comment]
i think you meant the resource pack, here it is.
[HaywenSMPResources-16-11-2022.zip](https://github.com/PepperCode1/Continuity/files/10033958/HaywenSMPResources-16-11-2022.zip)

**Comment by ChristianLW** [comment]
The pack contains a texture for the glass block. I'm not sure if that causes the issue.

**Comment by netcore10** [comment]
> The pack contains a texture for the glass block. I'm not sure if that causes the issue.

I think i tried it with and without and saw no changes, but worth another shot

**Comment by PepperCode1** [comment]
Sorry that I forgot to follow up on this in a timely manner. The pack does have a glass texture, and that is what is causing the default glass connected textures to be disabled. If the glass texture is the same as the vanilla texture, remove it, otherwise you can add your own CTM glass files to the pack.

**Comment by netcore10** [comment]
wait, even if the generated pack is being used?
