### ISSUE TITLE
Not sure if that's a bug, but no emissive textures on custom models

### ISSUE THREAD

**Issue by ginqus** [PepperCode1/Continuity#188]
So, i have a texture pack, and what it does, is change models and textures when carved pumpkin is renamed to a specific word, then you can put it on your head, and there it is, a lil silly hat.
One small problem, i have a miner helmet in my texture pack, and it the lamp thing should glow, however it's not, but it does in optifine
OptiFine:
![2022-11-17_20 58 22](https://user-images.githubusercontent.com/99472757/202528425-65702f49-4753-4dd5-a50f-19d4b48b0da5.png)
Continiuty + SITResewn + Fabric API + Indium + Mod Menu + Sodium
![2022-11-17_21 23 07](https://user-images.githubusercontent.com/99472757/202528733-0e04b60a-0411-4957-bb6a-567e252eb916.png)

Can i do anything about it or is it just skill issue

**Comment by TheNukeLore** [comment]
Might need entity texture features

**Comment by ginqus** [comment]
> Might need entity texture features

Yeah i tried, it doesn't help

**Comment by Julienraptor01** [comment]
What pack is it ? Did you enabled broken paths in all mods that have the options ?
Actually it's maybe this bug
https://github.com/SHsuperCM/CITResewn/issues/149

**Comment by ginqus** [comment]
> What pack is it ? Did you enabled broken paths in all mods that have the options ? Actually it's maybe this bug [SHsuperCM/CITResewn#149](https://github.com/SHsuperCM/CITResewn/issues/149)

Yeah, i have read that before
So is there any other mod that allows cit sprite path suffixes? Or maybe i could do this another way? It's my resource pack btw, but i can send .zip if you need it

**Comment by Julienraptor01** [comment]
> > What pack is it ? Did you enabled broken paths in all mods that have the options ? Actually it's maybe this bug [SHsuperCM/CITResewn#149](https://github.com/SHsuperCM/CITResewn/issues/149)
> 
> Yeah, i have read that before
> So is there any other mod that allows cit sprite path suffixes? Or maybe i could do this another way? It's my resource pack btw, but i can send .zip if you need it

Sadly you can't do anything except wait for CIT Resewn rewrite which will hopefully support sprite path suffixes

**Comment by ginqus** [comment]
> > > What pack is it ? Did you enabled broken paths in all mods that have the options ? Actually it's maybe this bug [SHsuperCM/CITResewn#149](https://github.com/SHsuperCM/CITResewn/issues/149)
> > 
> > 
> > Yeah, i have read that before
> > So is there any other mod that allows cit sprite path suffixes? Or maybe i could do this another way? It's my resource pack btw, but i can send .zip if you need it
> 
> Sadly you can't do anything except wait for CIT Resewn rewrite which will hopefully support sprite path suffixes

alright, thanks
