### ISSUE TITLE
Extreme Lag Spikes with Faithless

### ISSUE THREAD

**Issue by OoLunar** [PepperCode1/Continuity#190]
# Description
When using Faithless with Continuity, Sodium, and Indium, random lag spikes can occur. These lag spikes are made incredibly noticeable when running the [Faithless texture pack](https://www.curseforge.com/minecraft/texture-packs/faithless). On the [Faithless Discord server](https://discord.com/invite/wcmxjtV), users have narrowed down the issue to particles and pistons, as the reproduction example provides below. If there's any other information you need me to provide, I'll do my best to cooperate. 

# Minimal Repro
[mods.zip](https://github.com/PepperCode1/Continuity/files/10181855/mods.zip)
[New_World.zip](https://github.com/PepperCode1/Continuity/files/10181856/New_World.zip)
https://cdn.discordapp.com/attachments/996562194227535912/1049523540614983720/temp.mp4

**Comment by PepperCode1** [comment]
I would like to see the contents of the Continuity configuration file (not a screenshot of the configuration screen) and a screenshot of the video settings screen that has chunk building-related options.

**Comment by PepperCode1** [comment]
There has not been a response in half a year. Minecraft, the mods you are using, and Faithless have all received updates. There is no clear cause or fix for any performance issues you may be experiencing, however, so there is not much I can do regardless.
