### ISSUE TITLE
Stairs sides don't connect correctly?

### ISSUE THREAD

**Issue by DeadbushCarrot** [PepperCode1/Continuity#196]
So I have a texture pack installed that added ctm to andesite diorite and granite and when looked at the side of the stairs they had a line half way through where Optifine doesn't do this?
![2022-12-23_01 14 11](https://user-images.githubusercontent.com/109874700/209300917-921325f8-b49f-4ec1-8bef-1c3f37717583.png)
![2022-12-23_01 11 33](https://user-images.githubusercontent.com/109874700/209300929-d70ebff2-c996-40ea-9fbc-7b968cf56cc4.png)

**Comment by PepperCode1** [comment]
Which pack is it, exactly?

**Comment by TheNukeLore** [comment]
I will say I’ve had this issue as well but forgot what pack it was

**Comment by DeadbushCarrot** [comment]
The pack is Classic Improvements add-on 2 Am the owner of it so if I did anything wrong let me see heres the link https://www.planetminecraft.com/texture-pack/classic-improvements-add-on-2-stone-ctm/

**Comment by PepperCode1** [comment]
The case where a quad processed by `ctm_compact` was valid but did not require splitting was not handled correctly because it did not replace the sprite. This will be fixed for 2.0.2.
