### ISSUE TITLE
Performance are really bad

### ISSUE THREAD

**Issue by Fefedu973** [PepperCode1/Continuity#201]
With iris Patrick x256 ressource pack 16chunks of render and deus ressource pack I get around 40-50fps but when I put continuity in my mod folder my fps goes down to 5

**Comment by PepperCode1** [comment]
Did you test the resource pack on Optifine (with connected and emissive textures enabled) to see how performance is there?

**Comment by Fefedu973** [comment]
> Did you test the resource pack on Optifine (with connected and emissive textures enabled) to see how performance is there?

In optioned the performance are bad but if we turn on smart animations I got 30fps not 10. believe me i tested

**Comment by MrSlimeOfSlime** [comment]
Partix uses a LOT of CTM, enabling it via continuity or optifine loads thousands of very large (for minecraft) textures. This is likely expected behavior.

**Comment by PepperCode1** [comment]
If you want the best performance, make sure you are using Sodium+Indium and other optimization mods. Plus, every computer is different and Optifine may provide better performance for older systems. Continuity's connected textures code is as efficient as it can possibly be so there is nothing I can do.
