### ISSUE TITLE
1.19.3 release

### ISSUE THREAD

**Issue by jucogjucogi** [PepperCode1/Continuity#206]
when continuity will update to newer vers?
usually it's about month after prev. release, but now it's 5 months. i know that author need to rest and everything, but when it will update?

**Comment by Jayson729** [comment]
There's an alpha in the discord server that works with 1.19.3. The link to the discord server is on the curseforge/modrinth page.

**Comment by forkiesassds** [comment]
> There's an alpha in the discord server that works with 1.19.3. The link to the discord server is on the curseforge/modrinth page.

I'm not joining a Discord server. Is there any other way to download it (for example via GitHub Actions)?

**Comment by Julienraptor01** [comment]
> > There's an alpha in the discord server that works with 1.19.3. The link to the discord server is on the curseforge/modrinth page.
> 
> I'm not joining a Discord server. Is there any other way to download it (for example via GitHub Actions)?

no, alpha builds are only given in discord since the code isn't even pushed to GH yet

**Comment by forkiesassds** [comment]
> > > There's an alpha in the discord server that works with 1.19.3. The link to the discord server is on the curseforge/modrinth page.
> > 
> > 
> > I'm not joining a Discord server. Is there any other way to download it (for example via GitHub Actions)?
> 
> no, alpha builds are only given in discord since the code isn't even pushed to GH yet

Why aren't they pushed to a Git branch anyways???? This is the stupidest reason I've ever heard.

**Comment by Julienraptor01** [comment]
> > > > There's an alpha in the discord server that works with 1.19.3. The link to the discord server is on the curseforge/modrinth page.
> > > 
> > > 
> > > I'm not joining a Discord server. Is there any other way to download it (for example via GitHub Actions)?
> > 
> > 
> > no, alpha builds are only given in discord since the code isn't even pushed to GH yet
> 
> Why aren't they pushed to a Git branch anyways???? This is the stupidest reason I've ever heard.

idk yes there could be a branch but i guess it's only on his local git, he doesn't push it to GH
idk why his workflow is like this but well i just can't answer you, @PepperCode1 is the dev

**Comment by jucogjucogi** [comment]
thank you so much
