### ISSUE TITLE
CTM not working with Quilted Fabric API on Continuity 1.19.3 3.0.0 beta 2

### ISSUE THREAD

**Issue by S0urceDA** [PepperCode1/Continuity#214]
![2023-02-07_18 46 43](https://user-images.githubusercontent.com/61162198/217400387-9b4ac372-31bd-4220-868d-dfa99ea7ac94.png)
I only used continuity, lazydfu and quilted fabric api to get this result. 
![image](https://user-images.githubusercontent.com/61162198/217400640-1029f67a-708c-4dec-a71b-6b6b8f7bf30b.png)
Beta 1 works fine, and beta 2 works fine with the normal fabric API. The quilt version breaks it however.
And yes I did not forget to enable the resourcepacks

**Comment by YukiAyase** [comment]
Also important to note, **QFAPI seems to only break the default pack**
Using any other resource pack (including Prog art) works just fine

**Comment by mihkl** [comment]
Where could I download the beta 1.19.3 continuity from?

**Comment by The-HAX0R-31337** [comment]
I would also like to know where to obtain the beta.

**Comment by YukiAyase** [comment]
> Where could I download the beta 1.19.3 continuity from?

> I would also like to know where to obtain the beta.

You can grab betas at the [Discord](https://discord.com/invite/7rnTYXu)
_The Discord invite link is also literally at the README section aka the front page_

**Comment by PepperCode1** [comment]
I have been talking with the Quilt developers and this will be fixed by QSL/Quilted Fabric API soon. This issue will be closed once the updates containing the fix are publicly released.

**Comment by PepperCode1** [comment]
This will be fixed by QuiltMC/quilt-standard-libraries#270.

**Comment by PepperCode1** [comment]
QSL `4.0.0-beta.12+1.19.3` was released some time ago which fixed this issue.
