### ISSUE TITLE
continuity crash

### ISSUE THREAD

**Issue by L4ck3y** [PepperCode1/Continuity#216]
Although I have the latest versions of sodium and indium, my game crashes when I install continuity, what should I do?

**Comment by PepperCode1** [comment]
You should send a log.

**Comment by L4ck3y** [comment]
These are all the mods i have installed
![Ekran görüntüsü 2023-02-09 115929](https://user-images.githubusercontent.com/74822126/217765108-e1cf9e6c-8643-4ba0-8d3a-e53031d958d8.png)
![Ekran görüntüsü 2023-02-09 120102](https://user-images.githubusercontent.com/74822126/217765379-97ebe558-01b3-48d4-a17a-72c8d5d8c534.png)
[crash-2023-02-09_12.00.43-client.txt](https://github.com/PepperCode1/Continuity/files/10695174/crash-2023-02-09_12.00.43-client.txt)

**Comment by PepperCode1** [comment]
Released versions of Continuity will not work with 1.19.3. 1.19.3 beta releases are available on my Discord server.
