### ISSUE TITLE
Client crash due to Continuity texture connection and other issues

### ISSUE THREAD

**Issue by ccyounga** [PepperCode1/Continuity#224]
Hello, I recently sorted out an issue on the github of the author of the Indium mod. I thought it was the problem because the crashlog pointed to it.
After some testing, it turned out that the Continuity mod on 1.18.2 is causing wild problems for the optifine texture fusion system of the popular Conquest resource pack.
It is his function of disabling textures that causes the textures of the earth and other connected blocks to disappear in whole chunks, and also provokes a client crash in various situations.

Details and logs were presented on the github of the author of Indium, so it's easier to provide information that has already been chewed: https://github.com/comp500/Indium/issues/178

**Comment by PepperCode1** [comment]
The crash you encountered and other issues with Conquest have all been fixed in 2.0.2, but this version has not been released yet.

**Comment by ccyounga** [comment]
Well, let's try to wait, I hope it will be for 1.18.2? Version 1.19.3 is not yet ready according to modifications that replace the functions of the optifine.

**Comment by PepperCode1** [comment]
Yes, 2.0.2 will be released for 1.18.2 and 1.19.2 relatively soon.

**Comment by ccyounga** [comment]
When can we expect an update? Quite a lot of time has passed.

**Comment by PepperCode1** [comment]
2.0.2 has just been released for 1.18.2 and 1.19-1.19.2. 1.19.3 pre-releases already contain the necessary fixes.
