### ISSUE TITLE
Glass not connecting when using Mizuno's 16 Craft resource pack

### ISSUE THREAD

**Issue by mingh2e** [PepperCode1/Continuity#225]
I'm using a translator, so the sentences may not be smooth.

Mizuno's 16 Craft resource packs have textures such as terracotta and glass connected.

However, when using the Continuity mode, the terracotta is connected, but the glass and glass plate textures are not.

I don't know why terracotta's textures are connected but glass's are not.
I confirmed that the glass of the other resource pack (faithful 32x) connects well.

I would appreciate it if you could leave an answer on this issue.
I hope my words are conveyed well.
thank you for reading

**Comment by PepperCode1** [comment]
Mizuno's pack does not have connected glass. You can confirm this by running it with Optifine or looking at the official screenshots of the pack which show glass that is not connected.

**Comment by mingh2e** [comment]
![2023-03-10_12 08 27](https://user-images.githubusercontent.com/96931727/224214509-d843e587-6488-431d-a2ed-eda95f2dfd06.png)
Screenshot of applying forge optifine


----------------------------------------------------

![2023-03-10_12 16 55](https://user-images.githubusercontent.com/96931727/224214657-a1a32b53-161c-495d-9a30-2e822f05d6fd.png)

Screenshot of applying fabric iris

If you look at the screenshot, the glass of forge optifine is connected to each other, but
Confirmed that the glass of the fabric iris is not connected to each other.

**Comment by mingh2e** [comment]
-----

I found the cause of the problem.

After removing the Minekea mode, the glass connects normally.
