### ISSUE TITLE
Nbt tags

### ISSUE THREAD

**Issue by PikaTntyt** [PepperCode1/Continuity#229]
So, I was trying to make a texture pack where it connects lit redstone lamps and  unlit redstone lamps separately. But here's the catch, the lit/unlit thing is an Nbt Tag (lit: True/False). The question is "How on earth can I specify nbt data in the texture pack file???". I tried with the name of the textures (redstone_lamp/redstone_lamp_on) but this just doesn't work for any of the textures... Please help...

**Comment by PikaTntyt** [comment]
If that's even possible.

**Comment by PepperCode1** [comment]
This is not the place to get help with developing resource packs. Use my Discord server or the Optifine Discord server for that.
