### ISSUE TITLE
1.19.4 not working

### ISSUE THREAD

**Issue by Wiredcheetah828** [PepperCode1/Continuity#230]
won't work at fresh install

**Comment by YukiAyase** [comment]
Have you enabled Continuity's resource packs?
If not, please enable them in the resource pack menu
(continuity/default, continuity/glass_pane_culling_fix are the names for them)

If you have **Sodium** installed, you will need to install **Indium** which can be found here
https://modrinth.com/mod/indium/version/1.0.15+mc1.19.4

**Comment by Wiredcheetah828** [comment]
thanks, forget about that sorry
