### ISSUE TITLE
Connected textures not working in 1.19.4

### ISSUE THREAD

**Issue by User3624** [PepperCode1/Continuity#233]
The title explains it all.
![image](https://user-images.githubusercontent.com/108425476/228936452-bf74a141-de7e-4eaf-bb49-d3b441c59eda.png)
![image](https://user-images.githubusercontent.com/108425476/228937379-97d8a3de-e717-43fb-993d-cb0e5322b684.png)

**Comment by CatKing754** [comment]
Try enabling the resource packs.

**Comment by User3624** [comment]
Not sure what resource packs are there, but I'll try

**Comment by User3624** [comment]
Seems to be workimg, wasn't an issue!
