### ISSUE TITLE
Blocks made to look translucent by block.properties do not look translucent when moved by pistons

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#237]
Example resource pack, which makes normal glass as well as anvils look like white stained glass: 
[continuity-block-properties-render-test.zip](https://github.com/PepperCode1/Continuity/files/11183157/continuity-block-properties-render-test.zip)

Comparison:
![2023-04-06_18 15 54](https://user-images.githubusercontent.com/52297970/230719922-9b4a5d49-aa89-4fa5-988d-e3e62e0299d1.png)
![2023-04-06_18 15 56](https://user-images.githubusercontent.com/52297970/230719924-e2dfd58f-4933-4c95-996b-cd88f0ff5cd0.png)

**Comment by muzikbike** [comment]
Some older screenshots:
![2023-04-05_13 36 50](https://user-images.githubusercontent.com/52297970/230719958-bfb8c12c-8b42-48aa-8905-91e9bcc490f7.png)
![2023-04-05_13 36 51](https://user-images.githubusercontent.com/52297970/230719961-6b62b44f-5f72-48c0-a2e9-cddef198934f.png)
![2023-04-05_13 36 54](https://user-images.githubusercontent.com/52297970/230719966-4467ac30-6ec2-4425-92bc-caa00c41f07a.png)

**Comment by PepperCode1** [comment]
This behavior is consistent with Optifine as evidenced by my testing, so technically this is not a bug. However, this behavior makes no sense, and it is extremely easy to fix, so the next Continuity update will resolve this.
