### ISSUE TITLE
Blocks made to look translucent by block.properties do not look translucent in falling block form

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#238]
The resource pack attached to #237 can be used to test this with anvils.
![2023-04-06_18 13 56](https://user-images.githubusercontent.com/52297970/230720008-3530cb2d-f57a-40de-8af5-b0b070f2b110.png)
![2023-04-06_18 14 09](https://user-images.githubusercontent.com/52297970/230720009-b886db7d-ad75-4fac-8afe-595cfaf2f69b.png)
![2023-04-06_18 14 09_2](https://user-images.githubusercontent.com/52297970/230720011-0dc64b66-16ec-4ee2-a03a-5a7490e69b3f.png)

**Comment by muzikbike** [comment]
I should probably ask while I'm here: what exactly is Continuity's scope with respect to resource pack features? Are any features from MCPatcher or OptiFine fair game for reporting if they don't exist here yet, provided that they can be done without touching the renderer or other aspects of the game code that can't be messed with under current restrictions and such? I remember MCPatcher supporting some custom particle color settings such as biome-specific splash particle colors, custom sky colors and sky boxes, among other things, but haven't checked if either OptiFine or Continuity support such features, and there's probably other stuff as well. How about other resource pack features added by other mods?

The initial scope of the mod seems to be for connected texture support and things immediately adjacent to it, as opposed to being a modern/Fabric reimplementation of everything MCPatcher/OptiFine can do. But with things like block.properties, I'm not sure exactly where the line is drawn. It does seem reasonable to assume that this could be a feature included due to its association with connected textures for stuff like translucent glass.

**Comment by PepperCode1** [comment]
Continuity is mainly for connected textures, but it includes emissives (for blocks and item models only; the rest are handled by Entity Texture Features) and `block.properties` as well. Optifine/MCPatcher color features are Colormatic's territory and even if I choose to develop those features they will not be included in Continuity.

You are correct that Continuity is not a Fabric version of MCPatcher/Optifine. That was not its goal nor will it ever will be. I do not have time to develop all features and I do not want to develop all features, plus I think that so many different features should not all be part of one mod.

**Comment by PepperCode1** [comment]
This is the same issue as #237; I will close this issue and the problem can be tracked there.
