### ISSUE TITLE
Built-in resource packs display as outdated in 1.19.4

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#239]
Incredibly minor, but I thought I'd point it out anyway. I'm not sure if this is even a valid issue given that the jar I'm using is for 1.19.3 (although it seems to function completely fine otherwise).
![2023-04-08_13 14 12](https://user-images.githubusercontent.com/52297970/230720561-4a82ed03-efec-425d-9b02-b6d81cab2928.png)

**Comment by muzikbike** [comment]
They'll need to be incremented by one more pack version in 1.20 as well.

**Comment by ghost** [comment]
The jar file that says on the website that it's for 1.19.4 is actually for 1.19.3 but works fine in 1.19.4, so yes it is minor but, once they update it, they need to change the pack version.

**Comment by muzikbike** [comment]
As the latest version is no longer 1.19.4, is this still valid?

**Comment by PepperCode1** [comment]
This was fixed in beta 3 but I forgot to close this.
