### ISSUE TITLE
Overlay CTM seems to be broken

### ISSUE THREAD

**Issue by thedogcraftyt** [PepperCode1/Continuity#24]
When using overlay CTM, the texture appears to be missing in-game. With OptiFine, everything just works fine

**Comment by notLily72** [comment]
Can you please provide us a screenshot of the issue in optifine and continuity, and the log for continuity with the issue present.

**Comment by PepperCode1** [comment]
I am closing this issue because no futher context was provided so doing any sort of debugging is impossible. If information is provided, the issue can be reopened.
