### ISSUE TITLE
Make vertical culling fix resource pack affect iron bars as well?

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#240]
Iron bars don't use connected textures, but they're affected by the same annoying issue where culling doesn't work vertically. It's the same problem (https://bugs.mojang.com/browse/MC-50349), and can be "fixed" (disregarding the side effects detailed in #74) in the same way.
![2023-04-08_13 13 23](https://user-images.githubusercontent.com/52297970/230720875-b2ded5bd-c7d0-47d3-af87-d6487e10d2ec.png)
![2023-04-08_13 13 52](https://user-images.githubusercontent.com/52297970/230720876-b8f522ec-be30-443c-9cf9-a8b2bb3229d7.png)

For iron bars specifically, this broke in 1.8 - it was fine in 1.7 and earlier. Here's a comparison:
![2023-04-08_13 20 55](https://user-images.githubusercontent.com/52297970/230720911-2503416f-f90c-4918-ae13-0a303caf7ab7.png)
![2023-04-08_13 21 46](https://user-images.githubusercontent.com/52297970/230720912-ec705926-d400-44b4-8253-8ccc0aadbac3.png)

**Comment by PepperCode1** [comment]
Custom culling behavior is not something Continuity deals with. There may be other mods that allow this.
