### ISSUE TITLE
Configuration for culling certain faces?

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#241]
Yet another Hollow Glass Saga observation: it's possible for some planes to start z-fighting with the custom model I'm using. Some way to override what blocks can cull against other blocks using a resource pack might be useful to get rid of this effect. I'm not sure if this would be at all possible to implement here, though.
![2023-04-10_12 49 54](https://user-images.githubusercontent.com/52297970/230898548-cd3cc21e-7d47-4a10-88c0-26cc8ae616e0.png)

More significantly, there's a vanilla issue with beacons. The vanilla beacon model doesn't specify cullface for anything ([MC-239142](https://bugs.mojang.com/browse/MC-239142)). However, even if we do turn it on for the outer planes, for example, beacons still won't cull against other beacons. They also won't cull against glass blocks, nor will glass blocks cull against beacons. This results in many inner planes which are already a pain in vanilla, and become even more of a menace if you're trying to do CTM to make beacons connect with each other in a good-looking way. If there exists some way for a resource pack to say "beacons cull against beacons, beacons cull against glass, and glass culls against beacons", that would allow for this issue to be resolved. I don't know if that's doable.
![2023-04-10_13 02 05](https://user-images.githubusercontent.com/52297970/230899079-ec7237b7-cb2e-42c9-8f7a-6ffcde397704.png)
![2023-04-10_13 02 33](https://user-images.githubusercontent.com/52297970/230899084-a54a6a8f-3f31-4fc4-bdfa-b66ac502ce94.png)
![2023-04-10_13 02 45](https://user-images.githubusercontent.com/52297970/230899086-b5ec966f-14b7-4263-92e3-4e5d965df8a6.png)

**Comment by PepperCode1** [comment]
Custom culling behavior is not something Continuity deals with. There may be other mods that allow this.

**Comment by Julienraptor01** [comment]
For the beacon culling thing see https://modrinth.com/mod/morecullingextra
