### ISSUE TITLE
1.19.2 1.19.4都有这情况呀

### ISSUE THREAD

**Issue by wumu-wsl** [PepperCode1/Continuity#243]
求大佬看一下![屏幕截图 2023-04-11 170502](https://user-images.githubusercontent.com/129469634/231113728-a84e0fc2-5376-4963-8789-4e08eac0f4eb.png)

**Comment by PepperCode1** [comment]
The pack the randomizes models and textures clearly does not include emissive textures, and textures that don't exist can't show up.
