### ISSUE TITLE
Configuration for how blocks interact with water rendering?

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#245]
In vanilla, certain blocks will render differently around water, and water will render differently around them: the dowwards flowing water texture will not be rendered from within the water, and will be replaced with a single, solid color texture from the other side.

In vanilla, glass interacts with water in this way, but beacons do not. In the following screenshots, I've assigned the same model to glass and beacons. The blocks that don't have the blue water overlay are glass, and the ones that do are beacons.
![2023-04-14_16 47 51](https://user-images.githubusercontent.com/52297970/232094544-f6e94324-e3fe-48ff-b818-033ab0a0bc7c.png)

I'm not sure if this would fit in the scope of the mod or would be possible to implement in the first place, but it does get in the way of my goal to have glass and beacons connect to each other seamlessly (like #242 and the second issue I highlighted in #241), so this seemed like the most fitting place to report it.

I do know that Sodium does appear to touch water rendering to some extent resulting in deviations from vanilla (https://github.com/CaffeineMC/sodium-fabric/issues/991, which is unrelated to https://github.com/CaffeineMC/sodium-fabric/issues/38 but that issue can be seen here as well): 
![2023-04-14_16 53 33](https://user-images.githubusercontent.com/52297970/232095138-09c74fe2-9b73-4ece-9d01-d2de429b690d.png)

**Comment by PepperCode1** [comment]
This may be possible but I am not willing to add it to Continuity.
