### ISSUE TITLE
Conflict between connected grass and blocks overlays

### ISSUE THREAD

**Issue by Felina-Lain** [PepperCode1/Continuity#248]
Minecraft version 1.19.4
Continuity version: 3.0.0-beta.2+1.19.3
Indium: 1.0.15+mc1.19.4
Packs used: xali's Enhanced Vanilla + Continuity built-in better grass

Issue:
The overlay of some of the blocks don't work at all when using the built-in better grass.
Expected result (as seen in Optifine):
![image](https://user-images.githubusercontent.com/5339303/235667600-c917c2de-a577-4540-9b79-791afaff8ef3.png)
Has both the better grass with the sides, and the overlay on the dirt path

Current result: (with Sodium, Continuity, Indium)
![image](https://user-images.githubusercontent.com/5339303/235664037-4b637368-6205-4e47-ab23-ae9c064e0a85.png)
Has no overlay if better grass is activated
![image](https://user-images.githubusercontent.com/5339303/235666308-e6b9294c-8546-49fe-9f83-2ab4f6adf2ad.png)
Has overlay if better grass isn't activated

I tried using the mods with both possible orders (BG above Xali, and Xali above BG), both result in the same bug, although putting Xali above has some of the corners overlay appear, but seemingly at random.
I figured the effect was with Continuity since having the shaders on or off changes nothing to the issue.

have a nice day everyone.

**Comment by PepperCode1** [comment]
Continuity does not have built-in better grass.

**Comment by Felina-Lain** [comment]
> Continuity does not have built-in better grass.

Uh, I thought the pack came from here, because I don't recall installing it, and Continuity had its own included packs, but my bad then, I'll look for the source.
