### ISSUE TITLE
Unable to disable natural block transition effect?

### ISSUE THREAD

**Issue by totrider** [PepperCode1/Continuity#251]
It seems like you cannot get rid of the block transition effect on natural blocks?

It seems to me like it is part of the mod itself, and not dependent on the resource pack provided?

And, the visual effect is tied to the "connected textures" client setting, so I cannot have connected textures for bookshelves and glass, without the transition effect?
a
Would it be possible to separate the transition effect into its own configuration/resourcepack?

**Comment by PepperCode1** [comment]
Continuity does not have any behavior that cannot be disabled. Please send a screenshot of what you are referring to.

**Comment by totrider** [comment]
I found out what was causing it. Was unaware that "xali's Enhanced Vanilla" resource pack included the textures needed for terrain to transition between each other.

Essentially, say a user only wants to have connected textures for bookshelves and glass, but not the terrain. If a resource pack includes both, then you wont be able to cherry pick which features you want to enable/disable. The "Connected Textures On/Off" affects both the terrain, and other blocks. My assumption is that it is not possible to separate the two features with a separate on/off setting for both, but it would be nice. I know the work-around would be to just use resource packs that don't include the terrain textures I guess, but for modpack creation, it would be better if a user can choose what features they want more specifically.

Connected Textures On (using "xali's Enhanced Vanilla")
![2023-05-12_16 21 25](https://github.com/PepperCode1/Continuity/assets/1184655/f2b284f9-2af0-4775-ad2a-127bfae51e6b)

Connected Textures Off (using "xali's Enhanced Vanilla")
![2023-05-12_15 59 51](https://github.com/PepperCode1/Continuity/assets/1184655/a1108727-d991-4356-a724-fc45326236b1)

**Comment by PepperCode1** [comment]
It is not possible to automatically detect what is a transition and what is not, so a setting cannot be added. Even if it was possible, I do not think a setting should exist for it.

**Comment by totrider** [comment]
So the actual answer is to modify any resource packs on the user end, and remove the textures responsible for the effect. A bit unfortunate with how the whole copyright-side of modding is like for modpack creators. Can't exactly get a resource pack and modify it to be re-uploaded without it being a problem.

Oh well, it was worth a try :)
