### ISSUE TITLE
no connected textures in 1.19.2

### ISSUE THREAD

**Issue by JBJones42** [PepperCode1/Continuity#254]
I'm not getting any sort of error screen, there are just no connecting textures at all, as if I didn't even have the mod downloaded at all even though it's right in the mod folder with all the mods I currently have installed, which are:

- AppleSkin
- Architectury API
- BCLib
- Better Advancements
- Better End
- Better Nether
- Better F3
- Bobby
- Chipped
- CIT Resewn
- Continuity
- Controlling
- End Remastered
- Indium
- Mod Menu
- Origins
- Resourceful Lib
- Roughly Enough Items
- Sodium
- Xaero's Minimap
- Xaero's World Map

I'm new to mods in Minecraft, so I'm not sure if this is an incompatibility issue or something else entirely? Please help, I just want nice looking glass ;w;

**Comment by YukiAyase** [comment]
Have you enabled Continuity's resource packs?

**Comment by JBJones42** [comment]
> Have you enabled Continuity's resource packs?

Sorry if this sounds dumb, but how do I do that? :'0

**Comment by YukiAyase** [comment]
> Sorry if this sounds dumb, but how do I do that? :'0

In the resource pack menu, you basically just enable it like any other resource pack

**Comment by JBJones42** [comment]
> In the resource pack menu, you basically just enable it like any other resource pack

That fixed it perfectly, thank you so much! :]
