### ISSUE TITLE
Continuity not working in 1.19.4

### ISSUE THREAD

**Issue by zLc362** [PepperCode1/Continuity#256]
![image](https://github.com/PepperCode1/Continuity/assets/108236176/e4a8bb8d-a091-4aa1-b0b1-2d7d5e638fda)
![image](https://github.com/PepperCode1/Continuity/assets/108236176/9b76c16a-a7de-40be-9059-de89f4d47248)
![image](https://github.com/PepperCode1/Continuity/assets/108236176/36abd0da-c358-4d6f-abca-4351e4f1a8d9)

I should have everything enabled, yet it still doesn't work.

I am playing with the breakneck modpack

**Comment by PepperCode1** [comment]
Read the default resource pack's description. It does not include any overlays. Use Xali's Enhanced Vanilla or BetterVanillaBuilding + BVB Overlays if you want these blocks to have a transition effect.
