### ISSUE TITLE
Game crashing when gravel falls

### ISSUE THREAD

**Issue by MKLEGOPRO** [PepperCode1/Continuity#257]
So I have the latest version of Continuity mod for 1.19.4 installed and I have noticed that the game crashes whenever a block of gravel falls. I know it is this mod because of a mod I have that tells me whenever a mod makes my game crash

**Comment by YukiAyase** [comment]
Do you have Sodium installed as well?
If yes, you need Indium, https://modrinth.com/mod/indium/version/1.0.15+mc1.19.4
If no, please send your log file, it can be found in .minecraft/logs, filename is "latest"

**Comment by MKLEGOPRO** [comment]
I didn´t have indium. Now i do, and it works. Tanks!

**Comment by PepperCode1** [comment]
Duplicate of #107.
