### ISSUE TITLE
Please update to Minecraft version 1.20 for your module.

### ISSUE THREAD

**Issue by surfishs** [PepperCode1/Continuity#258]
Please update to Minecraft version 1.20 for your module.

**Comment by YukiAyase** [comment]
Pepper is working on the update
We all just have to wait for it to be ready
There're are no ETAs

**Comment by surfishs** [comment]
Thank you for your reply

> Pepper 正在开发更新 我们只需要等待它准备就绪 没有预计到达时间

**Comment by YukiAyase** [comment]
Continuity 3.0.0-beta.2 has released for Minecraft 1.20!
https://modrinth.com/mod/continuity/version/3.0.0-beta.2+1.20
