### ISSUE TITLE
Continuity conflicts with From the Fog (impossible to load its resource pack)

### ISSUE THREAD

**Issue by vico93** [PepperCode1/Continuity#260]
After installing Continuity [3.0.0-beta.2](https://modrinth.com/mod/continuity/version/3.0.0-beta.2+1.20) on my 1.20 modpack, the resource pack part of [From the Fog](https://github.com/LunarEclipseStudios/From-The-Fog) stopped working. If it was loaded before Continuity is installed, it will deactivate _all_ resource packs except vanilla and fabric ones and give a toast telling a resource pack is invalid on the main menu. If the player try to load FtF with continuity present, it will freeze in the Mojang loading screen.

Without Continuity present, even FtF still on 1.19.4 it loads and works fine.

_PS.: pinging @Bret06 to follow the issue._

**Comment by PepperCode1** [comment]
Provide your game log.

**Comment by vico93** [comment]
Very strange - after trying to update to Fabric Loader/API 1.20.1 and going back (since almost no mods loaded on the new version), next time i've opened it on my PC it resumed loading FtF.

Also, on my laptop, after pushing the updates i did on the PC, it also loaded.

I think something weird happened on my laptop that temporally borked the FtF loading, i will close this for a while, if the issue returns, i will send you my whole game folder (with the logs included).
