### ISSUE TITLE
me being stupid sorry

### ISSUE THREAD

**Issue by StealthyDrake12** [PepperCode1/Continuity#263]
crash report., randomly got this crash, hope this helps. it keeps happening when i join the server, pretty sure continuity is at fault ;(
[crash-2023-06-17_10.33.06-client.txt](https://github.com/PepperCode1/Continuity/files/11778484/crash-2023-06-17_10.33.06-client.txt)

**Comment by YukiAyase** [comment]
From the looks of it you don't have Indium installed _either that or I'm blind_
https://modrinth.com/mod/indium/version/1.0.18+mc1.20

**Comment by StealthyDrake12** [comment]
oops sorry
