### ISSUE TITLE
3.0.0-beta.2+1.20 game crashes after gravel falls

### ISSUE THREAD

**Issue by NuggetPudding** [PepperCode1/Continuity#265]
I have both sodium and indium installed
![image](https://github.com/PepperCode1/Continuity/assets/136999410/2100dbc7-8631-4135-8485-c08f98e63a2f)

**Comment by NuggetPudding** [comment]
nevermind I didn't have indium installed

**Comment by NuggetPudding** [comment]
I forgot to put it in the mods folder

**Comment by Subroutine7901** [comment]
Exact same issue, down to the indium part.

**Comment by YukiAyase** [comment]
> Exact same issue, down to the indium part.

**Please create your own thread which includes your latest log file and a screenshot of your mods folder if you're experiencing crashes**
_And please do also avoid necroing inactive threads_

**Comment by Subroutine7901** [comment]
Got it, sorry.

**Comment by ghost** [comment]
I have a same problem

**Comment by PepperCode1** [comment]
Duplicate of #107, as always.
