### ISSUE TITLE
Sodium's fix for ambient occlusion broken with continuity

### ISSUE THREAD

**Issue by SmajloSlovakian** [PepperCode1/Continuity#266]
when i turn the default continuity resourcepack, the ambient occlusion looks like vanilla - which it shouldn't when i have sodium installed...
the first picture is without the resourcepack (how it should look) and the second is with the resourcepack (how it looks normally without sodium)
(notice the upper-left and lower-right corners)
![2023-06-20_07 31 32](https://github.com/PepperCode1/Continuity/assets/16209307/1ee19b6e-7593-40a4-b57a-c638189d2583)
![2023-06-20_07 31 47](https://github.com/PepperCode1/Continuity/assets/16209307/afa97ccc-a343-4362-b983-d103acc7d0b9)

this is in 1.19.4 with continuity 3.0.0 beta 2

**Comment by PepperCode1** [comment]
This can only be fixed in Indium. Report your issue there.
