### ISSUE TITLE
Ad Astra making game crash.

### ISSUE THREAD

**Issue by DerpyMuffin25** [PepperCode1/Continuity#268]
With induim installed with the correct version of sodium paired with it, after loading the game it says this:
[crash-2023-06-22_17.50.32-client.txt](https://github.com/PepperCode1/Continuity/files/11837329/crash-2023-06-22_17.50.32-client.txt)
I believe it is due to Ad Astra if not please let me know how to change it.

**Comment by PepperCode1** [comment]
Continuity 2.0.2+1.19 will not work with 1.19.3. Update to 3.0.0-beta.2+1.19.3.
