### ISSUE TITLE
1.19.3-1.20 versions of the mod are not open source 

### ISSUE THREAD

**Issue by forkiesassds** [PepperCode1/Continuity#269]

**Comment by DJMoffinz** [comment]
i'm not sure, but i _think_ it is and it's just what's in the repo. it's not on the releases page cause it's not stable yet (eg, the beta from modrinth doesn't work on my minecraft) so you have to compile(?) it yourself (or get it at modrinth, as i said).

**Comment by forkiesassds** [comment]
> i'm not sure, but i _think_ it is and it's just what's in the repo. it's not on the releases page cause it's not stable yet (eg, the beta from modrinth doesn't work on my minecraft) so you have to compile(?) it yourself (or get it at modrinth, as i said).

You're entirely wrong, the version on the repository is months old and is for 1.19.2 at latest, no code is available for 1.19.3 or 1.20.

**Comment by DJMoffinz** [comment]
dang ok
yeah it not being open is deffo an issue then

**Comment by mrjasonn** [comment]
@PepperCode1 please fix as soon as possible

**Comment by jwaxy** [comment]
still no source
@PepperCode1 are you planning to upload it?

**Comment by forkiesassds** [comment]
They've said that sources will be published when 3.0 is no longer in beta.

**Comment by PepperCode1** [comment]
All sources have been uploaded.
