### ISSUE TITLE
After applying the texture pack, it will flash back to the state of no texture pack

### ISSUE THREAD

**Issue by nekochuc** [PepperCode1/Continuity#270]
After applying the texture pack, it will flash back to the state of no texture pack

**Comment by YukiAyase** [comment]
Please send a screenshot of your mods folder

**Comment by a-fan9823** [comment]
same here

**Comment by YukiAyase** [comment]
> same here

_This doesn't help us at all_
Please provide a screenshot of your mods folder

**Comment by a-fan9823** [comment]
I have like 300+ mods its probably not gonna help =p

**Comment by a-fan9823** [comment]
I can't even fullscreen to see all of them

**Comment by YukiAyase** [comment]
> I have like 300+ mods its probably not gonna help =p

That is a big list, still showing it wouldn't hurt anyone
And if you still don't want to take a screenshot
**Double check if you have Indium**
If you do have Indium then one or more mod/s is causing the problem

**Comment by a-fan9823** [comment]
hmm
if I don't have indium installed the game crashes when a falling block spawns

**Comment by YukiAyase** [comment]
> hmm if I don't have indium installed the game crashes when a falling block spawns

That's the problem there
You probably have Sodium installed
**Currently, you need to have Indium if you have Sodium installed**
![image](https://github.com/PepperCode1/Continuity/assets/64414315/750bbaff-d61f-44ba-9196-6c9f517d5995)

**Comment by a-fan9823** [comment]
yeah I have indium

**Comment by YukiAyase** [comment]
> yeah I have indium

Then one or more mod/s is causing the problem with such a big list
There's nothing more to do other than test which mod is causing Continuity to not work

**Comment by a-fan9823** [comment]
bruhhh I hate mods, now there isn't a problem

**Comment by a-fan9823** [comment]
I swear sometimes mods just break after not breaking and vice versa

**Comment by a-fan9823** [comment]
sorry for the waste of time...

**Comment by kirbyhi5** [comment]
https://github.com/comp500/Indium/issues/206#issue-1786226830

**Comment by kirbyhi5** [comment]
https://github.com/comp500/Indium/issues/206

**Comment by YukiAyase** [comment]
> [comp500/Indium#206](https://github.com/comp500/Indium/issues/206)

This is a completely different issue and is not related to this thread at all

**Comment by Snipperly** [comment]
I have this happen as well.. just in 1.20 (with the beta version of continuity) - a friend of me also as we ran into the same issue of Mizunos16craft not working and some other resource packs for me.. which I sadly do not remember and cannot add to this list to figure out why- 
![Screenshot 2023-07-05 235528](https://github.com/PepperCode1/Continuity/assets/138728593/22a8b87d-d11b-4873-8506-2425a3cf692d)
i can share this screenshot of my mod folder tho.. (put a couple of them out tho and tested if it would work then as I never ran into this issue with Continuity before but as I put continuity out it was fixed)
may this help to find out why - hav a nice day!

**Comment by YukiAyase** [comment]
> I have this happen as well.. just in 1.20 (with the beta version of continuity) - a friend of me also as we ran into the same issue of Mizunos16craft not working and some other resource packs for me.. which I sadly do not remember and cannot add to this list to figure out why- ![Screenshot 2023-07-05 235528](https://user-images.githubusercontent.com/138728593/251292020-22a8b87d-d11b-4873-8506-2425a3cf692d.png) i can share this screenshot of my mod folder tho.. (put a couple of them out tho and tested if it would work then as I never ran into this issue with Continuity before but as I put continuity out it was fixed) may this help to find out why - hav a nice day!

Install Indium
https://modrinth.com/mod/indium/version/1.0.18+mc1.20

**Comment by Snipperly** [comment]
Thank you! I accidentaly had it on deactivated.. so i wasnt aware that it is not loading because of that! - Have a nice day!
