### ISSUE TITLE
auto generated normal map issue with Complementary Shaders

### ISSUE THREAD

**Issue by Pdam67** [PepperCode1/Continuity#275]
![2023-07-08_12 54 58](https://github.com/PepperCode1/Continuity/assets/121340850/193cc0c4-9610-4ddc-87af-162e81b3a85d)

Causes an issue with the reflection of the sun on the grass with default settings

Do you think it would be possible to fix?

**Comment by PepperCode1** [comment]
What is the issue?

**Comment by Pdam67** [comment]
I'll send another screenshot on the matter:
![2023-07-09_21 31 13](https://github.com/PepperCode1/Continuity/assets/121340850/a1e148f1-840b-4dd7-955c-ee303db0b133)

Basically the PBR (i think) is all messed up and shows a reflection of the sun on the opposite direction and causes this weird reflection in the image that isn't meant to be ther

I sent a discord message first on the complementary shader server support and I was instantly told that this was an issue with Continuity mod

Same scene without the mod:
![2023-07-09_21 39 53](https://github.com/PepperCode1/Continuity/assets/121340850/43c4cf99-fb9e-4023-b24e-46a4fefcd14b)

This is how it is meant to look:

**Comment by Pdam67** [comment]
Sorry but this is the only info i can give as i don't really know how the mod works or how complementary shaders work however if you are unable to resolve the issue it's fine by me

**Comment by PepperCode1** [comment]
Continuity does not interact with PBR at all so it is very unlikely that this is a Continuity bug.

**Comment by PepperCode1** [comment]
I just tested this and reproduced it without Continuity. As usual, it is an Iris bug that only happens when rendering blocks through Indium. I have already reported this to Iris's lead developer and it may be fixed in the next Iris release.
