### ISSUE TITLE
Just doesn't load connected textures.

### ISSUE THREAD

**Issue by EysseW** [PepperCode1/Continuity#28]
Hi there, so I have got the mod fully installed. I have all the extra mods needed and I have got mod menu saying it's installed. I also tested some conencted texture texturepacks on it, but none worked. The connected textures just won't load. Not with default texturepacks either. Am I doing something wrong or is it a bug?

**Comment by FwuffyPetsOwO** [comment]
send us a log file please:
Game logs can be found in the logs sub-folder in .minecraft folder - we're probably interested in the file named latest.log

**Comment by EysseW** [comment]
[MultiMC-0.log](https://github.com/PepperCode1/Continuity/files/7620775/MultiMC-0.log)
There is quite a few mods in there. I hope you can find your way through the large log.

**Comment by KagefumiMerry** [comment]
It seems to be MultiMC Log, not the MC one we would like to know,
The actual log is located inside the instance folder and logs sub-folder in .minecraft folder

i.e. MultiMc/instances/your instance folder/. Minecraft/log

Or you can at least put the screenshot of your mod list inside "edit instance" - loader mods function.

also there is log listed in "edit instance" - logs function.

**Comment by EysseW** [comment]
Woops, my file manager told me this was the latest edited file name log in the folder, so I assumed it would be this one. I'll just copy multimc's one instead
[LOG.txt](https://github.com/PepperCode1/Continuity/files/7621214/LOG.txt)
.

**Comment by FwuffyPetsOwO** [comment]
This is a large mods list, could you confirm that this issue also happens with only Continuity and Fabric API activated?

**Comment by EysseW** [comment]
I couldn't, so I started experimenting with turning mods off and such. I came to the conclusion that moremcmeta and continuity are compatible in the way that they start together, but moremcmeta stops continuity from working. Maybe there is a way one of the mod owners could make them compatible?

**Comment by PepperCode1** [comment]
The incompatibility can be tracked here: soir20/MoreMcmeta#3.
