### ISSUE TITLE
Invisible textures all over the world 

### ISSUE THREAD

**Issue by aemishki** [PepperCode1/Continuity#280]
Idk what i need to do with this, turning on the mod breaks whole world, issue is prescent both online and offline

![2023-07-12_12 25 14](https://github.com/PepperCode1/Continuity/assets/139338495/9fc72ad2-88e5-44ea-b704-ddf6248c3a59)
![2023-07-12_12 21 27](https://github.com/PepperCode1/Continuity/assets/139338495/9314dcc2-e6d0-4fbf-bee7-66be9b7426b1)

**Comment by YukiAyase** [comment]
What version of Minecraft are you using?

**Comment by aemishki** [comment]
> What version of Minecraft are you using?

1.19.4

**Comment by YukiAyase** [comment]
> 1.19.4

Use this version of Indium instead
https://modrinth.com/mod/indium/version/1.0.15+mc1.19.4
