### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by L4ck3y** [PepperCode1/Continuity#281]
i got this crash report when i try to starting the game i have the latest version of continuity (the beta one for 1.20.1) pls help

![Ekran görüntüsü 2023-07-13 230036](https://github.com/PepperCode1/Continuity/assets/74822126/670a63c1-f90d-4ba8-a3ce-b974b9447b56)
[crash-2023-07-13_22.57.20-client.txt](https://github.com/PepperCode1/Continuity/files/12044034/crash-2023-07-13_22.57.20-client.txt)

**Comment by YukiAyase** [comment]
Try removing **ForgetMeChunk**, its not updated to 1.20
That may be affecting other mods
If that doesn't help, please send your full log instead, it can be found in .minecraft/logs, filename is "latest"

**Comment by L4ck3y** [comment]
it worked thx alot
