### ISSUE TITLE
Smooth lighting bug with Complementary Reimagined Shaders

### ISSUE THREAD

**Issue by Slooshie1** [PepperCode1/Continuity#284]
![image](https://github.com/PepperCode1/Continuity/assets/90230538/d6d97760-1bbf-4478-9499-cd44bc5a60bf)

How it looks on Complementary Shaders v4.7.2:
![image](https://github.com/PepperCode1/Continuity/assets/90230538/751c8741-d6ed-4d37-869a-071826420e77)

**Comment by Slooshie1** [comment]
also this is what it looks like with smooth lighting off on Reimagined
![image](https://github.com/PepperCode1/Continuity/assets/90230538/058ae0f2-f9c2-464a-8df2-ead3cd3e391b)

**Comment by Slooshie1** [comment]
it gets even more messed up with Bare Bones CTM (looks normal when renaming optifine folder)
![image](https://github.com/PepperCode1/Continuity/assets/90230538/ec4ba7c9-0a4e-4b7e-bd4d-18fe7259edab)

**Comment by PepperCode1** [comment]
This is an Iris bug that has already been reported and will be fixed in the next Iris release.
