### ISSUE TITLE
connect "material" tag doesn't seem to work

### ISSUE THREAD

**Issue by LunaByter** [PepperCode1/Continuity#285]
For whatever reason attempting to use `connect=material` in a ctm.properties file doesn't seem to affect anything. Shown here is the normal set of copper blocks connecting to themselves, but not the other types. The intended behavior would be that the edges would simply make a perfect square. I have also tried this with other block types such as dirts (Dirt, Coarse Dirt, and Rooted Dirt) and got the same results.

![2023-07-21_13 55 08](https://github.com/PepperCode1/Continuity/assets/108190570/3f9e192b-de96-46cb-9f27-27492fec082a)

**Comment by PepperCode1** [comment]
This value was removed from both Optifine and Continuity in 1.20. It will not be added back as the code that made it possible was completely removed in vanilla 1.20.

**Comment by LunaByter** [comment]
So do we just not have this option anymore? If there's another way to accomplish this now it would be much appreciated if you could inform me how.

**Comment by PepperCode1** [comment]
There is no alternative other than the other available values for `connect` (`state`, `block`, and `tile`) at the moment. I plan to add additional features eventually.
