### ISSUE TITLE
Mod instantly crashes when using Quilt Loader, Yes people actually use quilt.

### ISSUE THREAD

**Issue by Pdam67** [PepperCode1/Continuity#288]
Crashes on the latest beta (0.20.0-beta.4) and release (0.19.2) of Quilt Loader with Quilted Fabric API.

[crash-2023-07-24_18.44.23.1976-quilt_loader.txt](https://github.com/PepperCode1/Continuity/files/12148634/crash-2023-07-24_18.44.23.1976-quilt_loader.txt)

[latest.log](https://github.com/PepperCode1/Continuity/files/12148637/latest.log)

Idk maybe i'm doing something wrong. It could be a problem with Quilt.

**Comment by ImGRUI** [comment]
Quilted FAPI isn't updated to the latest version of FAPI, which are required for latest continuity version. Quilt issue

**Comment by Pdam67** [comment]
Thanks!
