### ISSUE TITLE
texture problem

### ISSUE THREAD

**Issue by ADTheMiner** [PepperCode1/Continuity#289]
i reinstalled the texture pack many times and i get the same result without contuinity it works but obviously the connected textures wont work i have everything installed properly indium,sodium,latest fabric api and have no other mods conflicting even the stay true wont work
![Screenshot_20230727-215328](https://github.com/PepperCode1/Continuity/assets/90947387/07379193-a979-4008-ac3f-f2406c9b9686)
![Screenshot_20230727-215405](https://github.com/PepperCode1/Continuity/assets/90947387/55776e9f-5fe1-4420-9fda-a81f2e7653b5)

**Comment by PepperCode1** [comment]
Please send your log.

**Comment by Spike-has-no-idea-how-to-code** [comment]
What version are you using because I’ve been told this is fixed in beta3, but I can’t use it because the newest indium version depends on fabric 86+ and quilted hasn’t updated to this therefore for now beta3 is incompatible with quilt

**Comment by PepperCode1** [comment]
There have been no updates on this issue in over a month. If you are still experiencing issues, open a new issue.
