### ISSUE TITLE
Continuity not working with multiple glass layers

### ISSUE THREAD

**Issue by Blackfindus** [PepperCode1/Continuity#290]
I was trying to do the fog effect by doing multiple glass layers and noticed that the mod broke when rendering glass through glass.

![2023-07-28_12 18 56](https://github.com/PepperCode1/Continuity/assets/133017210/1cb0839a-d500-4f47-86cf-c275a3885e13)
![2023-07-28_12 18 45](https://github.com/PepperCode1/Continuity/assets/133017210/390d8e7b-6ae7-48bb-9255-640aa12ddcb0)

**Comment by YukiAyase** [comment]
Assuming you also have **Sodium installed**
This is not a Continuity issue
Please refer to this [issue](https://github.com/CaffeineMC/sodium-fabric/issues/38)  if you do have Sodium installed, we all have to wait for Sodium devs to fix this
