### ISSUE TITLE
All colored blocks become white

### ISSUE THREAD

**Issue by Fortuna67** [PepperCode1/Continuity#291]
I'm using Patrix ressource pack and any colored block (wool, stained glass, etc) become white when they have connected textures
Then i'm using Faithful PBR wich have connected texture too, same issue

I'm using the version 3.0.0 beta 3 on 1.19.4

![2023-07-30_11 26 03](https://github.com/PepperCode1/Continuity/assets/44172841/b6cb08e7-38e5-4913-b18a-3330464fa12c)
Here is connected texturs on

![2023-07-30_11 26 12](https://github.com/PepperCode1/Continuity/assets/44172841/f4e9a1be-c261-4343-b2a7-a2d2e2879a75)
Here is connected texture off

**Comment by PepperCode1** [comment]
Continuity does not and will not implement OptiFine's color features. There are other mods for this.
