### ISSUE TITLE
Bug with shadows when in use of built-in resource pack

### ISSUE THREAD

**Issue by MbtMarco** [PepperCode1/Continuity#294]
### BEFORE:
![2023-08-05_21 41 36](https://github.com/PepperCode1/Continuity/assets/124934175/46071a42-5540-4ad8-881a-7c82f0dec858)

### AFTER:
![2023-08-05_21 41 52](https://github.com/PepperCode1/Continuity/assets/124934175/7b48edbe-4829-407f-8b25-9364632ff1b4)

### Resource packs enabled:
<img width="1440" alt="Screenshot 2023-08-05 alle 21 41 46" src="https://github.com/PepperCode1/Continuity/assets/124934175/2862c42f-0a89-4390-90b5-014c23d1489e">

I am 100% sure that Continuity that cause this issue because I installed the mods I use singorlarly after each startup to find the one that was creating the problem. 

**(Sodium 0.0.5 + Indium 1.0.22+mc1.20.1)**

**Comment by PepperCode1** [comment]
Duplicate of comp500/Indium#220.

**Comment by MbtMarco** [comment]
Sorry :P

**Comment by MbtMarco** [comment]
I noticed that the problem occurs only when applying the built-in resource pack. When you don't enable it, it doesn't create this problem with shadows.
