### ISSUE TITLE
Continuity  Making Me Crash When Pistons move

### ISSUE THREAD

**Issue by DaJRJesus** [PepperCode1/Continuity#296]
I'm not sure if its just Continuity or its a conflict with it and another mod but here is my crash log and removing continuity fixed me crashing.
[crash-2023-08-06_01.47.26-client.txt](https://github.com/PepperCode1/Continuity/files/12269620/crash-2023-08-06_01.47.26-client.txt)

**Comment by DaJRJesus** [comment]
Indium is installed.

**Comment by DaJRJesus** [comment]
indium is installed

**Comment by PepperCode1** [comment]
No, Indium is not installed. The mod list in the crash report does not contain Indium.

**Comment by DaJRJesus** [comment]
that is definitely mb I thought I reinstalled it I guess not
