### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by ggauzin** [PepperCode1/Continuity#299]
crash report
https://pastebin.com/ST1Dz6PK

**Comment by Timolino456** [comment]
This has nothing do to with Continuity. It seems to be a conflict between Dashloader and Enhanced Block Entities. I'd suggest removing Dashloader, it causes issues way too often anyways.

**Comment by ggauzin** [comment]
thx, it helped

**Comment by ggauzin** [comment]
thx, it heklped
