### ISSUE TITLE
Tops of glass panes won't connect

### ISSUE THREAD

**Issue by SynaBytez** [PepperCode1/Continuity#30]
The tops of glass panes refuse to connect when it works fine in Optifine.
![image](https://user-images.githubusercontent.com/54920057/144230977-57f797fa-282e-4e63-b4db-7c028d120b79.png)
Sodium + Indium + Continuity

![image](https://user-images.githubusercontent.com/54920057/144231210-3335a2c6-8b9f-46b4-a585-137948734259.png)
Optifine

**Comment by notLily72** [comment]
did you enable the glass culling fix pack that is included with them mod?

**Comment by SynaBytez** [comment]
No, I'm not sure what that is

**Comment by notLily72** [comment]
![Screenshot 2021-12-01 070641](https://user-images.githubusercontent.com/86197720/144231806-c54a51eb-0812-4fb4-95be-e1d91098304c.png)

**Comment by SynaBytez** [comment]
Oh, thank you so much. I just enabled it and it's fixed now!
![image](https://user-images.githubusercontent.com/54920057/144231913-2b44e461-91ae-41a0-b6c8-4d8572ae1dc7.png)
