### ISSUE TITLE
Compatibility Issue Between gtceu and Continuity Mods

### ISSUE THREAD

**Issue by Start-Buling** [PepperCode1/Continuity#303]
### GregTech CEu Version
gtceu-fabric-1.20.1-1.0.11
### Addons Installed
- gtceu-fabric-1.20.1-1.0.11
- continuity-3.0.0-beta.2+1.20 or 3.0.0-beta.3+1.20.1
- fabric-api-0.87.0+1.20.1
### Encountered Issue 
when i use continuity-3.0.0-beta.2+1.20
the font becomes the wrong square garbled font, and the resourcepacks cannot be used,
when i use continuity-3.0.0-beta.3+1.20.1
The game launcher(HMCL3.5.5) displays an error message and does not proceed to the game interface.

the log of the continuity-3.0.0-beta.2+1.20：
[2023-08-15-1.log.gz](https://github.com/PepperCode1/Continuity/files/12337550/2023-08-15-1.log.gz)
the log of the continuity-3.0.0-beta.3+1.20.1：
[2023-08-15-2.log.gz](https://github.com/PepperCode1/Continuity/files/12337555/2023-08-15-2.log.gz)

**Comment by PepperCode1** [comment]
LDLib makes it so all states of all blocks that implement a certain interface use the same `ModelIdentifier`. Continuity assumes each state has a unique `ModelIdentifier`, but LDLib violates this assumption. I do not think LDLib should making multiple states use the same `ModelIdentifier`, so I will ask them to change this. I can still work around this issue in Continuity if it is not fixed in LDLib, but I would prefer not to.

**Comment by Start-Buling** [comment]
Thank you very much for your response. In fact, I had already raised this issue with them before submitting it to you. However, their response was to have me report it to you first. In reality, I very much agree with your point that they should prioritize solving this issue, rather than you. I believe both of these mods are excellent, and it would be unfortunate if they are unwilling to fix it. Also, I'd like to ask, do I need to report this issue to them again?

**Comment by PepperCode1** [comment]
> Also, I'd like to ask, do I need to report this issue to them again?

No, I opened a new issue with technical details: Low-Drag-MC/LDLib-Architectury#9.

**Comment by Start-Buling** [comment]
I understand,thank you for your dedicated attention to my issue..have a good day!

**Comment by PepperCode1** [comment]
This should have been fixed. Try updating your mods and check if it works.

**Comment by PepperCode1** [comment]
I will assume this is resolved. If not, open a new issue.
