### ISSUE TITLE
Wiki link redirects to repo

### ISSUE THREAD

**Issue by Pixelguru26** [PepperCode1/Continuity#305]
The supposed link to the documentation for this mod ( https://github.com/PepperCode1/Continuity/wiki ) appears not to refer to an actual page, redirecting immediately back to the main repository page ( https://github.com/PepperCode1/Continuity ) instead, and there is no apparent alternative means of access.

**Comment by PepperCode1** [comment]
Correct; this is because the wiki does not yet exist. I am in the process of writing documentation and added wiki links in preparation for when I add that documentation to the wiki.

**Comment by Pixelguru26** [comment]
That explains things, thank you for the clarification!
