### ISSUE TITLE
Fabric block appearance API is not supported

### ISSUE THREAD

**Issue by matthewperiut** [PepperCode1/Continuity#307]
Recreate using Chisel on 1.20.1 (https://github.com/matthewperiut/Chisel-Reborn) and Templates 2 (https://github.com/quat1024/templates-mod)

Continuity version: 3.0.0-beta.3+1.20.1

Template blocks use connected textures properly, but base block doesn't.
Unfortunately also, in the base connected textures pack, it uses matchBlocks not matchTiles, so there's also issues with that:

https://github.com/PepperCode1/Continuity/assets/18296791/ac99bc6c-2aa1-47c9-acd8-440f4bfac092

![image](https://github.com/PepperCode1/Continuity/assets/18296791/e746004f-678a-45a0-8bf0-c7473510d59f)

**Comment by matthewperiut** [comment]
![2023-08-29_22 23 30](https://github.com/PepperCode1/Continuity/assets/18296791/5445079e-13e0-4a04-9958-335d836085d7)
It's worse than I initially imagined.

**Comment by PepperCode1** [comment]
Neither Continuity nor Templates supports `FabricBlock#getAppearance`. I plan to support it eventually, but Templates needs to support it as well for the support on Continuity's side to do anything. Continuity also cannot handle non-axis-aligned faces like those on the sloped blocks.
