### ISSUE TITLE
Connected textures aren't working [1.20] 

### ISSUE THREAD

**Issue by MajiUltimata** [PepperCode1/Continuity#309]
No shaders. Resource pack placement doesn't matter
![image_2023-09-13_220356703](https://github.com/PepperCode1/Continuity/assets/58165796/fed0ad6d-7277-4072-a83b-3ef82410c749)
![image_2023-09-13_220441231](https://github.com/PepperCode1/Continuity/assets/58165796/dc5325a4-4cb7-4624-a9b6-012306550ba9)

**Comment by YukiAyase** [comment]
Please send a screenshot of what you mean by "not working" for further clarification

**Comment by YukiAyase** [comment]
Since there is still no response
**Continuity by default only connects GLASS, SANDSTONE and BOOKSHELVES**
Also, I'm going to assume you're talking about overlays, Continuity only provides support for them meaning a resource pack needs to have it
*Here's a sample for grass, sand and podzol*
![image](https://github.com/PepperCode1/Continuity/assets/64414315/834ffff6-d912-490e-a41b-47230de9a9f1)

The sample screenshot came from
https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla
*The best one I can suggest to use*

**Comment by TheProvy** [comment]
![Base Profile Screenshot 2023 09 20 - 22 56 45 98](https://github.com/PepperCode1/Continuity/assets/99236308/edd16503-3321-4cd3-b3a1-7ff7588442a4)
Having issues with glass not connecting, 1.20.1

**Comment by YukiAyase** [comment]
> ![Base Profile Screenshot 2023 09 20 - 22 56 45 98](https://user-images.githubusercontent.com/99236308/269471335-edd16503-3321-4cd3-b3a1-7ff7588442a4.png) Having issues with glass not connecting, 1.20.1

Make sure to enable Continuity's Resource packs in the resource pack menu
If that doesn't work, please send your log file
The log file can be found in .minecraft/logs, the filename is "latest"

**Comment by wj-lxax** [comment]
![b1d85e5831e7b67e06ebfbdc8fe820e9](https://github.com/PepperCode1/Continuity/assets/101759265/d62cab67-e096-4037-a2c7-0e13ef3d30ec)
![Uploading ebe647fbe0f578298ea233a2332ab098.png…]()
[latest.log](https://github.com/PepperCode1/Continuity/files/12710111/latest.log)
我也遇到了这种情况。这个是我的日志文件


> > ![基本配置文件屏幕截图 2023 09 20 - 22 56 45 98](https://user-images.githubusercontent.com/99236308/269471335-edd16503-3321-4cd3-b3a1-7ff7588442a4.png)玻璃未连接的问题，1.20.1
> 
> 确保在资源包菜单中启用连续性的资源包 如果这不起作用，请发送您的日志文件 日志文件可以在 .minecraft/logs 中找到，文件名为“latest”

**Comment by wj-lxax** [comment]
> > ![Base Profile Screenshot 2023 09 20 - 22 56 45 98](https://user-images.githubusercontent.com/99236308/269471335-edd16503-3321-4cd3-b3a1-7ff7588442a4.png)玻璃未连接的问题，1.20.1
> 
> 确保在资源包菜单中启用连续性的资源包 如果这不起作用，请发送您的日志文件 日志文件可以在 .minecraft/logs 中找到，文件名为“latest”
[latest.log](https://github.com/PepperCode1/Continuity/files/12710122/latest.log)
我也遇到了这种情况，添加了两个资源包，结果没用。这个是我的日志文件，麻烦看一下

**Comment by NolanHewitt** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/13685529/latest.log)
I have the same issue. Textures with the built in resource pack don't connect. Using 1.20.1 Quilt, newest version of the loader.

Other resource packs with connected textures do still work normally though.

**Comment by PepperCode1** [comment]
Update all mods. If this issue still happens, open a new issue.
