### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by digitaltrucker** [PepperCode1/Continuity#31]
The latest version of Continuity for MC 1.18 is incompatible with Sodium.  It loads and MC runs just fine, it just doesn't do anything.

**Comment by notLily72** [comment]
Do you have indium installed? If not please install it.

**Comment by FwuffyPetsOwO** [comment]
Indium's 1.18 release can be found here: https://github.com/comp500/Indium/releases/tag/1.0.2-alpha1%2Bmc1.18

**Comment by digitaltrucker** [comment]
Installing Indium did the trick.
