### ISSUE TITLE
Game crashes when pushing piston

### ISSUE THREAD

**Issue by CleMooling** [PepperCode1/Continuity#310]
If Fabric Mod Continuity is enabled, push any piston in gaming will crash the game client.
Mod version is 3.0.0-beta.3+1.20.1, game version is 1.20.1 stable

**Comment by YukiAyase** [comment]
Please send your log file
It can be found in **.minecraft/logs**, the filename is "**latest**"

**Comment by CleMooling** [comment]
> Please send your log file It can be found in **.minecraft/logs**, the filename is "**latest**"

[latest.log](https://github.com/PepperCode1/Continuity/files/12642327/latest.log)

**Comment by YukiAyase** [comment]
### Please install [Indium](https://modrinth.com/mod/indium)
Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Comment by CleMooling** [comment]
> ### Please install [Indium](https://modrinth.com/mod/indium)
> Duplicate of #107

Thanks for your help!
