### ISSUE TITLE
Crash with REI

### ISSUE THREAD

**Issue by Qhn-bncyqy** [PepperCode1/Continuity#311]
Can't figure out if it is trouble with another mod since there are a lot of them, so I'll leave everything here

Minecraft Version: 1.18.2
Continuity Version: 2.0.2

Crash Report:
[crash-2023-09-19_16.05.54-client.txt](https://github.com/PepperCode1/Continuity/files/12665631/crash-2023-09-19_16.05.54-client.txt)

Log:
[2023-09-19-1.log](https://github.com/PepperCode1/Continuity/files/12665636/2023-09-19-1.log)

**Comment by PepperCode1** [comment]
This is a Hephaestus issue. Report it to them.
