### ISSUE TITLE
Crashing with indium when loading resource packs

### ISSUE THREAD

**Issue by OS1230** [PepperCode1/Continuity#312]
I've been having trouble with Continuity as the indium mod file is crashing the game.

Is there a fix for this?
[crash-2023-09-22_13.20.14-client.txt](https://github.com/PepperCode1/Continuity/files/12699802/crash-2023-09-22_13.20.14-client.txt)
![image](https://github.com/PepperCode1/Continuity/assets/75417009/5f03cca4-3d49-4658-8b1c-362986de8d5b)
the second is the mods I'm using.

**Comment by YukiAyase** [comment]
# Downgrade **Fabri API** to version **0.88.x**
*I haven't looked at any updates on mods this week but I do know Indium 1.0.25 is incompatible with Fabric API 0.89.0*

**Comment by dutyunogasai** [comment]
I've downgraded the fabric api and still experiencing crashes when I try to load into my world with the connected texture packs enabled.

**Comment by YukiAyase** [comment]
> I've downgraded the fabric api and still experiencing crashes when I try to load into my world with the connected texture packs enabled.

**Please create a new thread instead of using someone else's**
Do also provide your log file, it can be found in .minecraft/logs, filename is "latest"
