### ISSUE TITLE
LambDynamicLights: Top of hopper is not lighted up when mod Continuity is installed

### ISSUE THREAD

**Issue by icynstant** [PepperCode1/Continuity#313]
With Continuity:
![2023-09-24_15 56 48](https://github.com/PepperCode1/Continuity/assets/127024748/c2657d2c-910d-45fd-a370-d5dd69a10946)

Without Continuity:
![2023-09-24_15 58 05](https://github.com/PepperCode1/Continuity/assets/127024748/df6322d6-4c2b-4b64-8961-87aa6d4f0f1a)

Mods:
![Screenshot_1](https://github.com/PepperCode1/Continuity/assets/127024748/1006af60-b5ff-4fa8-8972-f6a61a1c370d)

Looks like resource packs "Stay True" and "Clear Glass with Connected Textures" are causing this issue.

**Comment by icynstant** [comment]
My bad, I forgot to test it without resource packs. I may fix it by myself.

**Comment by PepperCode1** [comment]
This is most likely an LDL issue. Report it to them. I will leave this issue open just in case.

**Comment by icynstant** [comment]
> This is most likely an LDL issue. Report it to them. I will leave this issue open just in case.

I reported it on both sides, no answer from LDL yet

**Comment by BluSpring** [comment]
Can repro using doors
Mods: 
![image](https://github.com/PepperCode1/Continuity/assets/20620191/df901768-8c0b-4575-9c6d-e466c38e4864)

![image](https://github.com/PepperCode1/Continuity/assets/20620191/3420425c-c7a8-4791-af82-4e96a47d7a4a)

This bug doesn't seem to occur without Sodium, which leads me to believe that it may be my Sodium fix commit (https://github.com/LambdAurora/LambDynamicLights/commit/8c2c0107d75b5a853690f8d5ec093d501a0aee90) that is acting up here.

**Comment by PepperCode1** [comment]
Continuity only makes this bug visible, but Continuity does not cause it. This is an incompatibility between LDL and Indium.
