### ISSUE TITLE
Use 'fabric-api' mod ID in fabric.mod.json 

### ISSUE THREAD

**Issue by Poopooracoocoo** [PepperCode1/Continuity#316]
Users may be confused when they see that it depends on `fabric`, not knowing that it's referring to the Fabric API. 

>As of Minecraft 1.19.2, Fabric API's mod ID has changed from `fabric` to `fabric-api`. When backporting from 1.19.2 to earlier versions, you must alter the `depends` section of your `fabric.mod.json` to expect `fabric`.

From https://fabricmc.net/wiki/tutorial:setup#mod_setup

**Comment by PepperCode1** [comment]
I wanted to do this a while ago, but forgot about it. I will do this for the next release.

**Comment by PepperCode1** [comment]
This has been fixed with 3.0.0-beta.5.
