### ISSUE TITLE
Crash: Tessellating block in world - Indigo Renderer with Misa Resource Pack

### ISSUE THREAD

**Issue by velnias75** [PepperCode1/Continuity#317]
The bug #253 reappears *again/sill* with the current [Misa Resource Pack](https://www.curseforge.com/minecraft/texture-packs/misas-realistic/files/4777688) and with Version `3.0.0-beta.4` for `1.20.1` 😿 

The same crash in `latest.log`.

**Comment by YukiAyase** [comment]
Please send your own log file
*It can be found in **.minecraft/logs**, filename is "latest"*

**Comment by velnias75** [comment]
> Please send your own log file _It can be found in **.minecraft/logs**, filename is "latest"_

[latest.log](https://github.com/PepperCode1/Continuity/files/12811135/latest.log)

**Comment by PepperCode1** [comment]
One error is caused by Vanadium; the other is caused by MoreCulling. This is not the same issue as #253 and it is not a Continuity issue.

**Comment by velnias75** [comment]
Sure?

![Screenshot_20231005_033013](https://github.com/PepperCode1/Continuity/assets/4481414/dd48b508-2911-433d-a160-56f5afd72abe)
[crash-2023-10-05_03.29.21-client.txt](https://github.com/PepperCode1/Continuity/files/12811353/crash-2023-10-05_03.29.21-client.txt)

**Comment by velnias75** [comment]
> Sure?

Ok, disabled more cullong and vanadium and it works.
