### ISSUE TITLE
Menu text turns to squares

### ISSUE THREAD

**Issue by ZombieKeks** [PepperCode1/Continuity#318]
1.20,1 error - https://reddit.com/r/ModdedMinecraft/s/YHJmf0j1se the newest comment points out the issue.

**Comment by hexadecimal233** [comment]
Update your indium, sodium and fapi to the latest version should solve this

**Comment by ZombieKeks** [comment]
I freshly downloaded from modrith. Maybe some modconflict? Idk. I'm just updating my pack to 1.20.1 never had issues before

**Comment by YukiAyase** [comment]
Please upload your log file
It can be found in .minecraft/logs, filename is "latest"

**Comment by ZombieKeks** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/12904184/latest.log)
here u go

**Comment by YukiAyase** [comment]
Install Indium
https://modrinth.com/mod/indium

**Comment by ZombieKeks** [comment]
Dang, sorry. My fault. Should have checked if i have installed it first.
