### ISSUE TITLE
1.20.1 Random crash in world

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [PepperCode1/Continuity#319]
Hello,

A random crash happened while walking around in the world.
Stacktrace seems to point at Continuity.
[crash-2023-10-15_13.06.33-client.txt](https://github.com/PepperCode1/Continuity/files/12909365/crash-2023-10-15_13.06.33-client.txt)

**Comment by YukiAyase** [comment]
Install Indium
https://modrinth.com/mod/indium

**Comment by ZsoltMolnarrr** [comment]
If Indium is required to work, I think this mod should have it linked as a dependency.
Both loader and websites.

**Comment by YukiAyase** [comment]
> If Indium is required to work, I think this mod should have it linked as a dependency. Both loader and websites.

Literally on top of Continuity's description page on Modrinth and curseforge
**Modrinth**
![image](https://github.com/PepperCode1/Continuity/assets/64414315/6a5d9e4c-de8b-4403-a24a-851e0d710ba0)
**curseforge**
![image](https://github.com/PepperCode1/Continuity/assets/64414315/1680cb30-9850-4ccf-bad9-4396284a7714)

**Comment by ZsoltMolnarrr** [comment]
Thank you for the clarification.
When managing a so many mods I tend to rely on the dependency management built into the launchers.
I still think it could be implemented in a more straightforward way.
