### ISSUE TITLE
Missing Textures with Resource Pack

### ISSUE THREAD

**Issue by ShadoUrufu** [PepperCode1/Continuity#32]
Probably easier to just show this. 
[Missing Textures](https://cdn.discordapp.com/attachments/250801422960951296/917514036571168848/unknown.png)

Sodium kept showing white over all the textures, so I tried your mod, and got this. 
Resource Pack Overgrowth

EDIT: I have a custom pack on, and and trying to figure out the issue with it. It seems to be the one causing the issue. 
EDIT2: It also still does it with overgrown.
EDIT3: Using the 'Disable CTM' option lets me see the textures. But at that point, not connected.

**Comment by hanneskt** [comment]
Are you using Sodium? It happens to me when using this mod together with Sodium.

**Comment by PepperCode1** [comment]
Do you have Indium installed?

**Comment by hanneskt** [comment]
> Do you have Indium installed?

Indeed, Indium does fix this. Everything's working great now. Thanks!
