### ISSUE TITLE
mod doesnt work quilt loader 0.21.0

### ISSUE THREAD

**Issue by lukeea12** [PepperCode1/Continuity#320]
Gives this error message: 
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'continuity'!

Mod ver: 3.0.0 beta 4
Mc version: 1.19.4

**Comment by YukiAyase** [comment]
Please provide a log file
It can be found in **.minecraft/logs**, filename is **"latest"**

**Comment by lukeea12** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/12918100/latest.log)

**Comment by Arthurmeade12** [comment]
I'm not sure if this is the same issue, since the log @lukeea12 attached contained no crash, but Continuity crashes for me with Quilt loader 0.21.0. Running 1.19.4.
[https://mclo.gs/dD4qmg8](https://mclo.gs/dD4qmg8)

**Comment by PepperCode1** [comment]
Your version of Quilted Fabric API does not contain Model Loading API v1, which Continuity uses.

This seems like a Quilt issue because the changelog on Modrinth for the QSL version you are using says that it includes Model Loading API v1 and the code in the Quilted Fabric API repository also includes it.

**Comment by lukeea12** [comment]
So what should I do? Report the error in their page?

**Comment by PepperCode1** [comment]
I do not know what the cause of your issue is; I was replying to Arthurmeade12 and am already in contact with the QSL developers to resolve the issue. The log you sent did not contain any issues.

**Comment by lukeea12** [comment]
ok, thanks for the help anyways.

**Comment by PepperCode1** [comment]
I will assume your issue is the same since you are also on Quilt and using Minecraft 1.19.4. It is being tracked on the Quilted Fabric API repository since it is not a Continuity issue. QuiltMC/quilted-fabric-api#138
