### ISSUE TITLE
[1.20.1; Quilt ver. 0.21.0] Continuity requires at least version 0.88.1 or newer version of farbic, but only a differen version is present: 0.88.0

### ISSUE THREAD

**Issue by tonceDev** [PepperCode1/Continuity#323]
^^^^

**Comment by YukiAyase** [comment]
Please send your log file
It can be found in **.minecraft/logs**, filename is **"latest"**

**Comment by dklasp** [comment]
> Please send your log file It can be found in **.minecraft/logs**, filename is **"latest"**

Not the OP but here is mine 
[latest.log](https://github.com/PepperCode1/Continuity/files/13252075/latest.log)

**Comment by PepperCode1** [comment]
The error message that you put in the issue title describes everything. The fact that Continuity requires Fabric API 0.88.1 is not an issue. Update your QSL, or if the newest version does not work, let the QSL developers know that you need a version of Quilted Fabric API that provides Fabric API 0.88.1 or newer.
