### ISSUE TITLE
[1.20 Quilt] Invisible textures issue

### ISSUE THREAD

**Issue by chiseDelta** [PepperCode1/Continuity#326]
Everything is invisible except entities and particles. I turned off shaders and texture packs, but it didn't help. I think the problem is a conflict between mods. Screenshots below
![explorer_bh0NwAwDCI](https://github.com/PepperCode1/Continuity/assets/115950355/876dd748-2ebc-4afa-92e0-d1529c3c6287)
![javaw_TuW1utW2Wg](https://github.com/PepperCode1/Continuity/assets/115950355/5586ee37-ace3-4cea-812e-92209d8cbb01)

**Comment by Poopooracoocoo** [comment]
https://modrinth.com/mod/qsl/version/7.2.2+0.88.1-1.20.1

**Comment by chiseDelta** [comment]
> https://modrinth.com/mod/qsl/version/7.2.2+0.88.1-1.20.1

OMG! ITS WORKING! THANK YOU SO MUCH!
