### ISSUE TITLE
Incompatibility between Continuty, Hephaestus, and Resource Packs on both Quilt and Fabric—Invisible Hephaestus Blocks with Continuity Enabled, Resource Packs only half-work with Continuity disabled.

### ISSUE THREAD

**Issue by viedemarli** [PepperCode1/Continuity#328]
### Quilt/Fabric Instance Versions
Quilt 0.21.1 / Fabric 0.14.24
### Quilt/Fabric API Versions
Quilted Fabric API 7.4.0+0.90.0 / Fabric API 0.90.4
### Continuity Version
3.0.0-beta+4 (both Instances)
### Hephaestus Version
3.6.3.232 (both Instances)

### Issue(s)
Whenever loading both Continuity and Hephaestus together, any items from Hephaestus end up rendering invisible in Hephaestus' blocks—namely the Casting Basin and Casting Table. Fluids are also all white, even if they have different colors to signify different smelted ore types, and are also rendered invisible when pouring into a Basin or Table. Particle effects work fine (casted parts and ingots sizzle and blow little black particles to signify they're finished cooling).

Disabling Continuity fixes the issue completely, and the reverse—disabling Hephaestus fixes the issue with resource packs requiring Continuity to continue working. I hope that makes sense, I am very tired from handing out candy today! Using Fabric over Quilt also doesn't fix either issue —they still persist, so I don't think it's a problem with the loader itself. I included both loader versions because I did testing between both of them, so maybe it will help.

### More Info/Other Stuff
I found out the incompatibility through brute force. I kept getting invisible items and went through my mod list one by one (it's quite big, almost modpack size, but all of the mods work just fine together, no problems!) and found out that it was indeed Continuity causing both issues. I don't know if it's an incompatibility on Hephaestus' end or this one, so I figured I would open a bug report here in case the incompatibility is not intentional and can at all be fixed and is on Continuity's end instead of Hephaestus'. 

Similarly, I had already opened a bug report on Hephaestus' side of things in case the issue is on that side. I should have made the bug report here yesterday, but I was exhausted and had to sleep to be ready for today. That's totally on me and I apologize!

### Minecraft Log and Hephaestus' bug report
[here is my Minecraft log](https://pastebin.com/AnfAgyRW) with Continuity _and_ Hephaestus enabled; I hope it's of some help! [Here is also the report on Hephaestus' end](https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/85), which is a little more in-depth but a little roundabout as I did not realize it was Continuity at first (I thought it was Quilt; this is now not true, and I apologize for the jumbled mess there and also here).

**Comment by AlphaMode** [comment]
This has been fixed in the latest version of Hephaestus this can be closed
