### ISSUE TITLE
Connected glass not working (using without quilted fabric api bc using fabric)

### ISSUE THREAD

**Issue by Sciccorz** [PepperCode1/Continuity#330]
![Screenshot 2023-11-05 142609](https://github.com/PepperCode1/Continuity/assets/140935674/835b1024-5446-47aa-9893-6f2501bb012b)
![Screenshot 2023-11-05 142620](https://github.com/PepperCode1/Continuity/assets/140935674/f9c93402-9e43-4cf7-b10d-cceb2126b772)

![image](https://github.com/PepperCode1/Continuity/assets/140935674/b4bd93c0-1cf1-4a16-90b5-e975449967fc)

**Comment by YukiAyase** [comment]
Please make sure you have Continuity's resourcepacks enabled
If you do have them enabled

Send your log file instead, it can be found in .minecraft/logs, filename is "latest"

**Comment by Sciccorz** [comment]
That fixed it thx!
