### ISSUE TITLE
Stained glass isnt connecting

### ISSUE THREAD

**Issue by moonchurro** [PepperCode1/Continuity#331]
I am playing Better Minecraft 1.19.2 which has sodium, indium and continuity installed. Normal glass seems to connect but stained glass does not, any fixes?
![huge_2023-11-07_13 39 56](https://github.com/PepperCode1/Continuity/assets/150110351/211ab01b-5c5b-4f1b-b5df-908eb24be438)
![huge_2023-11-07_13 40 02](https://github.com/PepperCode1/Continuity/assets/150110351/c333990d-2a9d-4e95-9a36-95e317c6921c)

**Comment by PepperCode1** [comment]
My guess is that you have another resource pack which replaces the vanilla glass textures. This causes the corresponding connected textures in the default pack to be disabled, which is not a bug. Also note that the texture of clear glass in that screenshot is not the vanilla texture, meaning a different pack is providing connected textures for it.
