### ISSUE TITLE
Crash when i turn on the texturepack

### ISSUE THREAD

**Issue by someDANGERpeople** [PepperCode1/Continuity#332]
My game instantly crashes whenever I log into a world with the texturepack.
crash report: https://mclo.gs/Mu7tVxT

**Comment by YukiAyase** [comment]
Update Sodium, Indium and Iris
Edit: And any other mods that depends on those three

**Comment by someDANGERpeople** [comment]
> Update Sodium, Indium and Iris Edit: And any other mods that depends on those three

Thanks, it worked
