### ISSUE TITLE
Connected Textures Not Connecting

### ISSUE THREAD

**Issue by CarbonNode** [PepperCode1/Continuity#333]
Running fabric 1.20.1
with Indium
Texture packs are enabled
Tried multiple different texture packs
Tried Restarting or just running Default texture packs
Tried testing grass and sandstone does not work

**Comment by kawashirov** [comment]
Same issue 

Minecraft 1.20.1
Quilt Loader 0.21.2
qfapi-7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1.jar
continuity-3.0.0-beta.4+1.20.1.jar
indium-1.0.27+mc1.20.1.jar  
sodium-fabric-mc1.20.1-0.5.3.jar

No errors, just doing nothing. Like mod was not installed.
Tried various configurations, respacks, on/off mods - no difference.

**Comment by YukiAyase** [comment]
> Running fabric 1.20.1 with Indium Texture packs are enabled Tried multiple different texture packs Tried Restarting or just running Default texture packs Tried testing grass and sandstone does not work

Please send your log file
It can be found in **.minecraft/logs**, filename is **"latest"**

**Comment by rikusen0335** [comment]
I am actually getting same behavior, aand almost same mods structure, so I'll send mine to investigate.
Not familiar with fabric, so if anything is wrong please tell me

My mods:
![image](https://github.com/PepperCode1/Continuity/assets/19174234/65fa62ff-c8eb-4fdc-8c75-1d349abfe134)

Logs
[latest.log](https://github.com/PepperCode1/Continuity/files/13339589/latest.log)

**Comment by YukiAyase** [comment]
> I am actually getting same behavior, aand almost same mods structure, so I'll send mine to investigate. Not familiar with fabric, so if anything is wrong please tell me
> 
> My mods: ![image](https://user-images.githubusercontent.com/19174234/282554499-65fa62ff-c8eb-4fdc-8c75-1d349abfe134.png)
> 
> Logs [latest.log](https://github.com/PepperCode1/Continuity/files/13339589/latest.log)

There seems to be no issue on yours
Have you made sure to enable Continuity's resource packs?

**Comment by rikusen0335** [comment]
Oh I didn't know I need textures
I tried built-in one and it worked, just in my case
![2023-11-14_20 24 04](https://github.com/PepperCode1/Continuity/assets/19174234/e53d4547-d423-411d-8b73-b3fe7c6c098f)

**Comment by rikusen0335** [comment]
Idk if @Sultansmooth is also facing the same issue, but if no responses around for a week this issue may be able to close
