### ISSUE TITLE
Game crash when gravity block gets rendered

### ISSUE THREAD

**Issue by DBPT210** [PepperCode1/Continuity#336]
There is a issue that makes the game crash everytime a block gets affected by gravity, such as sand, gravel, etc.
Attached is the crash report.
[Here is a video showcasing the problem.](https://youtu.be/GF4KOhUzN6M)
[Here is the game log.](https://paste.atlauncher.com/view/81f4147c-dfd3-4d63-a449-aff3cbdc5399)

[crash-2023-11-13_19.19.18-client.txt](https://github.com/PepperCode1/Continuity/files/13340157/crash-2023-11-13_19.19.18-client.txt)

**Comment by YukiAyase** [comment]
Install indium
https://modrinth.com/mod/indium

**Comment by DBPT210** [comment]
> Install indium https://modrinth.com/mod/indium

Oh, I didn't realized that mod was needed to make it work.
Actually, the only mention about it is on the CurseForge page, there is no mention on the modrinth page.

I apologize for any inconvenience then.
