### ISSUE TITLE
There is a bug with coloured glass and water.

### ISSUE THREAD

**Issue by Kastetas** [PepperCode1/Continuity#338]
There is a bug if there is a water beyond the glass it starts to bug out like this
![image_2023-11-18_191601817](https://github.com/PepperCode1/Continuity/assets/151393046/f615cc06-aa8d-4083-9257-2f674773f751)
Its all the mods I use
![image_2023-11-18_191323986](https://github.com/PepperCode1/Continuity/assets/151393046/6fa2264b-079f-4a49-87b3-22674fbb1c84)
Maybe there is a fix for this?

**Comment by PepperCode1** [comment]
CaffeineMC/sodium-fabric#38
