### ISSUE TITLE
Connecting Textures not working

### ISSUE THREAD

**Issue by emschmenk** [PepperCode1/Continuity#340]
Hello, i have seen some other posts about continuity not connecting textures and saw that sometimes it has to do with other mods and stuff. I have been trying to figure out why my textures aren't connecting and I just cannot seem to figure it out. I am attaching a screenshot of my mods and a copy of my latest log file. I have the texture packs enabled. Any help is greatly appreciated.
[latest.log](https://github.com/PepperCode1/Continuity/files/13460698/latest.log)

<img width="908" alt="Screenshot 2023-11-24 at 10 46 45 AM" src="https://github.com/PepperCode1/Continuity/assets/151948239/0686e94b-6c02-412f-afdb-504160fd273d">

**Comment by YukiAyase** [comment]
If you've already made sure you have Continuity's resource packs enabled
Please do note that by default, Continuity only connects glass, bookshelves and sandstone, you'd need a custom resource pack for any other types of connections

**Comment by emschmenk** [comment]
> If you've already made sure you have Continuity's resource packs enabled Please do note that by default, Continuity only connects glass, bookshelves and sandstone, you'd need a custom resource pack for any other types of connections

I have double checked my resource packs and they are enabled. they aren't even connecting the glass. any help is greatly appreciated

**Comment by PepperCode1** [comment]
Update all mods and send your log file if this still happens.

**Comment by TheCrafter8000** [comment]
My friend is having the same issue. We have the same exact jar file for the beta in 1.20.4 and his just aren't connecting. The only mods he has less mods installed than me

**Comment by Andromeda110K** [comment]
I've found a possible "workaround" for this.
If you have a resource pack enabled, you have to delete every glass texture, which are found in textures > blocks, then just apply Continuity resource pack, and glass textures will be connected.

I had the same issue, and doing that worked just fine, at least for me.

**Comment by PepperCode1** [comment]
The OP has not responded in months so I wil close this issue. Open a new one if you are having problems.

It is intentional that specific default connected textures get disabled if any resource pack replaces the corresponding base texture, such as the glass or bookshelf texture.
