### ISSUE TITLE
Issue with overlay textures 

### ISSUE THREAD

**Issue by Psikrios** [PepperCode1/Continuity#343]
For context I'm using continuity on quilt with sodium and indium. the texture pack i have is https://modrinth.com/resourcepack/overlays-reimagined . The podzol and sand are conflicting
![image](https://github.com/PepperCode1/Continuity/assets/102330643/62797308-2959-4f0a-bb3b-b10cbc33ba3e)

**Comment by PepperCode1** [comment]
Does it happen with OptiFine?

**Comment by Psikrios** [comment]
> Does it happen with OptiFine?

let me test.

**Comment by Psikrios** [comment]
> Does it happen with OptiFine?

The answer is yes. I realize now that it's the resource pack's fault and not yours. Also my bad it's mycelium that's conflicting. 
![2023-12-02_22 02 07](https://github.com/PepperCode1/Continuity/assets/102330643/bf269e00-5a8b-4e56-bcff-f42afdc24780)
