### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AlmightyAlex** [PepperCode1/Continuity#345]
its making my game crash

**Comment by YukiAyase** [comment]
Please send your log file located on .minecraft/logs, filename is "latest"

**Comment by AlmightyAlex** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/13561538/latest.log)

**Comment by YukiAyase** [comment]
Install [Indium](https://modrinth.com/mod/indium/version/1.0.27+mc1.20.1)


Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Comment by AlmightyAlex** [comment]
okk

**Comment by JaaiDead** [comment]
https://pastebin.com/ACS2rm2P
i have a very weird error and cilent crashing
with the fabric api
it happens exactly when i brake a sand block which a another sand block on top as a falling entity

**Comment by JaaiDead** [comment]
Also to note indium is not installed since its not updated to sodium 0.5.4

**Comment by PepperCode1** [comment]
Continuity will not magically work with Sodium just because Indium is not updated. No Indium means you will crash.
