### ISSUE TITLE
In version 1.20.2. The module cannot be used with the resource pack as it will prompt resource overload failure!

### ISSUE THREAD

**Issue by QianMuu** [PepperCode1/Continuity#349]
I am using fabric 1.20.2 version and downloading "continuity 3.0.0 beta. 4+1.20.2".
When only this unique "continue" is added to "mods", the startup resource package can be used normally.
But when other modules are added, the resource package cannot be used, and it will display "Overloading resource package error".
![{0EF9B928-B2ED-43eb-B658-521C1F327D23}](https://github.com/PepperCode1/Continuity/assets/50398180/08074095-ac20-4f14-a8e4-e87889d2c3db)

**Comment by YukiAyase** [comment]
Please send your log file found in **.minecraft/logs, filename is "latest"**

**Comment by PepperCode1** [comment]
The issue cannot be debugged without the log. It has been multiple months and the log has not been sent, so I will close the issue. Update all mods and open a new issue if this still happens.
