### ISSUE TITLE
every block is invisible (1.20.1)

### ISSUE THREAD

**Issue by Masterioq** [PepperCode1/Continuity#350]
when I load to any of my worlds, no blocks at all appear visible, this happens with only having the mod installed, you dont even need to activate built-in the resource packs for this to happen, I only tested this once but if you punch a block on survival the game crashes.
Im using shaders and the resource pack stay true, and here is my mod list:
![Captura de tela 2023-12-13 212613](https://github.com/PepperCode1/Continuity/assets/121316331/351840e1-b84a-4025-a8ab-bca66c70b3b7)

**Comment by YukiAyase** [comment]
Update Sodium, Iris and Indium

**Comment by TheTrashCrafter** [comment]
Same thing happening to me when using Vulkan Mod.

**Comment by YukiAyase** [comment]
> Same thing happening to me when using Vulkan Mod.

I'm not 100% sure but I do think **VulkanMod is not compatible with Continuity**
@PepperCode1 should have the solid answer for this one though

**Comment by PepperCode1** [comment]
From a quick look at VulkanMod's code, it seems that it does not support FRAPI, meaning it is incompatible with Continuity. It is fully on VulkanMod to support FRAPI and resolve the conflict.
