### ISSUE TITLE
Glass texture is not layering correctly

### ISSUE THREAD

**Issue by DragonLemonade** [PepperCode1/Continuity#353]
I have seen 2 other reddit posts about this where no one has found a fix, but no bug report here so heres this issue
if you try and layer glass like  i have done here (attatched images) theres a light then black glass gray glass repeated, on vanilla and optifine this would give off a foggy effect, with sodium, indium and continuity (everything in resource packs is enabled) it has this choppy look and is almost entirely see through, the effect only works from the top down but below side views do not work
![image](https://github.com/PepperCode1/Continuity/assets/97369043/1f3d8912-c5b1-423b-857a-905f0719e5d9)
![image](https://github.com/PepperCode1/Continuity/assets/97369043/45da1da2-40d5-4220-8242-dfebba451c06)
![image](https://github.com/PepperCode1/Continuity/assets/97369043/74b3fa1c-c9da-43a3-820e-71103d0d6938)

**Comment by PepperCode1** [comment]
CaffeineMC/sodium-fabric#38
