### ISSUE TITLE
Crash on startup 1.20.1 

### ISSUE THREAD

**Issue by Felisinnn** [PepperCode1/Continuity#354]
Full log: https://mclo.gs/AHqlUH0 
Crash log: https://mclo.gs/m7dSAa4 
Already tried disabling modernfix, physics mod, ferrite core, more culling and more culling extra. 

Disabling ferritocore lets me load the game, though as soon as I try to load a world the game crashes again: 
Full log: https://mclo.gs/LoUBiQm 
Crash log: https://mclo.gs/uoIBCwh

**Comment by PepperCode1** [comment]
This not a Continuity issue. When FerriteCore is not installed, `Enhanced_Celestials-fabric-1.20.1-5.0.0.2` is causing the crash. When FerriteCore is installed, the cause of the crash is the same as when Continuity is disabled (looking at the log in the issue you opened on the FerriteCore repository).
