### ISSUE TITLE
Continuity's rendering is having issues.

### ISSUE THREAD

**Issue by MagmaSlime123** [PepperCode1/Continuity#358]
Title, see the report below. Modlist is also included.

https://pastebin.com/Wg48hGVG

**Comment by YukiAyase** [comment]
Install [Indium](https://modrinth.com/mod/indium)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Comment by MagmaSlime123** [comment]
Seems MoreCulling and LambBetterGrass also hate this mod. A 4-way conflict.

https://pastebin.com/02P5Ub3Y

**Comment by YukiAyase** [comment]
> Seems MoreCulling and LambBetterGrass also hate this mod. A 4-way conflict.
> 
> https://pastebin.com/02P5Ub3Y

Its MoreCulling incompatibility with latest ModernFix
Solution: remove MoreCulling
https://github.com/FxMorin/MoreCulling/issues/195
