### ISSUE TITLE
I am wondering,

### ISSUE THREAD

**Issue by LilFatCat** [PepperCode1/Continuity#359]
I finally found the mod I wanted, but some resource packs I don't have for the blocks, or I don't even know there is any resource packs that Iam thinking of, and for my this is a issue because my minecraft isn't perfect with this, I was wondering if one of you peopl could send me a resource pack for Continuity?

(pls I beg I will do anything)

**Comment by PepperCode1** [comment]
Continuity will allow the connected textures in any pack made for OptiFine to work. You can try this pack if you want overlays between blocks.
https://modrinth.com/resourcepack/xalis-enhanced-vanilla
