### ISSUE TITLE
All Text and Sound in game gets Garbled with it???

### ISSUE THREAD

**Issue by CharlieGamer4896** [PepperCode1/Continuity#364]
I have nothing but from the fog, dynamic lights, and performance mods, and it garbles everything. this is a problem i never face.

**Comment by YukiAyase** [comment]
Please send your log file located in **.minecraft/logs**, filename is **"latest"**

**Comment by CharlieGamer4896** [comment]
i found the issue, sorry for not responding, i got busy.
i was using the wrong versions of the mods, and once i downgraded or upgraded (idr which) it was fixed.
