### ISSUE TITLE
It crashes in minecraft 1.20.1 (Fabric, Beta 4)

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [PepperCode1/Continuity#369]
It crashes when trying to load a world with some other mods, here is the crash report, when I delete this mods it loads normally.
[crash-2024-02-10_15.41.05-client.txt](https://github.com/PepperCode1/Continuity/files/14230193/crash-2024-02-10_15.41.05-client.txt)

**Comment by YukiAyase** [comment]
# Update your mods

I highly recommend checking updates for all your mods

If for some reason you can't/refuse to update, downgrade Fabric API to 0.88.1

**Comment by PepperCode1** [comment]
Yuki is correct. This is not a Continuity issue.
