### ISSUE TITLE
Crashes at a random moment V1.20.4

### ISSUE THREAD

**Issue by Wintecks** [PepperCode1/Continuity#373]
at any random moment the game just crashes, there are no reasons that could connect these crashes. it can happen when I fly on elytra, swim in water, stand still, open a trunk, in general at random moments. maybe it's related to some other mod, but after removing this mod everything started to work stably
PS
for some reason the mod does not perform its functions

**Comment by YukiAyase** [comment]
Please provide your log file found in **.minecraft/logs**, the filename is **"latest"**

**Comment by Wintecks** [comment]
пт, 16 лют. 2024 р. о 20:46 Yuki ***@***.***> пише:

**Comment by Wintecks** [comment]
I definitely don't know if these are the exact logs

пт, 16 лют. 2024 р. о 23:11 Wintecks ***@***.***> пише:

**Comment by YukiAyase** [comment]
It seems that you were not able to attach the log file

**Comment by Wintecks** [comment]
[2024-02-16-1.log.gz](https://github.com/PepperCode1/Continuity/files/14318344/2024-02-16-1.log.gz)
[2024-02-16-2.log.gz](https://github.com/PepperCode1/Continuity/files/14318345/2024-02-16-2.log.gz)

**Comment by YukiAyase** [comment]
According to the logs, you don't even have Continuiy installed
