### ISSUE TITLE
Glass Panes still rendering bottom of panes when connected

### ISSUE THREAD

**Issue by ZinGBear1** [PepperCode1/Continuity#374]
Glass panes are connecting textures horizontally but I am still able to see the top/bottom textures of the panes when they are stacked vertically.
![2024-02-16_18 48 16](https://github.com/PepperCode1/Continuity/assets/160294306/e558e382-42ed-4b72-9653-65b6dada9859)

**Comment by YukiAyase** [comment]
Have you made sure to enable the Glass Pane Culling Fix?
![image](https://github.com/PepperCode1/Continuity/assets/64414315/c3754da4-73ab-46b0-ac0e-6b27f383cd5e)

**Comment by ZinGBear1** [comment]
Thank you! That did it, probably should have given that a try before posting an issue.
