### ISSUE TITLE
Minecraft:continuity_reserved 

### ISSUE THREAD

**Issue by Krimatoria** [PepperCode1/Continuity#375]
I do not know if this applies to your fashion or not. But I have this error, and the only mod in the forge with this name is yours. 
But it's for Fabric. And I play Forge.

[19Feb2024 00:14:24.365] [Worker-ResourceReload-10/ERROR] [ModernFix/]: Using missing texture, unable to load minecraft:continuity_reserved/000004f7

**Comment by PepperCode1** [comment]
This line almost certainly means that one of your resource packs has incorrectly configured connected textures. As long as everything works, you can ignore this. If you see missing textures, report it to the resource pack that seemingly causes it.

**Comment by Krimatoria** [comment]
Thanks)
