### ISSUE TITLE
Default Connected Textures texture pack breaks Sodium custom biome blend

### ISSUE THREAD

**Issue by KronosVoid** [PepperCode1/Continuity#376]
If you activate the Default Connected Textures texture pack while using Sodium, Sodium's custom biome blend breaks and the game instead uses the default vanilla one. I don't know if this is an issue on your side, if it isn't, I'll report it to the Sodium devs as well.

Mods used:
- continuity-3.0.0-beta.4+1.20.2
- fabric-api-0.96.3+1.20.4
- indium-1.0.30+mc1.20.4
- sodium-fabric-0.5.8+mc1.20.4

Vanilla/Broken Sodium biome blend:
![2024-02-19_15 58 09](https://github.com/PepperCode1/Continuity/assets/89265861/72d94492-fde9-42a1-9b6a-9d00f86ef681)

Custom Sodium biome blend:
![2024-02-19_16 04 16](https://github.com/PepperCode1/Continuity/assets/89265861/cdda2ca6-afad-4402-9e9b-4ddc4208fe96)

**Comment by PepperCode1** [comment]
It's an Indium issue. It may not be worth reporting as Sodium will soon include a native FRAPI implementation that does not have the issue.

**Comment by KronosVoid** [comment]
Thank you for the quick answer, I've heard about Sodium's future FRAPI implementation and as it is just a small issue, I won't be reporting it to them.
