### ISSUE TITLE
Having Trouble Getting Continuity To Work

### ISSUE THREAD

**Issue by august18429** [PepperCode1/Continuity#377]
I've been through everything I could find for getting Continuity to work but nothing has worked
![Capture](https://github.com/PepperCode1/Continuity/assets/160556482/9000545c-a079-4654-89f7-3f44871c79af)
![Capture1](https://github.com/PepperCode1/Continuity/assets/160556482/055009ad-62dc-4e23-88e5-197a7071e5fc)
![2024-02-19_19 19 41](https://github.com/PepperCode1/Continuity/assets/160556482/16cf7b82-9e38-481c-88d0-181f875d017a)

**Comment by YukiAyase** [comment]
# Update [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4), [Sodium](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.8) and [Iris](https://modrinth.com/mod/iris/version/1.6.17+1.20.1)

**Comment by MeszarosGeri** [comment]
I have the same problem, although I think I have the newest version of mods installed.
![continuity](https://github.com/PepperCode1/Continuity/assets/96839789/c3f2b417-bbb8-474a-9ca9-bf7d838ba915)
