### ISSUE TITLE
Continuity Default Connected Textures Makes Everything invisible.

### ISSUE THREAD

**Issue by NemNem13** [PepperCode1/Continuity#378]
When trying to use the Default Texture that comes with the Continuity mod instead of making the connected textures all blocks just turn completely invisible. 
What might be causing this? How can it be fixed?

**Comment by YukiAyase** [comment]
Please provide your log file located in **.minecraft/logs**, filename is **"latest"**

**Comment by NemNem13** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/14359324/latest.log)

**Comment by YukiAyase** [comment]
# Update [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4), [Sodium](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.8) and [Iris](https://modrinth.com/mod/iris/version/1.6.17+1.20.1) 

Make sure to not forget to update any other mods that depends on them if you have any

**Comment by NemNem13** [comment]
Thank you, that fixed the issue.
