### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by ZmanTheFirst** [PepperCode1/Continuity#379]
I'm having an problem were all my blocks turn invisible any help would be appreciated.

![2024-02-23_02 19 23](https://github.com/PepperCode1/Continuity/assets/161009718/3aeedad1-0dca-4af1-b728-eb9cbfe676ea)
 
![Screenshot 2024-02-23 030201](https://github.com/PepperCode1/Continuity/assets/161009718/9d38bff7-8633-4d87-b62d-c115a8ee1383)

**Comment by YukiAyase** [comment]
# Update [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4), [Sodium](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.8) and [Iris](https://modrinth.com/mod/iris/version/1.6.17+1.20.1)
