### ISSUE TITLE
Not working in 1.20.4

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#380]
EDIT: maybe i'm stupid, does this mod include grass/snow textures? because that's what isn't working for me.

same as the other similar issues, but Indium is installed and (just to be sure) i even updated the pack.mcmeta files. no luck.
[latest.log](https://github.com/PepperCode1/Continuity/files/14390372/latest.log)

**Comment by YukiAyase** [comment]
I'm sorry but we will not be able to give you support
**Please ensure that you're using either the official Minecraft launcher or any other launchers like Prism Launcher, Forge Launcher, etc. with an official Microsoft account**
