### ISSUE TITLE
Unable to find the resource package included in mod

### ISSUE THREAD

**Issue by wobushibaobao** [PepperCode1/Continuity#381]
Hello, I have tried many methods, but I am unable to find the resource package for glass peeling repair in the resource package interface, which has been bothering me for a long time.（This is the integration pack and resource pack I played with）
![6{0}_5ZDLB24POY93NP24U1](https://github.com/PepperCode1/Continuity/assets/161111904/fbc5bc4a-3cc1-4349-ab1f-10878a0f92d8)
![98A } 3SW`8U487MA8BF}HI](https://github.com/PepperCode1/Continuity/assets/161111904/89fc3901-c011-4c9b-9cb3-52469d6077f0)

**Comment by wobushibaobao** [comment]
![) @NF(SOY}B{1P%)%) AR~Y](https://github.com/PepperCode1/Continuity/assets/161111904/10476d40-a47c-4a5a-906e-4afccb81e76c)
![BOMI$Y)MU)LJCR_~)1IPQLN](https://github.com/PepperCode1/Continuity/assets/161111904/48bc4495-3125-4398-a7ef-c88d059a6c02)
The mod and front-end mod are both installed and there are no errors. The mod can be used normally, but the problem lies in the inability to generate resource packages and gaps in the upper and lower layers of the glass panel

**Comment by wobushibaobao** [comment]
![Uploading 0)2KT$G@]C)FW42INJL%XFS.png…]()

**Comment by wobushibaobao** [comment]
![0)2KT$G@ C)FW42INJL%XFS](https://github.com/PepperCode1/Continuity/assets/161111904/9579c0e2-ed22-4ca8-8fb7-ac4cc66402b8)

**Comment by YukiAyase** [comment]
For some reason BetterMC hides Continuity's resource packs and the author missed enabling the glass pane fix

To show Continuity's resource packs you will have to:
1.) Go into **Better MC [FABRIC] - BMC1\minecraft\config** (or whatever your launcher named the instance)
2.) Locate and open the file named **resourcepackoverrides**
3.) Once you've opened the file using notepad, look for the lines that says:

"continuity/default": {
      "hidden": true
}

And

"continuity/glass_pane_culling_fix": {
      "hidden": true
    }

4.) Change the line "hidden": true to **"hidden": false**, save it and launch the game

If done successfully you will now be able to see Continuity's resource packs in the menu

EDIT: This should really be reported to the BetterMC author instead

**Comment by wobushibaobao** [comment]
Thank you so much. You're such a genius. I love you
