### ISSUE TITLE
Randomly crashes when rendering entities/blockentities (1.20.4)

### ISSUE THREAD

**Issue by ryakgn** [PepperCode1/Continuity#382]
[crash-2024-02-14_16.37.01-client.txt](https://github.com/PepperCode1/Continuity/files/14395234/crash-2024-02-14_16.37.01-client.txt)
[crash-2024-02-14_16.54.11-client.txt](https://github.com/PepperCode1/Continuity/files/14395235/crash-2024-02-14_16.54.11-client.txt)
[crash-2024-02-19_14.03.05-client.txt](https://github.com/PepperCode1/Continuity/files/14395236/crash-2024-02-19_14.03.05-client.txt)

**Comment by YukiAyase** [comment]
# Install [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107
