### ISSUE TITLE
Continuity not showing up in in-game resource pack folder

### ISSUE THREAD

**Issue by Phononno** [PepperCode1/Continuity#384]
I'm trying to use "continuity-3.0.0-beta.4+1.20.1" with "fabric-loader-0.15.7-1.20.1", yet when I start up the game with the continuity files in the resource pack folder it does not appear? I'm assuming something I am doing is the issue, but I still don't know what it is I am doing that's preventing it's usage. I am also using "fabric-api-0.91.0+1.20.1", "indium-1.0.27+mc1.20.1", "iris-mc1.20.1-1.6.10", "sodium-fabric-mc1.20.1-0.5.3", and "ComplementaryShaders_v4.7.2", if that helps.

**Comment by YukiAyase** [comment]
You put Continuity inside the mods folder, not the resource pack folder

**Comment by Phononno** [comment]
> You put Continuity inside the mods folder, not the resource pack folder

It's been in my resource pack folder, but it still does not appear.

**Comment by Timolino456** [comment]
No, Continuity is a **mod** that allows resourcepacks with connected textures to work, it is **not** a resource pack. You have to put it in the mods folder for it work.

**Comment by Phononno** [comment]
> No, Continuity is a **mod** that allows resourcepacks with connected textures to work, it is **not** a resource pack. You have to put it in the mods folder for it work.
Oh my goodness I am dumb...Is there a common resource pack with connected textures that I can use?

**Comment by YukiAyase** [comment]
> Oh my goodness I am dumb...Is there a common resource pack with connected textures that I can use?

Best one I recommend is [xali's Enhanced Vanilla](https://modrinth.com/resourcepack/xalis-enhanced-vanilla)

EDIT: **Make sure you have Continuity in the MODS folder and have its resource pack enabled as well or else it won't work**
