### ISSUE TITLE
i can't make it work 1.20.4

### ISSUE THREAD

**Issue by mira-roza** [PepperCode1/Continuity#385]
i have installed https://modrinth.com/mod/iris/version/1.6.17+1.20.4, https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4,
https://modrinth.com/mod/sodium/version/mc1.20.4-0.5.8, and https://modrinth.com/mod/continuity/version/3.0.0-beta.4+1.20.2
i have that:
![image](https://github.com/PepperCode1/Continuity/assets/47930050/12c7bf8c-2a90-4d83-82d4-2440ab394b30)
here is my latest log file:
[latest.log](https://github.com/PepperCode1/Continuity/files/14440866/latest.log)

Thanks you for helping me

**Comment by YukiAyase** [comment]
Please attach the log file itself instead of copy and pasting the contents of it

**Comment by mira-roza** [comment]
i did

**Comment by YukiAyase** [comment]
I've just tested it out
This is the first time I've ever used Lunar Client and found the problem
**Please do also install the latest version of Fabric API in .lunarclient\offline\multiver\mods\fabric-1.20.4**

**Comment by mira-roza** [comment]
thanks you. I m sorry they said that i don't need it and didn't try 😥

**Comment by osafaimal** [comment]
still don't work
