### ISSUE TITLE
Water artefacts on chunk borders

### ISSUE THREAD

**Issue by lostallmymoney** [PepperCode1/Continuity#386]
Installed mods : Sodium and more...
![2024-03-01_16 55 46](https://github.com/PepperCode1/Continuity/assets/6634309/1226afc6-3ab2-4c57-ba64-b4d1227e9400)

**Comment by YukiAyase** [comment]
## This is not a Continuity issue

It is a Sodium issue and will be fixed soon™
https://github.com/CaffeineMC/sodium-fabric/issues/38
