### ISSUE TITLE
Glass not connecting with HardTop Vanillaccurate enabled

### ISSUE THREAD

**Issue by Entropy159** [PepperCode1/Continuity#387]
I am trying to get connected glass. That's the whole reason I got the mod. It works just fine when I disable HardTop Vanillaccurate, but when I add it to the resourcepacks the glass doesn't connect, even when I load it under the built-in continuity resource packs.
My log: https://pastebin.com/7V1P7yuZ
If you need more info, I'm happy to provide.

**Comment by PepperCode1** [comment]
Use https://vanillaccurate.space/2021/04/02/vanillaccurate_ctm/. Vanillaccurate likely replaces the glass textures so Continuity's default pack doesn't do anything.

**Comment by Entropy159** [comment]
The download links are broken on that site. Is there anywhere else I could get it?

**Comment by Entropy159** [comment]
I fixed it by deleting the glass texture from Vanillaccurate - it just is an upscaled version anyway with no PBR whatsoever.
