### ISSUE TITLE
[FR] Prompt user to install indium when sodium is present

### ISSUE THREAD

**Issue by Blue-Beaker** [PepperCode1/Continuity#39]
If you install this mod with sodium but no indium, it just doesn't do anything. The user need to install indium for this mod to work with sodium, but there is no warnings about it. Please add the feature to prompt the user to install indium under this circumstance.

**Comment by TheNukeLore** [comment]
I believe this was not wanting to be added as sodium plans to add frapi or frex support on their end, so indium won’t be needed in the future

**Comment by PepperCode1** [comment]
I added such a prompt to the CurseForge and Modrinth pages some time ago, but I will not add one as an in-game screen.
