### ISSUE TITLE
CTM biomes rule not working

### ISSUE THREAD

**Issue by Zemtox** [PepperCode1/Continuity#390]
When applying the optional «biomes=» rule for where to display certain textures & models it fails to load them at all. All other features are working fine. 

I tested multiple different instances that have been confirmed to work on Optifine 1.20.1. 

I’m currently running on Fabric 1.20.1 with Continuity 3.0.0-beta.4+1.20.1 (ink Fabric API)

**Comment by PepperCode1** [comment]
Send your mod list.

**Comment by Zemtox** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/14619271/latest.log)

Here is my latest log file

**Comment by PepperCode1** [comment]
Biome predicates in beta 4 for 1.20.1 do not work when using Sodium older than version 0.5. Update Sodium or remove it. Older versions of Continuity may work, but it is not recommended to use them and they are not supported, meaning issues with them will not be investigated or fixed.

**Comment by Zemtox** [comment]
Right, I'll give it a try. Thanks for the great mod and quick reply!
