### ISSUE TITLE
Does not render connected textures (1.20.4)

### ISSUE THREAD

**Issue by katawful** [PepperCode1/Continuity#392]
I have installed Continuity and its required mods via PrismLauncher and activated the supplied resource packs. No textures connect. Also tested with compatible resource packs like Spectral which still do not connect

Log: https://mclo.gs/eHx1NYR

**Comment by YukiAyase** [comment]
Have you taken a look if glass, sandstone and bookshelves connect?

**Comment by NolanHewitt** [comment]
Can confirm this on 1.20.1, the built in resource pack doesn't work. Tested glass sandstone, and bookshelves. Other resource packs do work with connected textures, it seems its just the built in one here that doesn't work.

**Comment by PepperCode1** [comment]
The default pack disables its connected textures if the vanilla textures were replaced. This is intended. If the vanilla textures look the same, then you have another pack that is replacing them unnecessarily.
