### ISSUE TITLE
Emissive trim textures don't work

### ISSUE THREAD

**Issue by deftesthawk** [PepperCode1/Continuity#393]
I have used this mod to get emissive ores successfully, I even created some emissive ore textures for mods that don't have any uploaded anywhere. But when I've tried using emissive trim resource packs they don't work at all. I've looked at the files within and I don't see why they shouldn't work. This is one of the resource packs I tried but doesn't work: https://www.curseforge.com/minecraft/texture-packs/xxvis-shiny-armor-trims

**Comment by PepperCode1** [comment]
From the README:
> Continuity is a Fabric mod that allows resource packs that use the OptiFine connected textures format, OptiFine emissive textures format (**only for blocks and item models**), or OptiFine custom block layers format to work without OptiFine.

The mod Entity Texture Features provides OptiFine-format emissive textures for everything else.
