### ISSUE TITLE
Crash when falling blocks

### ISSUE THREAD

**Issue by Epik0rangutan** [PepperCode1/Continuity#395]
So recently I was trying my modpack with the Continuity mod 3.0.0-beta.4+1.20.1 fabric when suddenly I wanted to place a gravel block and when it started falling it crashed. I wasted hours trying to figure out what's going on and then I found out that the issue was with Continuity(I found the crash report file). I hope the creator will fix this.

**Comment by YukiAyase** [comment]
This is most likely a duplicate of #107 
Install [Indium](https://modrinth.com/mod/indium)

**Comment by Epik0rangutan** [comment]
> This is most likely a duplicate of #107 Install [Indium](https://modrinth.com/mod/indium)

Thank you really much, I actually did forgot to install it
