### ISSUE TITLE
(ctm overlay) texture overlapping depending on the lightning

### ISSUE THREAD

**Issue by Emox0026** [PepperCode1/Continuity#398]
From what I have tested, it only appears with the dirt block.

Same problem with different ressource packs.

I recorded a video so that it is easier to understand: 

https://github.com/PepperCode1/Continuity/assets/165693546/9844839f-12a9-4e07-b782-95368a80dc66

**Comment by PepperCode1** [comment]
Do you have Sodium installed? If so, test what happens without Sodium and Indium.

**Comment by Emox0026** [comment]
Okay so I tested and the problem seems to come from one of these mods

**Comment by PepperCode1** [comment]
It's probably the same underlying issue as in #292 then. Sodium 0.6.0 should fix it.

**Comment by ItzLucaGER** [comment]
Is it just me or does sodium 0.6.0 not seem to exist?

**Comment by PepperCode1** [comment]
It is not released yet and I did not intend to imply that it is. There is no ETA for when it might be released.

**Comment by PepperCode1** [comment]
Sodium 0.6 has been released for some time now so this issue is resolved.
