### ISSUE TITLE
Errors with Enhanced Block Entities mod

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#40]
https://github.com/FoundationGames/EnhancedBlockEntities/issues/63

Is this something that can be fixed on your side?

**Comment by 1upbyte** [comment]
im using both and i dont have any issues

**Comment by ghost** [comment]
> im using both and i dont have any issues

can you post your latest.log?

**Comment by probablypablito** [comment]
here you go! all that i did was remove some personal info

[latest.log](https://github.com/PepperCode1/Continuity/files/7803831/latest.log)

**Comment by 1upbyte** [comment]
here you go! i did modify it to remove ips / chat messages

[latest.log](https://github.com/PepperCode1/Continuity/files/7803866/latest.log)

**Comment by ghost** [comment]
> here you go! i did modify it to remove ips / chat messages
> 
> [latest.log](https://github.com/PepperCode1/Continuity/files/7803866/latest.log)

You have it too....................... lines 153 to 193

**Comment by 1upbyte** [comment]
oh.. i thought you meant like in game errors.

do they really do anything/matter?

**Comment by ghost** [comment]
> oh.. i thought you meant like in game errors.
> 
> do they really do anything/matter?

I don't know what its affecting but its not good to have 41 lines of STDERR

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/82549089/155604544-19c74743-68fc-4404-a008-15516d125cb9.png)

**Comment by PepperCode1** [comment]
Does this still happen?

**Comment by PepperCode1** [comment]
There have been no updates on this issue for over a year, so I will assume it is resolved. Please open a new issue if this is encountered again.
