### ISSUE TITLE
Uh, where are my conneected texture's?

### ISSUE THREAD

**Issue by Epik0rangutan** [PepperCode1/Continuity#400]
![image](https://github.com/PepperCode1/Continuity/assets/163749224/a7d253d3-06b2-40af-bb25-079c638539e9)

**Comment by YukiAyase** [comment]
If you are using Minecraft's default resource pack, please make sure to enable Continuity's resource packs

**Comment by Epik0rangutan** [comment]
> Contributor

If you mean these I actually did enable them but it still doesn't work
![image](https://github.com/PepperCode1/Continuity/assets/163749224/fef4a891-8ef0-4142-b252-69dd7e25d760)

**Comment by YukiAyase** [comment]
Just checked, I'm not sure if its intentional but cut sandstone only connects horizontally

**Comment by Epik0rangutan** [comment]
> Just checked, I'm not sure if its intentional but cut sandstone only connects horizontally

I just looked up some videos about this mod. I thing sandstone should also connect vertically.

**Comment by PepperCode1** [comment]
It is intentional.
