### ISSUE TITLE
Game completely freezes upon going in a world.

### ISSUE THREAD

**Issue by Akeoott** [PepperCode1/Continuity#401]
Every time i go in a world the game freezes and i need to Alt+F4. There is no crash log.

Version: 1.20.2-FB
Client: Feather
Mods: Starlight, Entity Culling, 3D skin layers, Cloth Config API, Iris Shiders, Sodium, Mod Menu, Continuity.
Shaders: None in use
Texture Pack: None in use

Mod Versions
3D skin layers (1.6.2)
Cloth Config (API (12.0.119+fabric)
Iris Shiders (1.6.14+1.20.2)
Sodium (mc1.20.2-0.5.5)
Mod Menu (8.0.1)
Continuity (3.0.0-Beta.4+1.20.2)

**Comment by YukiAyase** [comment]
We can't really determine anything without any logs
But from the mods list you've provided, you're missing Indium
[Indium](https://modrinth.com/mod/indium/versions) is needed if you're using Sodium

Though please do note that most of the time I've seen Feather client getting mentioned in the Sodium Discord, they advise people to not use it so do be prepared for something else being broken if installing Indium fixes your crashing problem

Edit: Duplicate of #107

**Comment by Akeoott** [comment]
I cant use Indium because it always says incopatible version.

`Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.5 with version 0.5.5 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.30+mc1.20.4 with any version that is compatible with:
		 - sodium, version 0.5.5
More details:
	 - Mod 'Indium' (indium) 1.0.30+mc1.20.4 requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
`

**Comment by YukiAyase** [comment]
> I cant use Indium because it always says incopatible version.
> 
> `Incompatible mods found! net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other! A potential solution has been determined, this may resolve your problem: - Replace mod 'Sodium' (sodium) 0.5.5 with version 0.5.5 that is compatible with: - indium, any version - Replace mod 'Indium' (indium) 1.0.30+mc1.20.4 with any version that is compatible with: - sodium, version 0.5.5 More details: - Mod 'Indium' (indium) 1.0.30+mc1.20.4 requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.5! at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) `

You're downloading the latest version of Indium which only supports Sodium 0.5.8

The version you have is Sodium 0.5.5 and the Indium version you'd want is [Indium 1.0.28](https://modrinth.com/mod/indium/version/1.0.28+mc1.20.4)

**Comment by Akeoott** [comment]
Thanks for the help. Everything works fine now.
