### ISSUE TITLE
Built-In Connected Textures Hidden by Iris

### ISSUE THREAD

**Issue by Jakookie** [PepperCode1/Continuity#406]
I am using Iris Fabric Loader for Minecraft. When I use that to load my game, the built-in resource packs are hidden and unapplied. I tried to switch to just the fabric loader which worked but I had no shaders for my game. How do I fix this?

**Comment by PepperCode1** [comment]
You can install Iris as a mod but I don't think this should happen and regardless it is not something Continuity can change or fix. Continuity's resource packs are always supposed to be visible — if they are not, then there is nothing I can do.
