### ISSUE TITLE
I cannot make it work on 1.20.4

### ISSUE THREAD

**Issue by Tairraos** [PepperCode1/Continuity#408]
MC 1.20.4
continuity-3.0.0-beta.4+1.20.2
indium-1.0.30+mc1.20.4.jar
sodium-fabric-0.5.8+mc1.20.4.jar

![image](https://github.com/PepperCode1/Continuity/assets/185069/73240294-5977-41f6-a2f1-374e97a22b6c)

**Comment by YukiAyase** [comment]
Uhhh, enable Continuity's resource packs?

**Comment by Tairraos** [comment]
enabled, no error but glass still not connected



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 28, 2024 02:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PepperCode1/Continuity] I cannot make it work on 1.20.4 (Issue#408)




 
Uhhh, enable Continuity's resource packs?

**Comment by YukiAyase** [comment]
Try only enabling Continuity's resource pack and see if that works
If yes, one of the resource pack/s you're using does not have connected glass

**Comment by Tairraos** [comment]
Still not work, i put the continuity at the top, the rest 2 packs are unremovable.

![image](https://github.com/PepperCode1/Continuity/assets/185069/3905ebb7-a9aa-4902-832b-990824b487c3)
![image](https://github.com/PepperCode1/Continuity/assets/185069/c222f1e2-67ff-4015-babe-544007ebc942)
![image](https://github.com/PepperCode1/Continuity/assets/185069/b97d0034-458b-4a34-af96-548ea6b09494)

**Comment by Tairraos** [comment]
What's your view at the 1.20.4 of this resource pack setting page? incompatible but work or no this warning?

**Comment by YukiAyase** [comment]
> Still not work, i put the continuity at the top, the rest 2 packs are unremovable.
> 
>  ![image](https://private-user-images.githubusercontent.com/185069/326229970-b97d0034-458b-4a34-af96-548ea6b09494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTI0MTcsIm5iZiI6MTcxNDI5MjExNywicGF0aCI6Ii8xODUwNjkvMzI2MjI5OTcwLWI5N2QwMDM0LTQ1OGItNGEzNC1hZjk2LTU0OGVhNmIwOTQ5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwODE1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWJiZDhiY2QzMjQ2MGYwYjJkMzYxN2EwNjY2MGZjZmMxMTI3MDg2ODQ5NWE1YjRhMDQ4MGU2YTFiODM4YzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jv6d-bFQ7Cns2Z7A0yKMtGghc9cwt8fUMfwbxKyuTQM)

You need to enable "Default Connected Textures" as well to actually have connected textures
Like this
![image](https://github.com/PepperCode1/Continuity/assets/64414315/6ba491e3-ba99-40ab-9667-44790fa81ba4)

**Comment by Tairraos** [comment]
Oh! it works... my fault! i just see the thumbnail images, default looks like default block by block, the culling looks like connected. !-_- 

Problem solved, thank you very much Yuki.
