### ISSUE TITLE
Continuity not working with Sodium / Iris Shaders

### ISSUE THREAD

**Issue by Agoreon** [PepperCode1/Continuity#409]
Hi guys,
im trying to install Continuity 1.20.5 on fabric. Without Sodium everything works but for some reason after using Sodium my texturepack (which is too old but without Sodium just works) cant load and Continuity too. Is there any way to use Sodium with this cause I need it for Iris Shaders?

**Comment by YukiAyase** [comment]
Indium has not yet updated to support 1.20.5
*Currently, Indium is ONLY required when Sodium is installed*

**Comment by Agoreon** [comment]
so is there nothing i can do to make it work in 1.20.5?

**Comment by YukiAyase** [comment]
Temporarily not using Sodium and Iris

**Comment by ItsRodrigoAl** [comment]
Well actually you can use Indium on 1.20.5 with the 1.20.4 version, but yeah thats the whole point, you need Indium if you use Sodium (I noticed the same thing like 1h ago)
