### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by kabuokis** [PepperCode1/Continuity#410]
Game will crash if you place gravity effected block like sand, gravel and others. i have like 30 mods wen Continuity is added game crashed.

Minecraft version: 1.20.5 fabric 0.15.10
mod list:
appleskin-fabric-mc1.20.5-3.0.0
c2me-fabric-mc1.20.5-0.2.0+alpha.11.89
chat_heads-0.11.0-fabric-1.20.5
Clumps-fabric-1.20.5-16.0.0.1
collective-1.20.5-7.54
continuity-3.0.0-beta.4+1.20.2 -
doubledoors-1.20.5-5.5
dynamic-fps-3.4.3+minecraft-1.20.5-fabric
entity_texture_features_fabric_1.20.5-6.0.1
entityculling-fabric-1.6.4-mc1.20.5
fabric-api-0.97.8+1.20.5
fabric-language-kotlin-1.10.19+kotlin.1.9.23
fancymenu_fabric_3.1.6_MC_1.20.5
ferritecore-6.1.0-fabric
FpsReducer2-fabric-1.20.5-2.8
freecam-fabric-modrinth-1.2.4+mc1.20.5
IAS-Fabric-1.20.5-9.0.0-beta.1
ImmediatelyFast-Fabric-1.2.12+1.20.5
InvMove-1.20-0.8.6-Fabric
iris-1.7.0+mc1.20.5
konkrete_fabric_1.9.4_MC_1.20.5
melody_fabric_1.0.6_MC_1.20.5
modernfix-fabric-5.17.0+mc1.20.5
modmenu-10.0.0-beta.1
moreculling-1.20.5-0.25.0
notenoughanimations-fabric-1.7.2-mc1.20.5
replantingcrops-1.20.5-5.3
Resourcify (1.20.5+-fabric)-1.3.5
rrls-4.0.4+mc1.20.5-fabric
sodium-extra-0.5.4+mc1.20.5-build.117
sodium-fabric-0.5.8+mc1.20.5
spark-1.10.64-fabric
ViaFabric-0.4.14+67-main
vmp-fabric-mc1.20.5-0.2.0+beta.7.151-all
WI-Zoom-1.5-MC1.20.5

**Comment by PepperCode1** [comment]
You are using Sodium 0.5.8 and you do not have Indium.
