### ISSUE TITLE
Minecraft crashes when a piston is extended (1.20.6)

### ISSUE THREAD

**Issue by SkyLeveI** [PepperCode1/Continuity#411]
The title is self explanatory. The error it gives out basically is saying that the item couldn't render because somewhere the rendering is null. I tried this on 1.20.4, and it was working fine. Did pistons receive an update on either 1.20.5 or 1.20.6?

**Comment by YukiAyase** [comment]
> The title is self explanatory. The error it gives out basically is saying that the item couldn't render because somewhere the rendering is null. I tried this on 1.20.4, and it was working fine. Did pistons receive an update on either 1.20.5 or 1.20.6?

Install [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4)
Duplicate of #107

**Comment by SkyLeveI** [comment]
ok

**Comment by YukiAyase** [comment]
Huh
Please send your log file located in **.minecraft/logs**, filename is **"latest"**

**Comment by SkyLeveI** [comment]
indium does not show up in my mod menu since indium does not have 1.20.6 version (but I have it in the mods folder)

**Comment by SkyLeveI** [comment]
nevermind even though indium does not show up in the mod menu it is fixed
