### ISSUE TITLE
Modrinth: Add Indium to dependency list

### ISSUE THREAD

**Issue by programmerlexi** [PepperCode1/Continuity#415]
Please add Indium to the optional dependencies.

**Comment by elybeatmaker** [comment]
This would be very helpful!

**Comment by PepperCode1** [comment]
How would this help?

**Comment by programmerlexi** [comment]
It would allow mod downloaders like ferium to ask if it should also be installed.

**Comment by ShadowRocks2** [comment]
tbf continuity only needs it if sodium is installed

**Comment by jbritain** [comment]
At the very least, I think the mod should display some kind of warning if it detects that Sodium is loaded but Indium isn't.

**Comment by ShadowRocks2** [comment]
> At the very least, I think the mod should display some kind of warning if it detects that Sodium is loaded but Indium isn't.

agreed

**Comment by PepperCode1** [comment]
Sodium 0.6 implements FRAPI, so Indium is no longer necessary.
