### ISSUE TITLE
Continuity glowing ore resource packs not working under Sinytra Connector Forge environment

### ISSUE THREAD

**Issue by FullMetalMaster** [PepperCode1/Continuity#418]
using 
create 
Embeddium
Continuity
Cobblemon 
All Glowing + (ores, mobs and w/ more supports)
and Cobblemon Emissive Ores

the mod seems to load without issue but does not function as intended

logs: https://pastebin.com/

**Comment by PepperCode1** [comment]
Issues when using Connector should be reported to Connector, not Continuity.

**Comment by FullMetalMaster** [comment]
did so
