### ISSUE TITLE
There are gaps in between the textures when (im guessing) stacking glass/placing it behind eachother.

### ISSUE THREAD

**Issue by Njit2098** [PepperCode1/Continuity#419]
![2024-05-23_15 25 00_4K](https://github.com/PepperCode1/Continuity/assets/167520200/4b43b18f-f89a-489a-8801-f2eff489339f)
This is my best example, on smallers scales I just looked over this. But now this is pretty annoying

**Comment by PepperCode1** [comment]
CaffeineMC/sodium-fabric#38; not a Continuity issue.

**Comment by Njit2098** [comment]
Oops, sorry! I'll try to find another thing that could be causing this.
