### ISSUE TITLE
everything is invisible when i use continuity 

### ISSUE THREAD

**Issue by Trademark0317** [PepperCode1/Continuity#423]
![2024-06-05_15 28 53](https://github.com/PepperCode1/Continuity/assets/171864272/f321749c-f06c-4c41-9c61-5dbb2fbc0fbd)
![image_2024-06-05_153453206](https://github.com/PepperCode1/Continuity/assets/171864272/5fbb92f4-a5d2-44cf-9a73-d17cc3499d74)
sorry if this is an issue thats already been resolved, i havent seen anyone specifically talk about it. 
this only happens when i load the texture packs, im not good at this stuff so im entirely clueless as to what the issue could be lol

**Comment by YukiAyase** [comment]
Update [Sodium](https://modrinth.com/mod/sodium/versions)
