### ISSUE TITLE
Warden and Turtle models are broken with Patrix texturepack.

### ISSUE THREAD

**Issue by frosthuuund** [PepperCode1/Continuity#424]
Optifine:
![optifine](https://github.com/PepperCode1/Continuity/assets/168279382/4a072e66-37f2-465b-860e-9c2c76de1496)

Continuity:
![continuity](https://github.com/PepperCode1/Continuity/assets/168279382/373bc53e-a50e-45a9-9332-450538f469de)

Mod List:
```
Indium [1.0.30+mc1.20.4]
Sodium [0.5.8+mc1.20.4]
Sodium Extra [0.5.4+mc1.20.4-build.116]
Continuity [3.0.0-beta.5+1.20.2]
BetterF3 [9.0.2]
Mod Menu [9.2.0-beta.2]
Cloth Config v13 [13.0.121]
Fabric API [0.97.1+1.20.4]
Iris [1.7.0+mc1.20.4]
Reese's Sodium Options [1.7.2+mc1.20.4-build.102]
```

Resourcepack load order:
![image](https://github.com/PepperCode1/Continuity/assets/168279382/2daff837-2fd0-41a4-94d3-63dd9e18f81c)

Patrix x32 is also broken

**Comment by sasquott** [comment]
It’s not a Continuity issue, you don’t have custom models mod for Fabric, you need to add EMF & ETF mods, required mods are in Patrix discord, and also on the Modrinth & Curseforge pages
