### ISSUE TITLE
Is there any difference between these two documents?

### ISSUE THREAD

**Issue by Huuuhuuhu** [PepperCode1/Continuity#426]
![新建 BMP 图像](https://github.com/PepperCode1/Continuity/assets/93205246/93f1b50c-11c2-433a-9cb9-1d97e1b5dead)
Is there any difference between these two documents? Which should I use? (Or should they be used together?)

**Comment by PepperCode1** [comment]
Only use the jar without "sources". The jar with "sources" is not a mod and contains the uncompiled source code.
