### ISSUE TITLE
Crash in 1.21 beta.5 due to (presumably) gravity block or some form of conflict?

### ISSUE THREAD

**Issue by Ynaught** [PepperCode1/Continuity#427]
This is the crash report. Apologies, I'm not very good at reading them:

> ---- Minecraft Crash Report ----
> // Shall we play a game?
> 
> Time: 2024-06-14 00:02:43
> Description: Rendering entity in world
> 
> java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
> 	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
> 	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
> 	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
> 	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
> 	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
> 	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
> 	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
> 	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
> 	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
> 	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
> 	at net.minecraft.class_901.handler$zdp000$continuity$beforeRenderModel(class_901.java:515)
> 	at net.minecraft.class_901.method_3965(class_901.java:45)
> 	at net.minecraft.class_901.method_3936(class_901.java:17)
> 	at net.minecraft.class_898.method_3954(class_898.java:148)
> 	at net.minecraft.class_761.method_22977(class_761.java:1312)
> 	at net.minecraft.class_761.method_22710(class_761.java:1071)
> 	at net.minecraft.class_757.method_3188(class_757.java:1087)
> 	at net.minecraft.class_757.method_3192(class_757.java:850)
> 	at net.minecraft.class_310.method_1523(class_310.java:1285)
> 	at net.minecraft.class_310.method_1514(class_310.java:882)
> 	at net.minecraft.client.main.Main.main(Main.java:256)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
> 	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
> 	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
> 	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
> 	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
> 	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
> 	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
> 	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
> 	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
> 	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
> 	at net.minecraft.class_901.handler$zdp000$continuity$beforeRenderModel(class_901.java:515)
> 	at net.minecraft.class_901.method_3965(class_901.java:45)
> 	at net.minecraft.class_901.method_3936(class_901.java:17)
> 	at net.minecraft.class_898.method_3954(class_898.java:148)
> 	at net.minecraft.class_761.method_22977(class_761.java:1312)
> 	at net.minecraft.class_761.method_22710(class_761.java:1071)
> 	at net.minecraft.class_757.method_3188(class_757.java:1087)
> 
> -- Entity being rendered --
> Details:
> 	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
> 	Entity ID: 23161
> 	Entity Name: Falling Gravel
> 	Entity's Exact location: -219503.50, 15.00, -999190.50
> 	Entity's Block location: World: (-219504,15,-999191), Section: (at 0,15,9 in -13719,0,-62450; chunk contains blocks -219504,-64,-999200 to -219489,319,-999185), Region: (-429,-1952; contains chunks -13728,-62464 to -13697,-62433, blocks -219648,-64,-999424 to -219137,319,-998913)
> 	Entity's Momentum: 0.00, 0.00, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> 	Immitating BlockState: Block{minecraft:gravel}
> Stacktrace:
> 	at net.minecraft.class_898.method_3954(class_898.java:148)
> 	at net.minecraft.class_761.method_22977(class_761.java:1312)
> 	at net.minecraft.class_761.method_22710(class_761.java:1071)
> 	at net.minecraft.class_757.method_3188(class_757.java:1087)
> 	at net.minecraft.class_757.method_3192(class_757.java:850)
> 	at net.minecraft.class_310.method_1523(class_310.java:1285)
> 	at net.minecraft.class_310.method_1514(class_310.java:882)
> 	at net.minecraft.client.main.Main.main(Main.java:256)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- Renderer details --
> Details:
> 	Assigned renderer: net.minecraft.class_901@50ea9225
> 	Location: 1.95,-0.62,-0.02 - World: (1,-1,-1), Section: (at 1,15,15 in 0,-1,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
> 	Rotation: 0.0
> 	Delta: 0.36009797
> Stacktrace:
> 	at net.minecraft.class_898.method_3954(class_898.java:148)
> 	at net.minecraft.class_761.method_22977(class_761.java:1312)
> 	at net.minecraft.class_761.method_22710(class_761.java:1071)
> 	at net.minecraft.class_757.method_3188(class_757.java:1087)
> 	at net.minecraft.class_757.method_3192(class_757.java:850)
> 	at net.minecraft.class_310.method_1523(class_310.java:1285)
> 	at net.minecraft.class_310.method_1514(class_310.java:882)
> 	at net.minecraft.client.main.Main.main(Main.java:256)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- Uptime --
> Details:
> 	JVM uptime: 1870.267s
> 	Wall uptime: 1858.135s
> 	High-res time: 1854.114s
> 	Client ticks: 36356 ticks / 1817.800s
> Stacktrace:
> 	at net.minecraft.class_310.method_1587(class_310.java:2501)
> 	at net.minecraft.class_310.method_54580(class_310.java:949)
> 	at net.minecraft.class_310.method_1514(class_310.java:902)
> 	at net.minecraft.client.main.Main.main(Main.java:256)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_746['Noah_Dekka'/9925, l='ClientLevel', x=-219505.45, y=14.00, z=-999190.48]]
> 	Chunk stats: 4096, 1529
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (16,63,1), Section: (at 0,15,1 in 1,3,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 	Level time: 349505 game time, 531380 day time
> 	Server brand: fabric
> 	Server type: Integrated singleplayer server
> 	Tracked entity count: 156
> 
> -- Last reload --
> Details:
> 	Reload number: 2
> 	Reload reason: manual
> 	Finished: Yes
> 	Packs: vanilla, fabric, adorabuild_structures, anvil-too-expensive, armourbundles, blockus, bossbar, bundle_jumble, bundle_scroll, cloth-config, codec-config-api, continuity, copper_golem, customlevelcolour, dyed_bundles, dyed_item_frames, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, grindenchantments, modmenu, presencefootsteps, reacharound, resourcify, smoke_signals, snowpig, snowyleavesplus, sodium, taxfreelevels, terraform-wood-api-v1, tomereader, tramplestopper, trenzalore, useful_brush, yet_another_config_lib_v3, presencefootsteps:default_sound_pack, file/VanillaTweaks_3D.zip, file/VanillaTweaks_GUI.zip, file/VanillaTweaks_Terrain.zip, file/VanillaTweaks_Utility.zip, file/VanillaTweaks_Variant.zip, file/VanillaTweaks_Water.zip, file/VanillaTweaks_Clear.zip, file/VanillaTweaks_Aesthetic.zip, file/ic's Copper Tweaks.zip, continuity:default, continuity:glass_pane_culling_fix, file/CCB+(1.20-1.20.1)+(Bolted Corners) (1).zip
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.21
> 	Minecraft Version ID: 1.21
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 21.0.3, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 3320089792 bytes (3166 MiB) / 4999610368 bytes (4768 MiB) up to 8589934592 bytes (8192 MiB)
> 	CPUs: 16
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 	Microarchitecture: Zen 2
> 	Frequency (GHz): 3.59
> 	Number of physical packages: 1
> 	Number of physical CPUs: 8
> 	Number of logical CPUs: 16
> 	Graphics card #0 name: AMD Radeon RX 5700 XT
> 	Graphics card #0 vendor: Advanced Micro Devices, Inc.
> 	Graphics card #0 VRAM (MiB): 8176.00
> 	Graphics card #0 deviceId: VideoController1
> 	Graphics card #0 versionInfo: 31.0.21031.1005
> 	Memory slot #0 capacity (MiB): 16384.00
> 	Memory slot #0 clockSpeed (GHz): 3.20
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MiB): 16384.00
> 	Memory slot #1 clockSpeed (GHz): 3.20
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MiB): 75736.14
> 	Virtual memory used (MiB): 65143.27
> 	Swap memory total (MiB): 43037.73
> 	Swap memory used (MiB): 7000.89
> 	Space in storage for jna.tmpdir (MiB): available: 630212.81, total: 1953497.00
> 	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 630212.81, total: 1953497.00
> 	Space in storage for io.netty.native.workdir (MiB): available: 630212.81, total: 1953497.00
> 	Space in storage for java.io.tmpdir (MiB): available: 1551732.00, total: 1907082.00
> 	Space in storage for workdir (MiB): available: 630212.81, total: 1953497.00
> 	JVM Flags: 10 total; -Xmx8192M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
> 	Fabric Mods: 
> 		adorabuild_structures: AdoraBuild: Structures 2.6.2
> 		amplified_nether: Amplified Nether 1.2.5
> 		anvil-too-expensive: Anvil Too Expensive 1.3.1
> 		armourbundles: Armour Bundles 1.4.0+1.21
> 		blockus: Blockus 2.9.0+1.21
> 			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
> 		bossbar: Bossbar 1.1
> 		bundle_jumble: Bundle Jumble 1.0.2-mc1.21
> 		bundle_scroll: Bundle Scroll 1.1
> 		cloth-config: Cloth Config v15 15.0.127
> 			cloth-basic-math: cloth-basic-math 0.6.1
> 		collective: Collective 7.61
> 		continents: Continents 1.1.5
> 		continuity: Continuity 3.0.0-beta.5+1.21
> 		copper_golem: Copper Golem 1.8.2+1.21
> 		customlevelcolour: Custom Level Colour 1.0.0+1.21
> 		cyclepaintings: Cycle Paintings 3.5
> 		cycletitlescreensplash: Cycle Title Screen Splash 1.2
> 		despawningeggshatch: Despawning Eggs Hatch 4.3
> 		dismountentity: Dismount Entity 3.2
> 		dyed_bundles: Dyed Bundles 1.0
> 		dyed_item_frames: Dyed Item Frames 1.1
> 		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
> 		fabric-api: Fabric API 0.100.1+1.21
> 			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
> 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
> 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
> 			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
> 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
> 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
> 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
> 			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
> 			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
> 			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
> 			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
> 			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
> 			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
> 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
> 			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
> 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
> 			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
> 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
> 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
> 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
> 			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
> 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
> 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
> 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
> 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
> 			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
> 			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
> 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
> 			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
> 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
> 			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
> 			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
> 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
> 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
> 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
> 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
> 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
> 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
> 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
> 			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
> 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
> 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
> 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
> 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
> 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
> 			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
> 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
> 		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
> 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
> 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
> 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
> 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
> 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
> 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
> 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
> 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
> 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
> 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
> 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
> 		fabricloader: Fabric Loader 0.15.11
> 			mixinextras: MixinExtras 0.3.5
> 		fallingleaves: Falling Leaves 1.16.0
> 		fishontheline: Fish On The Line 3.3
> 		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.3
> 		grindenchantments: Grind Enchantments 3.2.2+1.21-rc1
> 			codec-config-api: Codec config API 2.0.0+1.20.5-rc3
> 		grindstonesharpertools: Grindstone Sharper Tools 3.5
> 		guiclock: GUI Clock 4.5
> 		guicompass: GUI Compass 4.7
> 		java: OpenJDK 64-Bit Server VM 21
> 		keepmysoiltilled: Keep My Soil Tilled 2.2
> 		ksyxis: Ksyxis 1.3.2
> 		maptooltip: Map Tooltip 4.0.0
> 		minecraft: Minecraft 1.21
> 		modmenu: Mod Menu 11.0.0-beta.1
> 		morezombievillagers: More Zombie Villagers 3.5
> 		mr_duplicatable_potterysherds: Duplicatable Pottery Sherds 3.2
> 		mr_heavy_coreduplication: Heavy Core Duplication 1.0
> 		mr_kyb_hallucinate: Hallucinate 1.2.0.21
> 		mr_rich_husk: Rich Husk 1-mcmeta-45_1.21
> 		mr_warping_wonders: Warping Wonders 1.0
> 		netherportalspread: Nether Portal Spread 8.2
> 		nohostilesaroundcampfire: No Hostiles Around Campfire 6.1
> 		nullscape: Nullscape 1.2.6
> 		overworldpiglins: Overworld Piglins 1.4
> 		presencefootsteps: Presence Footsteps 1.10.0+1.21
> 			kirin: Kirin UI 1.19.0+1.21
> 		reacharound: Reacharound 1.2.0
> 		resourcify: Resourcify 1.4.0
> 			universalcraft: UniversalCraft 342
> 		respawningshulkers: Respawning Shulkers 3.8
> 		sculk_expansion_mr: Sculk Expansion 1.3.3
> 		shulkerbox: Advanced Shulkerboxes 1.21-2.0.4
> 		shulkerdropstwo: Shulker Drops Two 3.3
> 		smoke_signals: Smoke Signals 1.1
> 		snowpig: Snow Pig 4.0.2
> 		snowyleavesplus: SnowyLeavesPlus 0.1.11
> 		sodium: Sodium 0.5.9+mc1.21
> 		taxfreelevels: Tax Free Levels 1.3.12
> 		tomereader: TomeReader 0.0.3
> 		tramplestopper: Trample Stopper 6.0.1+mc1.21
> 		trenzalore: Trenzalore 6.0.0
> 		useful_brush: Useful Brush 0.1.2+mc1.21.0
> 		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
> 			com_twelvemonkeys_common_common-image: common-image 3.10.0
> 			com_twelvemonkeys_common_common-io: common-io 3.10.0
> 			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
> 			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
> 			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
> 			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
> 			org_quiltmc_parsers_gson: gson 0.2.1
> 			org_quiltmc_parsers_json: json 0.2.1
> 		zombievillagersfromspawner: Zombie Villagers From Spawner 3.8
> 	Launched Version: 1.21
> 	Launcher name: ATLauncher
> 	Backend library: LWJGL version 3.3.3-snapshot
> 	Backend API: AMD Radeon RX 5700 XT GL version 3.2.0 Core Profile Context 23.9.1.230821, ATI Technologies Inc.
> 	Window size: 1920x1080
> 	GFLW Platform: win32
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: 
> 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
> 	Universe: 400921fb54442d18
> 	Type: Integrated Server (map_client.txt)
> 	Graphics mode: fancy
> 	Render Distance: 20/20 chunks
> 	Resource Packs: vanilla, fabric, adorabuild_structures (incompatible), anvil-too-expensive, armourbundles, blockus, bossbar, bundle_jumble, bundle_scroll, cloth-config, codec-config-api, continuity, copper_golem, customlevelcolour, dyed_bundles, dyed_item_frames, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, grindenchantments, modmenu, presencefootsteps, reacharound, resourcify (incompatible), smoke_signals, snowpig, snowyleavesplus, sodium, taxfreelevels, terraform-wood-api-v1, tomereader, tramplestopper (incompatible), trenzalore (incompatible), useful_brush, yet_another_config_lib_v3 (incompatible), presencefootsteps:default_sound_pack, file/VanillaTweaks_3D.zip, file/VanillaTweaks_GUI.zip, file/VanillaTweaks_Terrain.zip, file/VanillaTweaks_Utility.zip, file/VanillaTweaks_Variant.zip, file/VanillaTweaks_Water.zip, file/VanillaTweaks_Clear.zip, file/VanillaTweaks_Aesthetic.zip, file/ic's Copper Tweaks.zip (incompatible), continuity:default, continuity:glass_pane_culling_fix, file/CCB+(1.20-1.20.1)+(Bolted Corners) (1).zip (incompatible)
> 	Current Language: en_us
> 	Locale: en_US
> 	System encoding: Cp1252
> 	File encoding: UTF-8
> 	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
> 	Server Running: true
> 	Player Count: 1 / 8; [class_3222['Noah_Dekka'/9925, l='ServerLevel[1am]', x=-219505.45, y=14.00, z=-999190.48]]
> 	Active Data Packs: vanilla, fabric, adorabuild_structures, amplified_nether (incompatible), armourbundles, blockus, bundle_jumble, collective, continents, copper_golem, dyed_bundles, dyed_item_frames, fabric-convention-tags-v2, mr_duplicatable_potterysherds, mr_heavy_coreduplication, mr_kyb_hallucinate (incompatible), mr_rich_husk, mr_warping_wonders, nullscape, sculk_expansion_mr, snowpig, tomereader, useful_brush, bundle, file/NetherStartChallenge_FREE.zip
> 	Available Data Packs: adorabuild_structures, amplified_nether (incompatible), armourbundles, blockus, bundle, bundle_jumble, collective, continents, copper_golem, dyed_bundles, dyed_item_frames, fabric, fabric-convention-tags-v2, file/NetherStartChallenge_FREE.zip, mr_duplicatable_potterysherds, mr_heavy_coreduplication, mr_kyb_hallucinate (incompatible), mr_rich_husk, mr_warping_wonders, nullscape, sculk_expansion_mr, snowpig, tomereader, trade_rebalance, useful_brush, vanilla
> 	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
> 	World Generation: Experimental
> 	World Seed: -2243382515033090771
> 
> >

**Comment by PepperCode1** [comment]
Indium is required when using Sodium. As Indium is not updated to 1.21 yet, wait, remove Sodium, or remove Continuity.
