### ISSUE TITLE
Continuity 3.0.0-beta.5 for 1.21 emissive textures break Wolf Armor tint

### ISSUE THREAD

**Issue by Cedric-Vii** [PepperCode1/Continuity#429]
Using a pack containing _emissive.properties_ **_and_** at least one emissive texture renders the tint on _undyed_ Wolf Armor items (_not_ entity models) as a solid black, rather than transparent. Issue is not present for other dyeable items, like Leather Armor or Leather Horse Armor. Item texture displays correctly when emissive textures **_and_** _emissive.properties_ are removed from the pack. 

Without a pack containing emissive textures; normal behavior
![expected_wolf_armor](https://github.com/PepperCode1/Continuity/assets/51303858/f5417dd7-3e1e-476d-aabe-3252664d0c5e)

With a pack containing emissive textures; unexpected behavior
![observed_wolf_armor](https://github.com/PepperCode1/Continuity/assets/51303858/dfa2d967-efe5-49bc-9128-9a880ee23a0b)

Observed with only Continuity, Fabric, and Fabric API installed.
[latest.log](https://github.com/user-attachments/files/15842908/latest.log)

[Example pack](https://github.com/user-attachments/files/15842901/broken_emissive_test.zip) contains an _emissive.properties_ file and a corresponding .png texture under /textures/block/

**Comment by Cedric-Vii** [comment]
Also confirmed to _not_ occur with just Fabric+Fabric API installed; only occurs once Continuity is enabled.

**Comment by PepperCode1** [comment]
Thank you for the high quality report. This is not a Continuity issue but a previously unknown Indigo issue (Indigo is part of Fabric API). I have opened an issue on the Fabric API repository (FabricMC/fabric#3853), so use that one to track the problem; I will close this issue. Note that it is expected that this issue is not visible without Continuity.
