### ISSUE TITLE
Resource packs doesnt work with continuity

### ISSUE THREAD

**Issue by PashacikV2** [PepperCode1/Continuity#431]
I dont know about older versions but on 1.21 resource packs doesn't fully load. It just gets stuck on the loading screen.

**Comment by PepperCode1** [comment]
Do you have Sodium installed?

**Comment by 14gabriel404** [comment]
I do have it installed and it doesn't work

**Comment by YukiAyase** [comment]
> I do have it installed and it doesn't work

**Indium is required** when **Sodium is installed**
Indium has not yet released an update to support Minecraft 1.21 so we'll have to wait for the Indium author to update the mod
