### ISSUE TITLE
Minecraft randomly crashes on some events

### ISSUE THREAD

**Issue by MuRuLOSE** [PepperCode1/Continuity#436]
Sometimes it crashes at certain intervals, sometimes if you hit a mob, sometimes if you need to render something, maybe it's a problem with sodium and indium, but I'm not sure
![image](https://github.com/PepperCode1/Continuity/assets/134152147/2f8517f0-d92f-4b1b-8089-ce2560ac5c97)

**Comment by PepperCode1** [comment]
Such an error can only occur if you do not have Indium installed. Double check your instance.
