### ISSUE TITLE
Continuity broke textures.

### ISSUE THREAD

**Issue by Yuchenjimmy** [PepperCode1/Continuity#437]
I'm using continuity-3.0.0-beta.5+1.21, with mods in the second picture installed. 
Shader pack: Nostalgia VX
Resourse pack: AVPBR retextured R7-B2
Apparently, right hand should have been a sword, and left hand should be a Totem of Undying.
![Minecraft_ 1 21 2024_6_18 下午 09_02_35](https://github.com/PepperCode1/Continuity/assets/116278150/b895589e-6d3d-49aa-b216-fe4c99b075ad)
![螢幕擷取畫面 2024-06-18 211655](https://github.com/PepperCode1/Continuity/assets/116278150/12c174d7-2764-40f4-ab51-19f21e9dd045)

**Comment by PepperCode1** [comment]
Does this happen without shaders?

**Comment by Yuchenjimmy** [comment]
No. But without continuity, there's no issue too.

**Comment by PepperCode1** [comment]
Still, report this to Iris as well.

**Comment by Yuchenjimmy** [comment]
Sure, no problem.

**Comment by Yuchenjimmy** [comment]
After doing some tests, I found enabling "Parallax occlusion mapping" will cause this problem.

**Comment by Yuchenjimmy** [comment]
And Vertex Attribute Fix must be enabled to fix this issue.

**Comment by PepperCode1** [comment]
IrisShaders/Iris#2369

**Comment by PepperCode1** [comment]
This was just confirmed to be an Iris bug. Use the above linked issue to track this problem.
