### ISSUE TITLE
Continuity stops Vanilla Tweaks texture packs from loading

### ISSUE THREAD

**Issue by chiiseburgur** [PepperCode1/Continuity#438]
On the newest 1.21 version of Fabric, whenever I have Continuity and I try to load my VT resource pack, it always fails. I tried removing the clean glass options, but that didn't work. My hypothesis is that all texture packs that change any block texture fail to load with continuity.

**Comment by PepperCode1** [comment]
Do you have Sodium installed? You must have Indium installed as well in that case.

**Comment by PepperCode1** [comment]
Since there has been no response in a few days I will assume the above solution was adequate.
