### ISSUE TITLE
Crash with Sodium

### ISSUE THREAD

**Issue by Hydranol** [PepperCode1/Continuity#441]
Crash instantly when gravel falls. Haven't tried other falling entities. Does not crash when alone, same thing for sodium, it does not crash when the mod is alone, it's only when the two are together

Using continuity-3.0.0-beta.5+1.21, sodium-fabric-0.5.9+mc1.21, fabric-api-0.100.3+1.21 and fabric-0.15.11-1.21

**Comment by PepperCode1** [comment]
Install Indium.
