### ISSUE TITLE
Continuity crashing when opening inventory (1.21 Fabric)

### ISSUE THREAD

**Issue by Aekology** [PepperCode1/Continuity#442]
The game crashes 100% of the time I open my inventory but only when holding an enchanted item. I believe people have already ran into a similar issue like this for the past few years, but I don't see them providing specific details.

Here's some details that I tried my best to narrow down where the issue could be:

- Crash ONLY happens specifically when opening inventory and holding an enchanted item in your hand, either main or offhand.
- Crash ONLY happens when emissive lighting is enabled in Continuity settings.
- Crashes ONLY when using any resource pack that has emissive textures.
- Crashes whether or not shaders are enabled or disabled, but if Iris is kept installed.
- Does not crash when Iris is removed.
- Does not crash when only using default resource pack.
- Does not crash when not holding an enchanted item (or any item with the enchanted glint)
- Does not crash when continuity is disabled or removed from mods folder.

Mods and crash report attached below

![image](https://github.com/PepperCode1/Continuity/assets/173419965/0b472362-5b96-4801-b345-4d6c51a3d123)

[crash-2024-06-21_07.43.28-client.txt](https://github.com/user-attachments/files/15921136/crash-2024-06-21_07.43.28-client.txt)

**Comment by PepperCode1** [comment]
This is an Iris bug that was fixed with commit IrisShaders/Iris@43cf325. Wait for a new Iris release.
