### ISSUE TITLE
Top of glass panes are transparent. (plus other small issues)

### ISSUE THREAD

**Issue by FloofyKat** [PepperCode1/Continuity#445]
So I dont know if this is an issue with Continuity or the texture pack im using (Vanilla Tweaks) But the top of regular glass panes are transparent besides for 2 pixels. I'm using the "Clean Glass" option on Vanilla Tweaks which says it works with Continuity, but when I turn Vanilla Tweaks off it does actually fix my issue. So I don't know if this is a Vanilla Tweaks issue or a Continuity issue. But just in case I'm sending a bug report to both. 

Edit:
Turning the mod off with Vanilla Tweaks enabled fixes the issue.
(Turning off only "Glass Pane Culling Fix" doesn't fix the issue btw)
It's weird because turning Vanilla Tweaks off with the mod enabled also fixes the issue.

(Also I found more issues, check comments lol)

![image](https://github.com/PepperCode1/Continuity/assets/173712853/c7447b21-a36b-4fd6-82e2-40c1ea9af626)

**Comment by FloofyKat** [comment]
I don't know if this empty space here is intentional or not, but if it's not then that's also an issue.

![image](https://github.com/PepperCode1/Continuity/assets/173712853/9d85b945-f33f-4be9-81c7-87edaf5f74d4)

**Comment by FloofyKat** [comment]
I keep finding issues lol, again works fine with stained panes but not regualar.

![image](https://github.com/PepperCode1/Continuity/assets/173712853/5313c4c1-eeb2-4113-a858-1afe7c438bba)

**Comment by PepperCode1** [comment]
All of these are separate issues.
1. OptiFine makes it so CTM cannot be applied to the top and bottom sides of glass panes, while Continuity does allow that. It seems that resource pack does not specify which sides to apply CTM on for glass panes, so it is applied to all sides. I cannot fix this in Continuity without removing features. It is possible to fix this by modifying the resource pack or making a separate fix resource pack. If possible, report this to the developers of the resource pack so it works correctly with Continuity.
2. This is a bug with the built-in glass pane culling fix pack. It cannot be fixed without a completely new fix to glass pane culling. The MoreCulling mod may provide a better fix, but I have never used it myself.
3. What you marked as correct is actually a translucency sorting bug in Sodium and what you marked as incorrect is actually correct.

**Comment by FloofyKat** [comment]
I have reported the issue to Vanilla Tweaks, and ill checkout MoreCulling once it updates to 1.21.
