### ISSUE TITLE
crash opening inventory

### ISSUE THREAD

**Issue by SS4BLADE** [PepperCode1/Continuity#447]
sometimes when i open the inventory the game crashes it only happens with continuity installed
![image_2024-06-25_130839434](https://github.com/PepperCode1/Continuity/assets/173755045/d1e5cebb-39f5-4643-b0b0-00f247fc00b0)
[crash-2024-06-25_13.08.09-client.txt](https://github.com/user-attachments/files/15964270/crash-2024-06-25_13.08.09-client.txt)

**Comment by PepperCode1** [comment]
This is an Iris issue that has been fixed but a release with said fix has not been made yet.
