### ISSUE TITLE
Problems with 1.20.4

### ISSUE THREAD

**Issue by Z1COB** [PepperCode1/Continuity#448]
Sometimes Minecraft does not start with this mod, it hangs on the Mojang loading screen. If Minecraft has started, the mod does not allow you to load the resource pack with the emissive.properties file. I use this mod only for glowing item textures. Please advise a solution or an alternative mod

**Comment by PepperCode1** [comment]
Provide your mod list and resource pack list.

**Comment by Z1COB** [comment]
> Provide your mod list and resource pack list.

![image](https://github.com/PepperCode1/Continuity/assets/105112268/83daa084-b641-4e15-96e1-c83549d93055)
![image](https://github.com/PepperCode1/Continuity/assets/105112268/acf92c1c-2618-47db-a547-e318b0c78a31)

**Comment by PepperCode1** [comment]
Indium must be installed if Sodium is installed, otherwise Continuity will not work.

**Comment by Z1COB** [comment]
> Indium must be installed if Sodium is installed, otherwise Continuity will not work.

**ok**
