### ISSUE TITLE
Continuity 1.21 breaking held and dropped item visuals w/ shaders and labPBR

### ISSUE THREAD

**Issue by danieltebor** [PepperCode1/Continuity#451]
The latest version of Continuity (3.0.0-beta.5-mc1.21) breaks the visuals of items that are handheld and dropped in the world. The shaderpack is Complementary-5.2.1. This bug can be fixed by disabling custom emissive textures. In addition, after a fresh install of Minecraft the game crashes when opening the inventory. This was fixed after launching the game w/o Continuity, and then relaunching it with Continuity.

I have ensured that Indium is not causing the issue and I have removed all mods except for:
- fabric-api
- indium
- iris
- modmenu
- sodium
- continuity

I have attached a screenshot detailing the issue, my latest.log file, and the crash report.

![2024-06-28_04 54 01](https://github.com/PepperCode1/Continuity/assets/70449929/25ab6ffe-74d2-4209-846d-e0cdc802074a)

[latest.log](https://github.com/user-attachments/files/16027112/latest.log)

[crash-2024-06-28_04.54.44-client.txt](https://github.com/user-attachments/files/16027115/crash-2024-06-28_04.54.44-client.txt)

**Comment by PepperCode1** [comment]
It's an Iris issue. The latest Iris update fixes it, but it requires a new version of Sodium that Indium doesn't support yet.
