### ISSUE TITLE
Game crashes whenever I opened my inventory

### ISSUE THREAD

**Issue by itssofia13** [PepperCode1/Continuity#452]
randomly but very often this mod crashes my game when I try to open my inventory.  All visual mods installed for 1.21 for Vanilla. 
Mods; 
![Screenshot 2024-06-28 221642](https://github.com/PepperCode1/Continuity/assets/75718731/c0781196-f266-4585-a07e-e4ea7be8a7cc)
![Screenshot (29)](https://github.com/PepperCode1/Continuity/assets/75718731/60b3ba51-a8cf-4ec7-8b2e-e60e1a151f4e)

These screenshots are without continuity installed. 

[crash-2024-06-26_00.29.27-client.txt](https://github.com/user-attachments/files/16038811/crash-2024-06-26_00.29.27-client.txt)

**Comment by PepperCode1** [comment]
It's an Iris issue. The latest Iris update fixes it, but it requires a new version of Sodium that Indium doesn't support yet.
