### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PylaAl** [PepperCode1/Continuity#455]
![image](https://github.com/PepperCode1/Continuity/assets/166453615/911aff19-beed-43f0-bf18-82672b3bfc7f)
![image](https://github.com/PepperCode1/Continuity/assets/166453615/1ff1a083-fb1c-4c4a-b15f-149580cee989)

**Comment by YukiAyase** [comment]
We can't really know what you mean by "not working" with the screesnshots you've sent
Please describe what seems to be not working as taking a look on your mods, there's nothing wrong with them and will let Continuity work just fine

**Comment by PylaAl** [comment]
There are no texture like continuity, its normal minecraft

**Comment by YukiAyase** [comment]
> There are no texture like continuity, its normal minecraft

Have you checked if Glass, Bookshelves and Sandstones connect?
If they do then Continuity is working

**Comment by PylaAl** [comment]
no its not connect
ed

**Comment by YukiAyase** [comment]
Please provide screenshots of the blocks I said above and please do also provide your log file
The log file is located in .minecraft/logs, filename is "latest"

**Comment by ghost** [comment]
> Please provide screenshots of the blocks I said above and please do also provide your log file The log file is located in .minecraft/logs, filename is "latest"

[latest.log](https://github.com/user-attachments/files/16042323/latest.log)
![image](https://github.com/PepperCode1/Continuity/assets/117947740/e508d38f-2fe1-454a-942a-e1bdbb0a38bc)

**Comment by YukiAyase** [comment]
> 
> [latest.log](https://github.com/user-attachments/files/16042323/latest.log) ![image](https://private-user-images.githubusercontent.com/117947740/344433455-e508d38f-2fe1-454a-942a-e1bdbb0a38bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MDAxMTcsIm5iZiI6MTcxOTY5OTgxNywicGF0aCI6Ii8xMTc5NDc3NDAvMzQ0NDMzNDU1LWU1MDhkMzhmLTJmZTEtNDU0YS05NDJhLWUxYmRiYjBhMzhiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQyMjIzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzY5MWQwZDI1OTY2MzJlMzhlOTZiZjk2MmI4M2Y2NzQ2Y2NkODc1MTQ3ZmUyYjljMzY5NzE2NmFlNGVmOGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._txUHBh6fl9s2tIM7zOzaYuDtzTdJkb4nxtMRKvvLxI)

# For you, install Indium

**Comment by MikeStorm03** [comment]
![image](https://github.com/PepperCode1/Continuity/assets/149621439/dc2cd959-39d4-4fd1-86f4-d30633310ece)
Mine is not working too, the glass is not connected, I installed Indium
