### ISSUE TITLE
Something in this mod may cause the crash.

### ISSUE THREAD

**Issue by tengpeixu** [PepperCode1/Continuity#456]
At first, I found that opening the inventory while trading with piglins in my mod configuration would crash my game.

Later, I discovered another way to crash, with a background in a monster farm tower with pistons in constant motion underneath. There was a crash when I attacked with my sword.

And it will all be back to normal when I uninstall this mod. I asked some of the bigwigs, and they told me it was due to the conflict between Indium and Continue, and speculated that it was most likely related to Continue.

Here's my mod config (removed Continue) that might help.
![image](https://github.com/PepperCode1/Continuity/assets/128492387/326c49c4-c7da-43ed-a4ea-203aad0e1b16)

**Comment by PepperCode1** [comment]
It's an Iris issue. The latest Iris update fixes it, but it requires a new version of Sodium that Indium doesn't support yet.
