### ISSUE TITLE
NPE on Renderer.meshBuilder() running 1.21 Fabric

### ISSUE THREAD

**Issue by Dean904** [PepperCode1/Continuity#457]
[Exception.log](https://github.com/user-attachments/files/16043180/Exception.log)

**Comment by MissPotato** [comment]
I also encountered this crash. It happenes when I pull lava out of a cauldron.

**Comment by PepperCode1** [comment]
Indium is required when using Sodium.

**Comment by MissPotato** [comment]
Aw crap, you're right.  Sorry about that, indium was causing a different crash so I had it disabled.
