### ISSUE TITLE
Held Enchanted Items Glitched in Inventory - 1.20.4

### ISSUE THREAD

**Issue by AeonixAeon** [PepperCode1/Continuity#458]
On the hotbar they look fine. 
In the game itself they are fine.

Held in Inventory view they are blown out and glitched.

![MC Continuity Distortion](https://github.com/PepperCode1/Continuity/assets/123700111/3d7165eb-0a5d-4a64-b569-e1c4205320bb)

After some testing, it turns out that this happens so long as any texture pack that uses emissive textures is enabled.
I am using Ozocraft Remix as a texture pack (which uses emissive), and Visible Ores. The latter is the reason I wanted to install Continuity for 1.20.4 in Fabric.

Taking Ozocraft Remix out and Visible Ores, it behaves as usual. Adding either of them back seems to bork the rendering of enchanted items in hand for Inventory. That being said there is no reason Visible Ores should affect enchanted held items, and yet it does. This brings me to conclude the glitch has something to do with this version of Continuity and the moment the portion for activating Emissive textures comes into play, bringing that glitch on.

![MC Continuity Distortion - MODS](https://github.com/PepperCode1/Continuity/assets/123700111/938e1eee-35f4-4b32-b39b-b46f795b118f)

I'm not running a lot of mods, either, and have effectively removed all unneeded mods to test.
The glitch only seems to appear when emissive textures are present in the texturepack in any form.

**Comment by PepperCode1** [comment]
It's an Iris issue. The latest Iris update fixes it, but it requires a new version of Sodium that Indium doesn't support yet.

**Comment by AeonixAeon** [comment]
> It's an Iris issue. The latest Iris update fixes it, but it requires a new version of Sodium that Indium doesn't support yet.

So essentially I need to wait for all three of those to play nice together to solve the issue? I narrowed it down to - the Emissive.Properties file in the Optifine Folder. Just the text file that says that the _e after a texture is emissive. Soon as I remove that text file things work (but emissive goes away).

At least that's good to know... I maintain the Ozocraft Remix pack and was straight up losing my sanity trying to figure out what was causing it so I could fix it on Curseforge.

**Comment by PepperCode1** [comment]
From what I recall, the latest Indium release does work with Sodium 0.5.11, but it requires a dependency override. You can include one in your modpack, but I suspect Indium will be updated soon enough.
