### ISSUE TITLE
Mipmapping is ignored

### ISSUE THREAD

**Issue by Chrisblox** [PepperCode1/Continuity#46]
The title says it all, for reference I took some screenshots:
Continuity:
![2022-01-06_12 51 25](https://user-images.githubusercontent.com/35179334/148386229-a6d8bf60-639c-4bdc-b606-9c2a79b0c7dd.png)
Vanilla:
![2022-01-06_12 52 26](https://user-images.githubusercontent.com/35179334/148386236-0047c91d-bf07-44b4-8f3a-086d19e09e10.png)
Only have fabric API and Continuity installed.

**Comment by PepperCode1** [comment]
Could you send a log file?

**Comment by Chrisblox** [comment]
[latest.log](https://github.com/PepperCode1/Continuity/files/7825549/latest.log)

**Comment by PepperCode1** [comment]
One of your textures is 1x1, which disables mipmaps. This is vanilla behavior.
> [00:39:08] [Worker-Main-8/WARN]: Texture minecraft:continuity_reserved/baa60a420f550ec430fc3ec3b611f73a with size 1x1 limits mip level from 4 to 0
> [00:39:08] [Worker-Main-8/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
