### ISSUE TITLE
The mod let Minecreaft collapse when I press the E key.

### ISSUE THREAD

**Issue by zzh10425** [PepperCode1/Continuity#461]
[Error report-2024-7-2.zip](https://github.com/user-attachments/files/16069484/Error.report-2024-7-2.zip)
[bandicam 2024-07-02 .7z.txt](https://github.com/user-attachments/files/16069502/bandicam.2024-07-02.7z.txt)

**Comment by PepperCode1** [comment]
> `java.lang.IllegalStateException: Item group has no page`

Not a Continuity issue.
