### ISSUE TITLE
Textures not connecting with Embeddium 0.3.23

### ISSUE THREAD

**Issue by vinnyg0621** [PepperCode1/Continuity#463]
so, I have all the built-in texture packs enabled, and I'm using connector 1.0.0 beta.44 in 1.20.1. I also have vanilla tweaks clean glass, but they are not connecting either.
![2024-07-04_12 02 35](https://github.com/PepperCode1/Continuity/assets/57818441/46cd219e-3982-4598-802a-dae79be99b69)
![2024-07-04_12 16 58](https://github.com/PepperCode1/Continuity/assets/57818441/c3f9158a-3aa9-480e-9f38-14b4baaf4aa6)
![Screenshot 2024-07-04 121333](https://github.com/PepperCode1/Continuity/assets/57818441/1f97b8f8-d2b2-4ceb-9243-967bf380b904)

**Comment by PepperCode1** [comment]
When using Connector, report issues to Connector.
