### ISSUE TITLE
MAJOR!!!! (VERY, VERY BAD)

### ISSUE THREAD

**Issue by JavaFireStick** [PepperCode1/Continuity#465]
I had the mod installed, with everything that is needed, but one major problem, It blue screened my computer, 2 times! Ever time I try to turn on my computer (after I installed this) it blue screened! I need some help!

It also did not work. Please help!

**Comment by tajemniktv** [comment]
It's not possible and even if it is, would be something incredibly rare. Something else must be causing you to BSOD, especially that it's happening when you simply turn on your PC, not even minecraft. What's the BSOD code?

**Comment by PepperCode1** [comment]
This is definitely not something that is caused by Continuity or something I can fix and thus I am not willing to help debug it.
