### ISSUE TITLE
Falling block crashes Minecraft

### ISSUE THREAD

**Issue by Cathay3520** [PepperCode1/Continuity#468]
# Overview

With Continuity 3.0.0-beta.5+1.21, rendering any falling blocks, including but not limited to falling sand, falling red sand, falling gravel, falling concrete powder, will crash the game.

# Steps to reproduce

## Version 1: naturally generated falling block

1. Launch Minecraft with Continuity mod and Fabric API.
2. Create a world.
3. If there's any naturally generated falling block being rendered, your minecraft crashes.

## Version 2: manually placed falling block

1. Launch Minecraft with Continuity mod and Fabric API.
2. Create a world. If you're lucky, no naturally generated falling block will be rendered yet and your Minecraft will not crash.
3. Place a block of sand/red sand/gravel/concrete powder several blocks above the ground and let it fall.
4. Alternately, you can /summon any falling block above the ground and let it fall.
5. Minecraft renders the falling block and crashes.

# Crash reports and logs

Crash report (naturally generated falling block): 
[crash-2024-07-10_17.10.11-client.txt](https://github.com/user-attachments/files/16158545/crash-2024-07-10_17.10.11-client.txt)

Crash report (manually placed falling block):
[crash-2024-07-10_17.03.53-client.txt](https://github.com/user-attachments/files/16158577/crash-2024-07-10_17.03.53-client.txt)

(I don't think these two many any differences in terms of crash mechanics but whatever)

Logs (naturally generated falling block):
[latest.log](https://github.com/user-attachments/files/16158595/latest.log)

**Comment by PepperCode1** [comment]
Install Indium.

**Comment by Cathay3520** [comment]
my god I'm sure dumb, thanks
