### ISSUE TITLE
The 256x Patrix basic Texture Pack won´t load with Fabric. Because of Continuity Mod.

### ISSUE THREAD

**Issue by edwardlauncher123** [PepperCode1/Continuity#469]
I have this problem with the 256x Patrix pack, where when I am in forge it won´t load, because of the continuity mod, which is required for this texture pack. This mod is only required when using fabric, but when I try with Forge It also will not work, because Optifine 1.21, which is the vers I want to play on isn´t compatible with forge yet, so fabric is my only option, but as I said it doesn´t work. 
Please help, I am not the only person with this kind of problem, and people paid money for this pack. Help is much apprechiated! <3

**Comment by PepperCode1** [comment]
What exactly doesn't work?

**Comment by edwardlauncher123** [comment]
> What exactly doesn't work?

When I launch Fabric (on Curse Forge or Luna Client) with Continuity Mod in it, and then try to load the 256x Patrix texture pack (basic), it says: Reload recource failed!
And then it just sets the texture pack to default. The problem accurs only with the basic pack (the main pack from patrix) and the 256x res. idk why. And it´s not a problem with the version of the mod, cause ive tried with lower version of mc and I had the same problem. Continuity Mod is the only mod that workes with patrix texture pack, so things like grass and flowers work correctly and other have it working with continuity mod too, so idk why its not working foe me.

**Comment by PepperCode1** [comment]
Send the game log from when you ran the game and tried to apply the resource pack.

**Comment by edwardlauncher123** [comment]
> Send the game log from when you ran the game and tried to apply the resource pack.

how do I do that?

**Comment by edwardlauncher123** [comment]
> Send the game log from when you ran the game and tried to apply the resource pack.

[latest.log](https://github.com/user-attachments/files/16167861/latest.log)
right here: I opened mc went into options and tried to change my texture pack to patrix 256x (basic)

**Comment by edwardlauncher123** [comment]
U still there?

**Comment by DemiLichLore** [comment]
this is also a problem with the 128 and 64x versions

**Comment by PepperCode1** [comment]
Your graphics card is not able to load Patrix x256. This is not a Continuity issue.

**Comment by mattmcbeardface** [comment]
May have a fix for this issue. 

https://github.com/mattmcbeardface/pages-of-atlas
