### ISSUE TITLE
Why glass plane not connext up

### ISSUE THREAD

**Issue by Peazaza555** [PepperCode1/Continuity#47]
![Screenshot (19)](https://user-images.githubusercontent.com/97720743/149456279-70176f15-f775-4d84-a263-d23ba1d5cacc.png)

**Comment by TheNukeLore** [comment]
make sure to activate the glass pane fix pack

**Comment by PepperCode1** [comment]
Activate the `continuity/glass_pane_culling_fix` resource pack that is bundled with the mod to resolve this issue.
