### ISSUE TITLE
Patrix 256x won´t load because of (too bad PC) 

### ISSUE THREAD

**Issue by edwardlauncher123** [PepperCode1/Continuity#470]
I know that there is some kind of barrier in the Patrix Texture Pack, so Low-End PC´s are not able to use a highe res patrix pack, but I found out after I had already bought it. Now the requirerments for 256x res are 40 gb of ram and 20 gb vram. I have a solid pc with 32 gb ddr5 ram and 12 gb vram. When I try to load the pack it just won´t. So my question: Is there any way I can still load this pack, even thow I don´t have the exsact requirements? I want to test it out so bad and the worst what could happen is it crashing right?

**Comment by PepperCode1** [comment]
Do not open duplicate issues.

**Comment by edwardlauncher123** [comment]
> Do not open duplicate issues.

I didn´t fcking duplicate it, it a hole other question ??????

**Comment by PepperCode1** [comment]
This issue tracker is not for discussing problems not related to Continuity, then. Modifying a resource pack to work with a certain GPU is not related to Continuity.

**Comment by edwardlauncher123** [comment]
> This issue tracker is not for discussing problems not related to Continuity, then. Modifying a resource pack to work with a certain GPU is not related to Continuity.

I didn´t even mention the mod???

**Comment by PepperCode1** [comment]
This is the **Continuity** issue tracker, not a support forum for Minecraft-related questions.
