### ISSUE TITLE
Patrix 256x won´t load because of (too bad PC)

### ISSUE THREAD

**Issue by edwardlauncher123** [PepperCode1/Continuity#471]
I know that there is some kind of barrier in the Patrix Texture Pack, so Low-End PC´s are not able to use a highe res patrix pack, but I found out after I had already bought it. Now the requirerments for 256x res are 40 gb of ram and 20 gb vram. I have a solid pc with 32 gb ddr5 ram and 12 gb vram. When I try to load the pack it just won´t. So my question: Is there any way I can still load this pack, even thow I don´t have the exsact requirements? I want to test it out so bad and the worst what could happen is it crashing right?

**Comment by PepperCode1** [comment]
This one is definitely a duplicate.

**Comment by edwardlauncher123** [comment]
> This one is definitely a duplicate.

jooooooooooooo, its a general question not ur mod

**Comment by djmrFunnyMan** [comment]
do not ask general questions on random unrelated githubs

for help you can join a general community like the modded mc discord https://discord.com/invite/moddedmc

or better yet the official patrix discord which you should have access to if you link your parreon to your discord acc
