### ISSUE TITLE
[Crash][Mod Compat?] Crash when enter in a world

### ISSUE THREAD

**Issue by MbtMarco** [PepperCode1/Continuity#472]
https://mclo.gs/uveEb3w

**Comment by MbtMarco** [comment]
it is difficult to reproduce the bug, some times crash other times not, it happens sometimes when I create a new world.

**Comment by MbtMarco** [comment]
It could be a resource pack but I am not sure. Could it be?

**Comment by PepperCode1** [comment]
No. Install Indium.

**Comment by MbtMarco** [comment]
Bruh im dumb. Sorry 😅
