### ISSUE TITLE
Game Crash with Breaking Under block  to block Falldown

### ISSUE THREAD

**Issue by AkarinLiu** [PepperCode1/Continuity#478]
https://github.com/user-attachments/assets/b254053b-9394-4f61-9541-8e758bc75717

**Comment by AkarinLiu** [comment]
https://github.com/AkarinLiu/logs/blob/master/Minecraft/2024-07-27-6.log.gz

**Comment by AkarinLiu** [comment]
![屏幕截图 2024-07-27 162649](https://github.com/user-attachments/assets/3c3b1d32-a901-4803-8904-5ee5f6876015)

**Comment by dirtTW** [comment]
你有裝 [Indium](https://modrinth.com/mod/indium) 嗎?
Have you installed [Indium](https://modrinth.com/mod/indium) mod yet?

**Comment by AkarinLiu** [comment]
没有

@阿卡林刘
哔哩哔哩：点此<https://space.bilibili.com/551264339>
小红书：点此<https://www.xiaohongshu.com/user/profile/64fef45a000000000402761c?xhsshare=CopyLink&appuid=64fef45a000000000402761c&apptime=1717390476&share_id=a440f423c2814e66b9b7cca4a9ffa644>
博客：https://www.akarinliu.com
论坛：https://forum.akarinliu.com

邮件来自 Outlook for Windows
________________________________
发件人: dirtTW ***@***.***>
发送时间: 2024年7月28日 19:40
收件人: PepperCode1/Continuity ***@***.***>
抄送: 阿卡林刘 ***@***.***>; Author ***@***.***>
主题: Re: [PepperCode1/Continuity] Game Crash with Breaking Under block to block Falldown (Issue #478)


你有b Indium<https://modrinth.com/mod/indium> ?
Have you installed Indium<https://modrinth.com/mod/indium> mod yet?

―

**Comment by AkarinLiu** [comment]
你们应该将Indium标记为依赖模组

@阿卡林刘
哔哩哔哩：点此<https://space.bilibili.com/551264339>
小红书：点此<https://www.xiaohongshu.com/user/profile/64fef45a000000000402761c?xhsshare=CopyLink&appuid=64fef45a000000000402761c&apptime=1717390476&share_id=a440f423c2814e66b9b7cca4a9ffa644>
博客：https://www.akarinliu.com
论坛：https://forum.akarinliu.com

邮件来自 Outlook for Windows
________________________________
发件人: dirtTW ***@***.***>
发送时间: 2024年7月28日 19:40
收件人: PepperCode1/Continuity ***@***.***>
抄送: 阿卡林刘 ***@***.***>; Author ***@***.***>
主题: Re: [PepperCode1/Continuity] Game Crash with Breaking Under block to block Falldown (Issue #478)


你有b Indium<https://modrinth.com/mod/indium> ?
Have you installed Indium<https://modrinth.com/mod/indium> mod yet?

―

**Comment by PepperCode1** [comment]
Indium is only required when using Sodium, so if it is marked as a dependency, then people who don't use Sodium wouldn't be able to use Continuity.
