### ISSUE TITLE
biome-based ctm not working (v1.0.3)

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#48]
Log: https://pastebin.com/XscxgGdr

Since upgrading to the latest sodium, indium, fabric api, etc. the biome-based ctm method stopped working

**Comment by FwuffyPetsOwO** [comment]
known issue, biome-based things are not functional in latest Sodium for now

**Comment by PepperCode1** [comment]
You can use the latest build from GitHub Actions for now, but this issue was already fixed yesterday. I will release 1.0.4 within a few days.
