### ISSUE TITLE
[Chunk Render Task Executor #0/ERROR]

### ISSUE THREAD

**Issue by TRANDMOND** [PepperCode1/Continuity#484]
First to put you in context: this a test world, and for cleanning reasons i delete all the chunks that I dosen't use so after that I try to enter again to my world and this happened _(the .log in the bottom)_ all the mods work propperly at lees never crashed, I have no idea about this code or how interpretting or what I need to do if it's a problem of the mod's incompatibility or someone or missed or something else if someone can help me i will apreciate it very much

[latest.log](https://mclo.gs/bl8coBa)

**Comment by PepperCode1** [comment]
Downgrade Fabric API; comp500/Indium#324

**Comment by TRANDMOND** [comment]
> Downgrade Fabric API; [comp500/Indium#324](https://github.com/comp500/Indium/issues/324)

Thank you
