### ISSUE TITLE
Crash when opening a world

### ISSUE THREAD

**Issue by RyanAnayaMc** [PepperCode1/Continuity#486]
The game seems to crash when I add continuity to my modpack. To test, I disabled all my mods except Sodium+Extra, Iris, Indium, Fabric API, and Continuity and it still crashes with this basic combo the exact same way. Fabric 0.16.0 on Minecraft 1.21

[latest.log](https://github.com/user-attachments/files/16490106/latest.log)

**Comment by StarComrade** [comment]
Crashing as well, log attached. Removing Continuity let me load up Patrix without crashing (albeit without connected textures)
[2024-08-04-7[1].log](https://github.com/user-attachments/files/16490755/2024-08-04-7.1.log)

**Comment by thehrz** [comment]
The reason is fabric-api's [recent API update](https://github.com/FabricMC/fabric/pull/3937), you can downgrade Fabric API to 0.100.8.

**Comment by PepperCode1** [comment]
Downgrade Fabric API; https://github.com/comp500/Indium/issues/324
