### ISSUE TITLE
[Bug] Continuity is causing problems with a Resource Pack

### ISSUE THREAD

**Issue by Goldenfreddy0703** [PepperCode1/Continuity#49]
![image](https://user-images.githubusercontent.com/62456796/150434428-ccd7aafa-55bf-4e6f-b240-ff774b65fb70.png)
Hey there, I've been doing some testing with other mods and Continuity seems to be having the most problems with a Resource Pack i have installed. Im using Patrix Resource Packs and all of the textures for Wool is not showing its colors and im not sure why. My shaders are not effecting it and the only mods that could be causing the issue is Continuity sense i tested all the mods. If you could take a look at this then that would be greatly appreciated

**These are the mods i have installed:**
![image](https://user-images.githubusercontent.com/62456796/150434699-9986200e-52a3-4370-961e-e403dc4e4cc2.png)

**Here is the download link to the specific Resource Pack i have installed:**
https://www.mediafire.com/file/clx0n3dtdkcyrqf/Patrix_1.18_128x_basic.zip/file

**Comment by PepperCode1** [comment]
Patrix relies not only on Optifine's connected textures features but also on the color features, which are not a part of Continuity. There is another mod called Colormatic that adds them. If you install it, your issue should be resolved. I will not close this issue yet just in case I am mistaken.

**Comment by Goldenfreddy0703** [comment]
Thank you, i will try out Colormatic and see if it works

**Comment by Goldenfreddy0703** [comment]
Hey so im kinda having a couple problems with Colormatic.

First Cloth Config2 is required and irus is incapable with iris-mc1.18.1-1.2.0-pre.jar 
I downgraded my Iris and tried again and it launched but when going into a world, it crashed

Here is my log: https://paste.ee/p/ZS8Dc

**Comment by Goldenfreddy0703** [comment]
Oh i found out that the crashing is due to this issue: https://github.com/kvverti/colormatic/issues/74

**Comment by Goldenfreddy0703** [comment]
Hey so i got Colormatic to work but its not capable with iris-mc1.18.1-1.2.0-pre.jar so im hoping an update will come soon on that. Everything so far works well, i just have a beacon lighting shader bug to deal with but that should be all. 

Again, Thank you for helping me and i will close this issue.
