### ISSUE TITLE
Game crashes when using a resourcepack with the latest version of this mod.

### ISSUE THREAD

**Issue by istupidgirl** [PepperCode1/Continuity#490]
So I only have:
- Sodium
- Indium
- Fabric API
- Continuity

When I put on a resourcepack like the default one that continuity provides, it crashes.

There was another report of this in here, but didn't have enough information, so here's the log to help:
https://mclo.gs/009lNwQ

**Comment by PepperCode1** [comment]
Downgrade Fabric API to 0.100.8; https://github.com/comp500/Indium/issues/324
