### ISSUE TITLE
Game crashes when entering any world

### ISSUE THREAD

**Issue by terraquad** [PepperCode1/Continuity#492]
https://github.com/user-attachments/assets/d43cb044-efa5-4a27-aa8a-f2a519709c93

[console output](https://mclo.gs/aIqENRm)
[crash log](https://mclo.gs/crKyUkR)

code path:
https://github.com/PepperCode1/Continuity/blob/b055564fb8c8643cd187ff5abdc3926480a0c344/src/main/java/me/pepperbell/continuity/client/model/CtmBakedModel.java#L33

I disabled all my mods except
 - sodium
 - indium
 - fabric api
 - continuity

and as you can see, when I enter the world, the game crashes (the issue also happened when I created the world).

OS: Fedora/Linux
Launcher: Prism Launcher (Flatpak)

Without Continuity, I can join the world, but I would like to use it for resource packs.

**Comment by waltonama** [comment]
I am experiencing this exact problem. I've done what you did and disabled all mods except my performance mods, which includes what you listed + Entity Culling, Essential, and Noisium, and it still crashes specifically when Continuity is enabled. I also tried once or two with Essential disabled. But specifically when Continuity is disabled, it does not crash and runs fine. It was working fine with other mods not even 5 hours ago so I wonder what happened.

Also I should mention that while you are on Fedora/Linux, that I am on Windows. Still doesn't change anything though.

**Comment by EreoGaming** [comment]
Exact same issue here

**Comment by EreoGaming** [comment]
I have a crash log if this helps
[crash-2024-08-07_07.07.42-client.txt](https://github.com/user-attachments/files/16522512/crash-2024-08-07_07.07.42-client.txt)

**Comment by cr-gomezm** [comment]
The problem seems to be the same I have had this morning. Fabric API has been updated and it seems to be causing the issue... right now, we only have two options, reverting back Fabric API (which will require to downgrade every dependant mod) or disabling continuity till is updated 😓

**Comment by dicedpixels** [comment]
The Fabric API version which causes Indium to crash is in beta. I have not seen any mod that has a hard dependency to it.

Downgrading to https://modrinth.com/mod/fabric-api/version/0.100.8+1.21 should be sufficient.

**Comment by marzeq** [comment]
Same here

**Comment by PepperCode1** [comment]
Downgrade Fabric API to 0.100.8; comp500/Indium#324

**Comment by Athar42** [comment]
This is definitively an issue on Continuity.

1.21.1, need a more recent version of Fabric API (0.102.0 at that time), same error as reported.
If we disable Continuity but kept Indium/Sodium, it's working fine.

From what you point out @PepperCode1 , I read this "Continuity loads the bad method in indium, causing the crash", so that's an issue on your side if I get it right :/
