### ISSUE TITLE
Causes crashing the game

### ISSUE THREAD

**Issue by PaRHaM-M0** [PepperCode1/Continuity#494]
I am experiencing a consistent crash when trying to load worlds in Minecraft. This issue occurs specifically when I am using the Continuity mod alongside Indium 1.0.34 and Sodium 0.5.11. The game crashes during the world loading process.

**Comment by JustPixeled** [comment]
The game crashes upon loading into the world with a resource pack enabled that requires Continuity and have Indium  in
your client. However, Continuity works fine with said resource pack if Indium (and Sodium) isn't in your client.

Downgrading Fabric API to 0.100.8+1.21 fixes this issue. 

So TL;DR Fabric API 0.101+1.21 and above breaks compatibility between Continuity and Indium for some reason.

**Comment by PepperCode1** [comment]
https://github.com/comp500/Indium/issues/324

**Comment by PaRHaM-M0** [comment]
Downgrading Fabric api and puzzles lib works flawlessly, thanks a lot!❤️
