### ISSUE TITLE
[BUG]Crash generated when using fabric_api0.102.0+1.21

### ISSUE THREAD

**Issue by just-a-snowy-owl** [PepperCode1/Continuity#498]
When I only loaded the following 7 mods and entered the archive using fabic_api0.102.0+1.21, and then loaded the Default Connected Textures built-in in Continuity, it would not render and cause a crash.fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		indium: Indium 1.0.34+mc1.21
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.12.7
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sspb: Sodium Shadowy Path Blocks 3.3.1
But when I replace it with fabric-api-0.100.8+1.21 and repeat the above operation, there will be no crash.[
[minecraft-exported-logs-2024-08-10T12-23-36.log](https://github.com/user-attachments/files/16568479/minecraft-exported-logs-2024-08-10T12-23-36.log)
](url)

**Comment by just-a-snowy-owl** [comment]
@PepperCode1 I think the above information and logs should be sufficient for you to confirm how to make the modifications.

**Comment by girshcatt** [comment]
just downgrade fabric api to 0.100.8

**Comment by Soreek** [comment]
> just downgrade fabric api to 0.100.8

Thanks a lot!

**Comment by Tera498** [comment]
so i downgraded the fabric api to .100.8 but all my mods are not incompatible, would i have to re-install all my mods again to that version ?

**Comment by girshcatt** [comment]
> so i downgraded the fabric api to .100.8 but all my mods are not incompatible, would i have to re-install all my mods again to that version ?

of coarse you dont need to, there is like no mods that require fabric api 0.102.x+ now

**Comment by PepperCode1** [comment]
Update Indium.
