### ISSUE TITLE
Crash in 1.21.1

### ISSUE THREAD

**Issue by zhenlige** [PepperCode1/Continuity#499]
The game crashes when loading the world in 1.21.1 with this mod. The mod version is 3.0.0-beta.5.

**Comment by RyanYu2004** [comment]
The game also crashes when loading the world in 1.21 with it, but it works in the main title. I don't know whether Indium & Sodium on my game affect it or not. ( 3.0.0-beta.5 )

**Comment by zhenlige** [comment]
1.21 is OK on my device, and 1.21.1 also works in the main title. Both versions are with Sodium 0.5.11 and Indium 1.0.34.

> The game also crashes when loading the world in 1.21 with it, but it works in the main title. I don't know whether Indium & Sodium on my game affect it or not. ( 3.0.0-beta.5 )

**Comment by Salted-Bread** [comment]
Having crashes too, but only when using Fabric API versions above 0.100.8

**Comment by girshcatt** [comment]
> Having crashes too, but only when using Fabric API versions above 0.100.8

same, 0.100.8 is the most stable now

**Comment by Aturtle2021** [comment]
game will crash with Fabric API versions above 0.100.8,but Fabric API in 1.21.1 only has version 102.0

**Comment by dmstewart42** [comment]
[comp500/Indium#324](https://github.com/comp500/Indium/issues/324)

**Comment by zhenlige** [comment]
> game will crash with Fabric API versions above 0.100.8,but Fabric API in 1.21.1 only has version 102.0

Changing `fabric.mod.json` in Fabric API 0.100.8 to contain 1.21.1 seems to solve the problem.

**Comment by PepperCode1** [comment]
Install or update Indium.
