### ISSUE TITLE
Continuity causes game to crash when enabling texture packs with connected textures on (1.21)

### ISSUE THREAD

**Issue by Giganta00** [PepperCode1/Continuity#500]
As the title says, the game crashes whenever I enable the texture packs associated with Continuity and also having the "Connected textures" turned on in the config screen. I use a fair amount of mods including Distant Horizons, Sodium, Indium and Iris with Complementary Unbound in Fabric 0.16.0 with Fabric API 0.102.0+1.21. The game does not crash if the connected textures setting is turned off but it does cause the shaders to not be able to be loaded.

I have allocated 32gb of ram out of 64gb to the game, using a 13th gen i9 KF and a 12gb rtx 3060 if this helps.
All mods and has been downloaded through modrinth and game is launched through modrinth
[Latest.log Continuity crash.txt](https://github.com/user-attachments/files/16570279/Latest.log.Continuity.crash.txt)
[crash-2024-08-10_18.10.38-client.txt](https://github.com/user-attachments/files/16570295/crash-2024-08-10_18.10.38-client.txt)
[ComplementaryUnbound_r5.2.2.zip.txt](https://github.com/user-attachments/files/16570296/ComplementaryUnbound_r5.2.2.zip.txt)

These files should be enough i think to troubleshoot the issue.
Thank you in advance.

**Comment by dmstewart42** [comment]
See [comp500/Indium#324](https://github.com/comp500/Indium/issues/324)

**Comment by PepperCode1** [comment]
Update Indium.
