### ISSUE TITLE
Sodium + Continuity crashes when extending a piston (it crashes when rendering the moving_piston block?)

### ISSUE THREAD

**Issue by MausKaffee34767** [PepperCode1/Continuity#502]
Mod versions:
Continiuity: `3.0.0-beta.5+1.21`
Sodium: `0.5.11+mc1.21`
Fabric API: `0.102.0+1.21.1`
Fabric: `0.16.0-1.21.1`

Description:
When powering (extending) a piston the game crashes!

INFO:
THIS ONLY OCCURS WHEN USING SODIUM
(but i dont think i should report it to sodium)

Crash log:
[crash-2024-08-12_21.04.28-client.txt](https://github.com/user-attachments/files/16590869/crash-2024-08-12_21.04.28-client.txt)

Steps to recreate:
1. Place a piston
2. Power it

---
![2024-08-12_21 10 54](https://github.com/user-attachments/assets/0c1416cd-66ee-4736-89ef-7e41c2e00272)

**Comment by MausKaffee34767** [comment]
Download links:
https://modrinth.com/mod/continuity/version/3.0.0-beta.5+1.21
https://modrinth.com/mod/sodium/version/mc1.21-0.5.11
https://modrinth.com/mod/fabric-api/version/0.102.1+1.21.1

OLD DOWNLOAD LINK:
https://modrinth.com/mod/fabric-api/version/0.102.0+1.21.1

**Comment by MausKaffee34767** [comment]
Also works with fabric api 0.102.1+1.21.1

**Comment by PepperCode1** [comment]
Install Indium.
