### ISSUE TITLE
Crashed when loading resource packs

### ISSUE THREAD

**Issue by Legends0356** [PepperCode1/Continuity#505]
The game crashes as soon as i add the resource packs.
![image](https://github.com/user-attachments/assets/90c6df8a-54ff-4299-9bdd-5b14a69387a5)

Here is the crash report:
https://gist.github.com/Legends0356/0d7f5ae4916af04023adbc8f7f699dac

**Comment by dmstewart42** [comment]
[comp500/Indium#324](https://github.com/comp500/Indium/issues/324)

**Comment by PepperCode1** [comment]
Update Indium.

**Comment by dmstewart42** [comment]
Thank you PepperCode1.
Indium 1.0.35, Continuity 3.0.0-beta5 and Fabric API 1.102.0 work together with no crash
