### ISSUE TITLE
When i load "stay true" resorce pack it freezes my game forever

### ISSUE THREAD

**Issue by Tobias433** [PepperCode1/Continuity#506]
![image](https://github.com/user-attachments/assets/7f8fd07b-41b2-4f4e-a756-c61656aa490f)

![image](https://github.com/user-attachments/assets/ab7bab86-2fab-4afe-bce8-45122fed659d)

theres much more weird code (probably 1k lines) but its the main thing i think.

when i restart the game it does the same thing, if i enter my world without the texture pack and i enable it later it closes my game.
I DO USE INDIUM AND KEEP MY MODS UP TO DATE

someone help please? 
if i enable faithless is crashes too, so i dont know

**Comment by PepperCode1** [comment]
Update Indium.
