### ISSUE TITLE
Crash when I use Connect Textures 

### ISSUE THREAD

**Issue by Dobastickrn** [PepperCode1/Continuity#508]
Game freeze & crash when I join a world with Connect Textures.
Crash Report:
[Crash-Report-2024.8.14_14.48.58.zip](https://github.com/user-attachments/files/16608707/Crash-Report-2024.8.14_14.48.58.zip)

**Comment by dmstewart42** [comment]
[comp500/Indium#324](https://github.com/comp500/Indium/issues/324)

**Comment by PepperCode1** [comment]
Update Indium.
