### ISSUE TITLE
Textures are not connecting

### ISSUE THREAD

**Issue by tipsyGnostalgik** [PepperCode1/Continuity#509]
Hello, I have installed this mod alongside many others, however, this one does not connect the textures, even with the resource pack enabled and at the top!

![javaw_elbYdqhOyI](https://github.com/user-attachments/assets/f346eba6-0638-4148-8336-52e93c98c6b9)
![image](https://github.com/user-attachments/assets/055a69af-4e11-4a69-9f01-2c30a9ff9632)
_I am not using Windows 7, it's themed Windows 11, just to avoid any confussion._

[Here is my log if it helps.](https://pastebin.com/58NUx1B4)

**Comment by PepperCode1** [comment]
Install Indium.
