### ISSUE TITLE
ctm repeat does not support bedrock & deepslate in 1.18

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#51]
![2022-01-23_11 55 32](https://user-images.githubusercontent.com/84546057/150661049-5fa7b94a-788b-4ca6-a04e-1df3472e4d07.png)

log: https://pastebin.com/Pb7Be5NY

v1.0.4 build 31

**Comment by PepperCode1** [comment]
Please provide a log.

**Comment by PepperCode1** [comment]
If you are making your own resource pack ("Custom Resourcepack") you need to override the blockstate files for stone and bedrock to disable random models. Continuity will not be adding an option for this because it is the resource pack's responsibility.
