### ISSUE TITLE
Game Crash using Default Resource Pack MC-1.21 

### ISSUE THREAD

**Issue by schrummy14** [PepperCode1/Continuity#510]
Hello,
Began to see crashes when enabling the default continuity resource pack.
I can have continuity installed, without the resource pack enabled, without causing crashes.
Once the resource pack is enabled, I see the crash occur.

Below is the crash log. Please let me know if you would like me to try anything else to narrow down the cause.
Thank you.
[crash-2024-08-15_23.22.03-client.txt](https://github.com/user-attachments/files/16632922/crash-2024-08-15_23.22.03-client.txt)

**Comment by PepperCode1** [comment]
Update Indium.

**Comment by schrummy14** [comment]
Sorry for the noise.
Updating Indium did the trick.
Saw the other issues without crash logs but didn't check the closed.
Thank you.
