### ISSUE TITLE
Crash to desktop with 3.0.0-beta-5+1.21

### ISSUE THREAD

**Issue by meza** [PepperCode1/Continuity#515]
With continunity enabled, this is what happens: https://mclo.gs/a8PiZz1

Without it, everything works fine.

Here's the crash report: https://mclo.gs/fbOoC6N

**Comment by PepperCode1** [comment]
Install Indium.

**Comment by meza** [comment]
Omg, classic... I uninstalled it one time to debug another issue and apparently forgot to put it back... thanks :D
