### ISSUE TITLE
I'd like to create textures for modded blocks

### ISSUE THREAD

**Issue by vinnyg0621** [PepperCode1/Continuity#516]
so I'm using biomes o' plenty and it adds new kinds of sandstones. but when I tried to create a connected texture it did not work. is it even possible to support a modded block? I also want to do this with other mods.
also, have you had the time to create the documentation yet?

**Comment by PepperCode1** [comment]
"It did not work" is not enough context for anyone to fix your issue and this issue tracker is not a support forum. If you looked at any OptiFine CTM documentation, such as [this one](https://optifine.readthedocs.io/ctm.html), you would know that it is possible to define a modded block in properties that accept blocks. As for the Continuity wiki, it has been published for months.

**Comment by vinnyg0621** [comment]
thank you, it works now! :D
