### ISSUE TITLE
grass biome tint is applied incorrectly 1.18

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#52]
v.1.0.4 build 31

log: https://pastebin.com/Pb7Be5NY

![2022-01-24_08 22 03](https://user-images.githubusercontent.com/84546057/150699623-21b7bc70-d00a-4bc4-b8e4-341e6bce53c2.png)

I have removed the tint from the block model file for grass and grass_block, and yet the tint is still applied. Also there are random patches of tint from other biomes.

**Comment by PepperCode1** [comment]
Please provide a log.

**Comment by PepperCode1** [comment]
Does this happen if you turn off shaders?

**Comment by ghost** [comment]
yes

**Comment by PepperCode1** [comment]
Does it happen if you use only Continuity and Fabric API?

**Comment by ghost** [comment]
It occurs when indium-1.0.2-alpha2+mc1.18.1 is installed with continuity; and does not occur when continuity is removed, and vis versa.

**Comment by PepperCode1** [comment]
I tested with the latest Sodium and Indium releases and Continuity 1.0.4 build 32 and everything works correctly. If you could provide your custom resourcepack one way or another that would be beneficial.

![image](https://user-images.githubusercontent.com/44146161/150720239-7ebbbfd0-702f-40cb-b917-02bc3b9eb5f9.png)

**Comment by ghost** [comment]
Turns out the biome tint issue only occurs at Y-63. 

A weird quirk I didn't notice.

Nothing to do with Continuity.
