### ISSUE TITLE
Continuity not working

### ISSUE THREAD

**Issue by Ursaross** [PepperCode1/Continuity#521]
_As the title suggests, Continuity isn't working for me even with the dependencies installed. (Sodium user)_
I've disabled/removed a lot of mods to wonder what was the problem, I caved and made a new instance in Modrinth, and it still doesn't work.
![2024-09-07_15 29 25](https://github.com/user-attachments/assets/0ff61d94-7cf5-4291-ad33-4618b05b164f)
![image](https://github.com/user-attachments/assets/7243cc45-83c9-4fcb-93db-c69d8c65f15e)
**_No other resource packs other than the default and Continuity's_**
![image](https://github.com/user-attachments/assets/e5e20275-80d3-4c55-aa00-bc9dd1414400)

How does one fix this?

**Comment by Ursaross** [comment]
Don't know if it's relevant or not, but all my graphics are set as the default (Fancy)
_also let me know if you need a better photo than the cobble next to dirt_

**Comment by YukiAyase** [comment]
## Continuity by default only connects glass, sandstone and bookshelves
You'd need a custom resource pack that supports overlays for the connection you'd want
Like [xali's Enhanced Vanilla](https://modrinth.com/resourcepack/xalis-enhanced-vanilla/versions)

**Comment by Ursaross** [comment]
> ## Continuity by default only connects glass, sandstone and bookshelves
> You'd need a custom resource pack that supports overlays for the connection you'd want Like [xali's Enhanced Vanilla](https://modrinth.com/resourcepack/xalis-enhanced-vanilla/versions)

Oh my god, thank you.
