### ISSUE TITLE
Continuity renders vanilla textures on top of ones provided by resource packs in certain situations

### ISSUE THREAD

**Issue by pajicadvance** [PepperCode1/Continuity#523]
Setup:

- Minecraft 1.21.1
- Fabric Loader 0.16.5
- Fabric API 0.104.0+1.21.1
- Continuity 3.0.0-beta5+1.21

Reproduction steps:

1. Go to https://vanillatweaks.net/picker/resource-packs/, under Aesthetic select "Splash Bottle O' Enchanting" and download the resource pack.
2. Download the [Glowing](https://modrinth.com/resourcepack/glowing) resource pack.
3. Launch the game and enable *only* the Vanilla Tweaks resource pack.
![image](https://github.com/user-attachments/assets/0c789e89-34a5-49b8-9611-9ae26fd06f48)
5. Verify in game that the bottle o' enchanting texture changed.
![image](https://github.com/user-attachments/assets/c8e1e9df-289d-4e54-88d2-edfa38fa86f5)
6. Now enable the Glowing resource pack on top of the Vanilla Tweaks one.
![image](https://github.com/user-attachments/assets/a8671b54-9c31-4be6-9a96-91ae8a5f1257)
8. Observe that the vanilla bottle o' enchanting texture is being rendered over the one from the Vanilla Tweaks resource pack.
![image](https://github.com/user-attachments/assets/d1b45e33-6729-4460-9b46-3694fe4f662a)

Log file: https://mclo.gs/n2VeK8Y

**Comment by PepperCode1** [comment]
This seems entirely expected. The texture on top is presumably the emissive texture provided by the glowing pack. I expect that disabling emissive textures will "fix" this and that using the same resource packs on OptiFine will result in the same behavior. Not every resource pack is compatible with every other resource pack.

**Comment by pajicadvance** [comment]
I see what's going on now, a bit of an oversight on my side as I didn't check whether the glowing pack contained textures for the bottle, sorry about that!
