### ISSUE TITLE
[Enhancement] Adding continuity to the core of slime blocks

### ISSUE THREAD

**Issue by Abelkrijgtalles** [PepperCode1/Continuity#526]
Hi, I hope you're doing well. I thought that adding continuity to the core of slime blocks would be a good enhancement to this mod.
That's all,  have a nice rest of your day!
PS: I'll maybe add this some time in a pull request if I can understand the code to help out.

**Comment by PepperCode1** [comment]
What do you mean? I have no idea this means.

**Comment by Abelkrijgtalles** [comment]
I mean that the slime blocks merge in this way:
![image](https://github.com/user-attachments/assets/abbacdd3-fcc7-4b7e-ba91-1532c30c9c57)

**Comment by PepperCode1** [comment]
[This pack](https://www.curseforge.com/minecraft/texture-packs/rekindled-ctm) does this. If it doesn't look how you want it to, you can make your own pack based on how that pack works, or ask that pack's author how they accomplished connected slime blocks. This is a significant visual change so I am not willing to add this to Continuity's default CTM resource pack.
