### ISSUE TITLE
Turn off Connected Textures for specific packs

### ISSUE THREAD

**Issue by proxyorg** [PepperCode1/Continuity#527]
Is it possible to turn off continuity or not use continuity's connected textures without having to turn off connected textures completely?
I have a pack that changes ancient debris and netherite block but since continuity adds connected textures to those blocks, It replaces the texture pack. I would turn off connected textures completely but i have another pack that has connected textures and I cant play minecraft without. Is it possible?

**Comment by YukiAyase** [comment]
**You'll have to edit the resource pack itself and remove the connected textures for the blocks you don't like**
Continuity only connects glass, sandstone and bookshelves by default, and **if you're using a custom resource pack that connects other blocks, Continuity only allows/enables this**

**Comment by PepperCode1** [comment]
Continuity's default pack does not add connected textures to ancient debris or netherite blocks, so I do not understand what you want to do. If you want to disable connected textures from a third-party resource pack for specific blocks or textures, then you will have to edit that pack.
