### ISSUE TITLE
Glass blocks glitches on chunck border

### ISSUE THREAD

**Issue by Yoween** [PepperCode1/Continuity#53]
So I'm making a timelapse using the replay mod and I wanted to use connected textures but it does this weird glitch on chunck border

![2022-01-29_10 06 10](https://user-images.githubusercontent.com/82267191/151655046-2b87937b-2146-4223-9f75-ddbaa9f9bbdb.png)
s

**Comment by PepperCode1** [comment]
What mods are you using? Does it happen with only Continuity and Fabric API?

**Comment by PepperCode1** [comment]
There has not been a follow up from the issue author in almost a month so I will assume this is CaffeineMC/sodium-fabric#38. If it is not, please open a new issue.

**Comment by Yoween** [comment]
I'm so sorry I never recieved a notification about your reply... I used only Sodium, Continuity and Replay Mod and the issue seems to be fixed now
