### ISSUE TITLE
port to neoforge?

### ISSUE THREAD

**Issue by VaporeonScripts** [PepperCode1/Continuity#530]
will the mod ever get ported to neoforge 1.21.1? as im unable to publish my modpack with sinytra connector and fabric version of continuity

**Comment by v3xed-v0id** [comment]
I fully support this, this mod is needed for neoforge as i still havent found a worthwhile working replacement for connective textures on neoforge, i hope this gets looked at! i would be ok with either a sinytra connector port or native neoforge port, whatever the devs prefer to do to get this ported i would fully support.

**Comment by Lumiko32** [comment]
Yes, very agree, neoforge has been getting more and more popular since 1.21.1, but there is no similar mod that works well yet, so we need it！

**Comment by v3xed-v0id** [comment]
> Yes, very agree, neoforge has been getting more and more popular since 1.21.1, but there is no similar mod that works well yet, so we need it！

Especially since sodium has an official neoforge port now, it would be much easier for them to port to neoforge i think.

**Comment by PepperCode1** [comment]
Continuity already works well when used with Connector. What advantages would a standalone NeoForge jar have?

**Comment by v3xed-v0id** [comment]
> Continuity already works well when used with Connector. What advantages would a standalone NeoForge jar have?

i find that connector is unreliable and buggy, as well as it being beta software more generally, i dont think it is a good idea to rely on it for neoforge support, i have personally had stability issues and bugs with connector with compatibility with other mods, having a native neoforge port would allievate these issues.

**Comment by VaporeonScripts** [comment]
currently using it for continuity, never had an issue, altough a direct neoforge port would be better to have less mods installed and less conflicts :D

**Comment by PepperCode1** [comment]
The easiest way for me to make a NeoForge jar right now would be to bundle the parts of Connector that Continuity needs to work in the jar (what you call a "sinytra connector port"). While this bundled part of Connector would be simpler than all of Connector, I don't know if that would necessarily help with compatibility. A standalone jar also makes me responsible for any issues that arise, which include issues in Connector's code that I can't fix.

**Comment by v3xed-v0id** [comment]
well yeah thats why i recommended a native port, sinytra connector isnt stable and imo isnt a reliable mod to rely on for mod compat for neoforge, its beta software and has lots of issues and i have ran into issues where fabric mods on sinytra dont work together with neoforge mods bc of incompatibilities between the 2 modloaders n stuff, sadly it just doesnt work all that well sadly, it would probably be much more reliable long term and simpler to just do a native neoforge port than trying to get it to work on sinytra

u said it urself about the issues in sinytra that u cant fix with continuity, theres bound to be more and more issues with sinytra that pile up as the project progresses and keeps trying to make more compatibility with upstream, and the same issue persists whether u make a seperate jar file for sinytra or not, so its more reliable to do a neoforge native port honestly

thats just my 2 cents tho, plus sinytra is too complex for the average user and i wouldnt recommend it to anyone for ppl who want stable modpacks

**Comment by PepperCode1** [comment]
A native port requires significantly more time and effort to both make initially and maintain later. I do not currently have the time for this.

**Comment by v3xed-v0id** [comment]
> A native port requires significantly more time and effort to both make initially and maintain later. I do not currently have the time for this.

well i mean no pressure ofc, not trying to put pressure on u to do it, mb if i was, do it at ur own pace ofc, if u dont currently have time for a neoforge port then hopefully someone else whos smarter than me can do a neoforge port or something

**Comment by DarthCaesium** [comment]
Sorry, could you please add the NeoForge tag to your mod on CurseForge so that NeoForge modpacks can use it with Sinytra Connector on CurseForge?

**Comment by Fundryi** [comment]
> Sorry, could you please add the NeoForge tag to your mod on CurseForge so that NeoForge modpacks can use it with Sinytra Connector on CurseForge?

I second this, this is exactly my problem atm, I can't upload my mod pack, it always gets rejected because its only missing the NeoForge Tag, even tho with the "Forgified Fabric API" makes it work without any issues. 

Just upload the same version as Alpha and NeoForge Tag on it, this way people won't be downloading it for Fabric but it will still work with modpacks.

**Comment by VaporeonScripts** [comment]
my solution for the pack problem was this:
![image](https://github.com/user-attachments/assets/ac77e4dc-8734-40e2-8c39-40fd351c749e)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/bb5e8065-320c-4afb-a510-ecc0bbc72dd8)

**Comment by VaporeonScripts** [comment]
redirects to latest fabric ver

**Comment by Fundryi** [comment]
ALOT of the people won't bother doing that sadly :/

**Comment by VaporeonScripts** [comment]
well, their fault then lol

**Comment by PepperCode1** [comment]
With the release of 3.0.0, I will upload separate jars for 1.20.1 and 1.21.1 that are just the Fabric jar but are marked as working with Forge/NeoForge and list Connector as a required dependency.

**Comment by PepperCode1** [comment]
I just released 3.0.0 and I have made Forge/NeoForge releases with Connector as a required dependency on Modrinth. I tried to do the same on CurseForge, but those releases were rejected.

**Comment by VaporeonScripts** [comment]
Bruh,it's always that goofy site that can't work properly

**Comment by VaporeonScripts** [comment]
try to chat with support, cleanf3 managed to do it on cf

**Comment by PepperCode1** [comment]
I added proper Connector integration and these jars were accepted by CurseForge. Continuity for Forge 1.20.1 and NeoForge 1.21.1 is now available on both platforms, so I will close this issue now. There are no plans to port to Forge/NeoForge versions which for which Connector does not exist.

**Comment by Sodj** [comment]
@VaporeonScripts will we have continuity for MC26.x on neoforge?
if no, what would be an alternative?
