### ISSUE TITLE
No valid connection + no matching block found

### ISSUE THREAD

**Issue by Aeldit** [PepperCode1/Continuity#532]
Hi, so for context, I am adding connected textures support for Versecraft texteures to my resourcepack. I added 4 textures (`azalea_log_top`, `stripped_azalea_log_top`, `polished_calcite` and `polished_dripstone`), but only the log textures work and I get this error for the `polished` blocks :

```
[18:16:35] [Worker-Main-9/ERROR]: No tile or block matches provided in file 'versecraft:optifine/ctm/stones/polished_calcite.properties' in pack 'file/CTM_OF_Fabric'
[18:16:35] [Worker-Main-9/ERROR]: No valid connection type provided in file 'versecraft:optifine/ctm/stones/polished_calcite.properties' in pack 'file/CTM_OF_Fabric'
[18:16:35] [Worker-Main-9/ERROR]: No tile or block matches provided in file 'versecraft:optifine/ctm/stones/polished_dripstone.properties' in pack 'file/CTM_OF_Fabric'
[18:16:35] [Worker-Main-9/ERROR]: No valid connection type provided in file 'versecraft:optifine/ctm/stones/polished_dripstone.properties' in pack 'file/CTM_OF_Fabric'
```

Minecraft version : `1.21.1`

These mods are installed :
- Biomes O'Plenty `21.1.0.6`
- Cloth Config v15 `15.0.140`
- Continuity `3.0.0-beta.5+1.21`
- Dynamic FPS `3.7.3`
- Fabric API `0.106.0+1.21.1`
- FerriteCore `7.0.1`
- GlitchCore `2.1.0.0`
- Mod Menu `11.0.3`
- PlaceHolder API `2.4.1+1.21`
- Remove reloading Screen `5.0.8+mc1.21.1-fabric`
- TerraBlender `4.1.0.3`
- VerseCraft `4.0+1.21.1`

And the folder tree of the pack is as follows :

> I only included versercraft textures here but there are also minecraft's and biomesoplenty's textures in the pack, and they work

```shell
└── CTM_OF_Fabric/assets/versecraft/optifine
    └── ctm
        ├── organics
        │   ├── azalea_log_top
        │   │   ├── *.png
        │   │   └── azalea_log_top.properties
        │   └── stripped_azalea_log_top
        │       ├── *.png
        │       └── stripped_azalea_log_top.properties
        └── stones
            ├── *.png
            ├── polished_calcite.properties
            └── polished_dripstone.properties
```

Contents of the properties files :

```properties
# File : azalea_log_top.properties
matchBlocks=versecraft:azalea_log
method=ctm
tiles=0-46
faces=top bottom
connect=tile
```

```properties
# File : polished_calcite.properties
matchTiles=versecraft:polished_calcite
method=ctm_compact
tiles=0-4
```

```properties
# File : polished_dripstone.properties
matchTiles=versecraft:polished_dripstone
method=ctm_compact
tiles=5-9
```

Here is what it looks like in-game :
![2024-10-19_18 32 42](https://github.com/user-attachments/assets/eefbdc0b-1a7d-41f7-bf21-51daa40f9d74)

I tripled checked the textures path in Versecraft's assets and they are correct in my files.

What could be the issue ?

**Comment by PepperCode1** [comment]
It is only possible for `No tile or block matches provided...` to appear in the log when both `matchTiles` and `matchBlocks` properties are completely absent from the file, but you have defined `matchTiles`, so it should not appear, even if the sprites don't exist. Try adding `\` before the `:` for now. I'll do some testing to see if I can locate the issue.

**Comment by Aeldit** [comment]
Thanks :)

Also adding the `\` doesn't seem to work

**Comment by Aeldit** [comment]
After some investigation, it seems that some characters that don't appear in text editors (Intelij idea when testing, neovim when writing my pack's files) where placed before the `matchTiles` properties :

![image](https://github.com/user-attachments/assets/c4c994c7-d41a-4e67-a028-cc184430653f)

We can see here that the polished calcite file that I edited and saved with Intelij idea no longer has the wierd characters, while the one not saved yet with Intelij idea has them.

![image](https://github.com/user-attachments/assets/883de66f-23e2-42b0-81a6-4c024e66322f)

Adding a print to the `CompactConnectingCtmProperties#parseTileReplacements()` method shows that the characters appear before the `matchTiles` text.

It may be a good idea to add some sort of message in the console if the given key has `matchTiles`, saying that some characters that should not be here are detected.

I can try to make a PR for that if you want, so I wont be closing this issue for now :)

**Comment by PepperCode1** [comment]
Closing for same reason as linked PR. I don't think that this is something Continuity itself should detect.
