### ISSUE TITLE
1.21.2 update?

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#533]
is this resource pack getting a update for 1.21.2? just asking for curiosity.

**Comment by PepperCode1** [comment]
This is a mod for Fabric, not a resource pack, and yes, it will be updated eventually.

**Comment by Agustinbro27** [comment]
it has been 5 days after 1.21.3 update and there is no 1.21.3 update mod :(

**Comment by viperxx** [comment]
> it has been 5 days after 1.21.3 update and there is no 1.21.3 update mod :(

While I too am eager to update, I’d say it may take a bit. I’ve helped update some other mods for 1.21.2/.3 and some of the changes for certain mods can be extensive.

plus I don’t think they are getting paid for this lol maybe lets give them a few more weekends :)

**Comment by Agustinbro27** [comment]
> > it has been 5 days after 1.21.3 update and there is no 1.21.3 update mod :(
> 
> While I too am eager to update, I’d say it may take a bit. I’ve helped update some other mods for 1.21.2/.3 and some of the changes for certain mods can be extensive.
> 
> plus I don’t think they are getting paid for this lol maybe lets give them a few more weekends :)

ok

**Comment by PepperCode1** [comment]
3.0.0+1.21.3 has been released on Modrinth, CurseForge, and GitHub Releases.

**Comment by PepperCode1** [comment]
A 1.21.2 version specifically will not be released. Please update to 1.21.3.
