### ISSUE TITLE
Glass Not Connecting

### ISSUE THREAD

**Issue by PixelArtPlays** [PepperCode1/Continuity#54]
Hi! I did some research and thought I downloaded everything I needed in order for Continuity to work. Here's my full list of mods:(including the Fabric Installer)

fabric-api-0.43.1+1.18
iris-mc1.18.1-1.2.0-pre
lambdynamiclights-2.1.0+1.17
modmenu-3.0.1
okzoomer-5.0.0-beta.3+1.17.1
replaymod-1.18.1-2.6.3
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
continuity-1.0.3+1.18
indium-1.0.2-alpha2+mc1.18.1
(Resource Pack: Better+Leaves+Add-on+V2.7-1.18)

But when I load into my world and place glass blocks or panes they still aren't smoothed/connected. I've tried turning "Disable CTM" and "Use Manual Culling" both On and Off but it had no effect. Could you please help?

Thank you!

![2022-01-31_14 58 17](https://user-images.githubusercontent.com/98280613/151865253-56ebaaae-5578-41d6-b837-68164cce85a2.png)

**Comment by machiecodes** [comment]
Did you load the built in resource pack called "default" with the connected textures?

**Comment by PixelArtPlays** [comment]
Ah! I hadn't realized that this was treated like a resource pack. I've always run on OptiFine, so setting up Fabric mods/textures in new to me.
I've loaded them both and I worked great!

Thanks so much, I really appreciate it! :)

**Comment by machiecodes** [comment]
No problem!
