### ISSUE TITLE
buggy stone textures

### ISSUE THREAD

**Issue by VaporeonScripts** [PepperCode1/Continuity#540]
![image](https://github.com/user-attachments/assets/a97beea8-e7d2-4385-8c69-129489935c81)

**Comment by VaporeonScripts** [comment]
1.21.1

**Comment by PepperCode1** [comment]
Send your game log. Does this still happen  if all mods except Fabric API and Continuity are removed?

**Comment by VaporeonScripts** [comment]
caused by barely default incompat with stay true, without it, mod works, my bad
