### ISSUE TITLE
Indium still mentioned on modrinth front page

### ISSUE THREAD

**Issue by TQNL** [PepperCode1/Continuity#543]
With the upcoming release for 1.21.3, sodium 0.6.0 is in play for 1.21.1+ (including 1.21.3). This version makes indium obsolete, so this notice message in the image should be updated to account for that.
![image](https://github.com/user-attachments/assets/71b29011-87b2-4b61-ab85-c9d95ebb961a)

**Comment by PepperCode1** [comment]
Fixed.
