### ISSUE TITLE
1.21.3?

### ISSUE THREAD

**Issue by EmirCivil06** [PepperCode1/Continuity#548]
Hello, will there be an update to Continuity mod for the version 1.21.3?

**Comment by YukiAyase** [comment]
There is a test build available for 1.21.3 in the Discord server
Its pretty much stable

**Comment by EmirCivil06** [comment]
Thank you for your answer, but I'd rather learn the expected date of its offical release. Thanks for your attention.

**Comment by PepperCode1** [comment]
3.0.0+1.21.3 has been released on Modrinth, CurseForge, and GitHub Releases.
