### ISSUE TITLE
method overlay_random not working

### ISSUE THREAD

**Issue by litoj** [PepperCode1/Continuity#55]
Hello, I use random textures overlay through ctm and since I switched to sodium for performance, I am trying to convert everything in my resourcepack to something compatible.
I have a file like this:
```
matchTiles=dark_oak_leaves
tiles=0-6 <skip>
weights= 1 1 1 1 1 1 1 100
method=overlay_random
connect=block
biomes=dark_forest
```
but it doesn't show anything using this method I used with Optifine.
Is there an alternative I could use to achieve the same result?

**Comment by PepperCode1** [comment]
Please provide a log. I might know what the issue is but I need to confirm it.

**Comment by litoj** [comment]
Oh, when I launched it now, to get the log, but wasn't using any other mod than yours, it worked.
When I use just fabric api, your mod and sodium, it breaks completely, meaning all blocks with overlay just display as the missing texture, when I add Iris, lithium and indium, it doesn't show missing texture, but doesn't work either,

**Comment by PepperCode1** [comment]
If you are using Sodium, you need Indium. Additionally, Continuity 1.0.3 does not support Sodium alpha 6 or higher, but this will be fixed with 1.1.0.

**Comment by litoj** [comment]
oh, ok. That's probably the problem.
Just out of curiosity, what is the breaking change with new  Sodium?

**Comment by PepperCode1** [comment]
`WorldSlice#getBiome` was removed in alpha 6, meaning that any properties files using the `biomes` property are effectively ignored.

**Comment by litoj** [comment]
is there any available replacement?

**Comment by PepperCode1** [comment]
You can either use alpha 5, build the repository yourself, use a build from Github Actions, or wait until 1.1.0 is released.

**Comment by litoj** [comment]
ok, thanks
