### ISSUE TITLE
add a way to disable specific block connection (or glass)

### ISSUE THREAD

**Issue by VaporeonScripts** [PepperCode1/Continuity#550]

**Comment by VaporeonScripts** [comment]
id like to completely disable glass ability to be connected with textures

**Comment by VaporeonScripts** [comment]
(cuz of this)
![image](https://github.com/user-attachments/assets/5df9d914-5417-4971-9f40-29c4d797f1de)

**Comment by PepperCode1** [comment]
Disable the provided Default Connected Textures pack and make an edit if necessary. The ability to add/remove certain connections is exactly what the resource pack format is for.

**Comment by VaporeonScripts** [comment]
> Disable the provided Default Connected Textures pack and make an edit if necessary. The ability to add/remove certain connections is exactly what the resource pack format is for.

Idk how to do that

**Comment by PepperCode1** [comment]
There are plenty of resources out there to learn. Alternatively, for specifically this case, you can debug #544 as I described so you don't need to edit or disable packs in the first place.
