### ISSUE TITLE
Missing Text for 1.20.1 

### ISSUE THREAD

**Issue by SpicyDandelion** [PepperCode1/Continuity#554]
![image_2024-12-04_133735911](https://github.com/user-attachments/assets/40168638-3daf-4983-950d-909dec3a0730)

I get this every time I open the game with any version of 1.20.1 continuity installed! I tried disabling every single one of my mods and found that this one is the cause. I don't know if its a compatibility issue...because I use continuity for my 1.21.1 game. Any tips on how to figure out how to fix this would be great! Idk if it'll help, but here's my log. My game didn't crash though so idk what it will help with.

[latest.log](https://github.com/user-attachments/files/18012790/latest.log)

**Comment by PepperCode1** [comment]
Indium is required when using Sodium 0.5.

**Comment by SpicyDandelion** [comment]
oh my gosh, sorry about that. Ty for the help. I use curseforge to download mods, and for some reason it didn't auto add that requirement for me! <3
