### ISSUE TITLE
Modrinth issue with 1.21.1 NeoForge version

### ISSUE THREAD

**Issue by mpustovoi** [PepperCode1/Continuity#555]
Although it may not have been indexed yet, but Modrinth App constantly wants to update the version of the mod for NeoForge 1.21.1, since the version name is identical to the version of Fabric 1.21.1:
![image](https://github.com/user-attachments/assets/5a8a5940-d1e2-4b6c-9e1d-3c13992c3884)

This issue isn't there on Forge 1.20.1:
![image](https://github.com/user-attachments/assets/c50f2038-4ced-47a3-8063-f5ee05e2ee6c)

**Comment by PepperCode1** [comment]
The version number is `3.0.0+1.21.neoforge`, which is not the same as for the Fabric release.

**Comment by mpustovoi** [comment]
The issue is gone.
