### ISSUE TITLE
1.21.2

### ISSUE THREAD

**Issue by A-r-s-a-n-e** [PepperCode1/Continuity#556]
I see there is a port on 1.21.3 and 1.21.1 but no 1.21.2. I decided to use fabric 1.21.2 because many mods I use are not in 1.21.3, and I want 1.21.2 update items, but for some reason there is no continuity 1.21.2.

**Comment by A-r-s-a-n-e** [comment]
Apparently, u can make it work on 1.21.2 by downloading 1.21.3 and changing fabric.mod.json file so all 1.21.3 become 1.21.2 and sodium 0.6.2 into 0.6.0. It seems to work, but i am not sure about any bugs or other things.

**Comment by PepperCode1** [comment]
An official version for 1.21.2 will not be made. Sodium 0.6.0 has critical bugs that affect Continuity.
