### ISSUE TITLE
Fabric version claims to be Neoforge when installed via Modrinth

### ISSUE THREAD

**Issue by dylanparry** [PepperCode1/Continuity#558]
I installed the Fabric version (as that's what I'm using), but since you've released a Neoforge version Modrinth decided to update to that instead, and now claims I need to update it when I already have the lastest version. If I switch back to the [correct] Fabric version, it still says that I'm using the Neoforge version and still prompts me to upgrade.

![image](https://github.com/user-attachments/assets/2301510e-3b9a-437e-8b3c-10e986ea93d4)

**Comment by FaultyFunctions** [comment]
Same thing here!

**Comment by IceMan70mc** [comment]
same problem

**Comment by Fyoncle** [comment]
Same here but its only forge for me, i use 1.20.1 Fabric

**Comment by PepperCode1** [comment]
I have recreated the Forge/NeoForge releases on Modrinth (and also published them on CurseForge). The jar for those releases is no longer exactly the same as for the Fabric releases. If this issue persists, contact Modrinth support - I will not be able to do anything about it.

**Comment by Fyoncle** [comment]
> I have recreated the Forge/NeoForge releases on Modrinth (and also published them on CurseForge). The jar for those releases is no longer exactly the same as for the Fabric releases. If this issue persists, contact Modrinth support - I will not be able to do anything about it.

Why close as not planned? Its already fixed
