### ISSUE TITLE
Not connected... I guess?

### ISSUE THREAD

**Issue by TiboOpGithub** [PepperCode1/Continuity#56]
Hi!
I have an issue with mostly big windows were glass is sometimes not connected. (version 1.17.1)
![image](https://user-images.githubusercontent.com/95926002/153768208-6983135c-9be2-4576-90e7-21207c3b68a5.png)

**Comment by PepperCode1** [comment]
I could not reproduce this. Please send a log file from when this occured.

**Comment by PepperCode1** [comment]
Closing as there has not been a response from the author.
