### ISSUE TITLE
1.19 Textures not connecting :/

### ISSUE THREAD

**Issue by left-eyebr0w** [PepperCode1/Continuity#561]
I'm trying to make a modpack for **Minecraft 1.19** using **Fabric**.
I have a bunch of mods installed and they all seem to be working fine except Continuity. 
Everything is in 1.19 (not 1.19.x).

Here's what I've done / tried so far : 
- I have enabled both resource packs available in the menu
- Disabling my shaders
- Downloading and using another resource pack with connected textures
- Running the game with minimal mods : only fabric-api, sodium, continuity

=> Still doesn't work (the result is below)

Is there something I'm doing wrong ?
Please help ahaha

The result : 
![2024-12-07_16 49 30](https://github.com/user-attachments/assets/3d644acc-cac9-4c0c-9e68-84ee929979e7)

The resource packs menu :
![Capture d’écran du 2024-12-07 16-50-46](https://github.com/user-attachments/assets/7709c600-015b-49de-a4b7-1a99aced5e1e)

**Comment by YukiAyase** [comment]
Send in your log file
Located in **.minecraft/logs**, filename is **"latest"**

**Comment by PepperCode1** [comment]
On 1.19, if you have Sodium, you need Indium.

**Comment by left-eyebr0w** [comment]
That did the trick, thank you !
