### ISSUE TITLE
Grass biome color tint not present on overlays

### ISSUE THREAD

**Issue by VL4DST3R** [PepperCode1/Continuity#562]
![image](https://github.com/user-attachments/assets/432644f1-beac-4a13-98a3-c422f943d8c4)
Not sure if it is related in any way to [this issue](https://github.com/PepperCode1/Continuity/issues/376) or [this one](https://github.com/PepperCode1/Continuity/issues/549), but figured it warranted its own separate issue.

**Comment by PepperCode1** [comment]
Yes, likely a duplicate of #549.
