### ISSUE TITLE
Weird visual issue with logs when against eachother.

### ISSUE THREAD

**Issue by TheTrueRain** [PepperCode1/Continuity#563]
https://github.com/user-attachments/assets/66a0f1fe-a9f7-4f6d-9fdd-6fd654aaeaa9

It seems there's some kind of lighting issue to do with logs intersecting like shown in the video. It happens with all types of logs whether stripped or not, might happen with all pillar type blocks, dunno if I'm conveying that right, but you probably get what I mean.

**Comment by PepperCode1** [comment]
That is a connected texture added by one of your resource packs. If you do not like it, you can disable that resource pack or edit it to remove specifically these connected textures.
