### ISSUE TITLE
1.18.1 release continuity? 

### ISSUE THREAD

**Issue by rony9707** [PepperCode1/Continuity#57]
Will there be the release of this mod for 1.18.1?

**Comment by machiecodes** [comment]
No, never ever.

**Comment by AlsoSylv** [comment]
Continuity 1.18 already works on 1.18.1

**Comment by nomeat1337** [comment]
Using the latest fabric (0.13.0), with 1.18.1 the mod does not work.

The issue resolver tells me to install any version of fabric. But fabric is already installed.

Any dice ?

![error](https://user-images.githubusercontent.com/64922003/154068758-8fc0de8b-4a9c-4838-ad9c-74a216cce9e8.PNG)

**Comment by TheNukeLore** [comment]
Install fabric api
