### ISSUE TITLE
[Forge] It looks like it's still a fabric type.

### ISSUE THREAD

**Issue by yoloray** [PepperCode1/Continuity#576]
It doesn't work as well as it looks.

<img width="321" alt="화면 캡처 2024-12-26 004220" src="https://github.com/user-attachments/assets/3b7b0884-24e8-4683-a278-f15687121965" />

I don't have a problem with using connector mode, but that's forge mode, so I ask.

**Comment by PepperCode1** [comment]
Yes, this is intended. I do not plan to make a native port anytime soon. If you have specific issues with the Forge version, report the issues instead of the fact that the port requires Connector.

**Comment by RemagOfficial** [comment]
if it requires connector it's not a port, you just named it neoforge
