### ISSUE TITLE
Says continuity is incompatible with fabric api and sodium.

### ISSUE THREAD

**Issue by Naknekia** [PepperCode1/Continuity#578]
I use mods through luner client and never had issues with continuity until 1.21.4. When i try and launch it says it isn't compatible with fabric api, which doesn't make sense because continuity depends on it, and also says it isn't compatible with sodium which is weird cause i had both in prior versions.

**Comment by PepperCode1** [comment]
The 1.21.4 version requires the latest version of Fabric API (0.113.0) and only works with the latest version of Sodium (0.6.6).

**Comment by Naknekia** [comment]
Tysm :)
