### ISSUE TITLE
Not compatible with Fabric API for 1.21.4?

### ISSUE THREAD

**Issue by Patar747** [PepperCode1/Continuity#579]
I get this message:

Replace Continuity 3.0.0 with any version compatible with:
Fabric API 0.110.5+1.21.4
Sodium 0.6.2+mc1.21.4

**Comment by PepperCode1** [comment]
The 1.21.4 version requires the latest version of Fabric API (0.113.0) and only works with the latest version of Sodium (0.6.6).
