### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by petya-RC** [PepperCode1/Continuity#58]
Hey,
I don't think it works so please help me.

![screen1](https://user-images.githubusercontent.com/74210929/154065142-ce6dfd88-072f-4074-a925-92b493040f22.png)

![2022-02-15_14 34 00](https://user-images.githubusercontent.com/74210929/154065195-5cac3514-4989-4a5d-84c6-5b1148b9db82.png)

**Comment by PepperCode1** [comment]
Send a log file.

**Comment by petya-RC** [comment]
[2022-02-16-2.log](https://github.com/PepperCode1/Continuity/files/8078657/2022-02-16-2.log)

**Comment by PepperCode1** [comment]
You need to install Indium, since you are using Sodium.
