### ISSUE TITLE
[Forge] Continuity crashes game when searching Botania Item

### ISSUE THREAD

**Issue by HoodBlah** [PepperCode1/Continuity#580]
Using latest Sinytra Connector and Forgified Fabric API on Forge 1.20.1

Searching using EMI + JEI.

Searching for Botania Item crashes game.

[debug.log](https://github.com/user-attachments/files/18268081/debug.log)

[latest.log](https://github.com/user-attachments/files/18268083/latest.log)

**Comment by PepperCode1** [comment]
This is caused by `floweringbotany`.

**Comment by PepperCode1** [comment]
`floweringbotany` is closed source so I cannot investigate this issue. Report it to them, and they might fix it.

**Comment by HoodBlah** [comment]
Got it, thx
