### ISSUE TITLE
Incompatible Fabric Mods

### ISSUE THREAD

**Issue by griffins2** [PepperCode1/Continuity#582]
Apologies if I'm an idiot, but I can't figure this out. 

Continuity 3.0.0+1.21.4 is incompatible with Fabric API 0.110.5+1.21.4 and Sodium 0.6.2+mc1.21.4 .

I'm using Lunar. Any help much appreciated.

**Comment by PepperCode1** [comment]
The 1.21.4 version requires the latest version of Fabric API (0.113.0) and only works with the latest version of Sodium (0.6.6).
