### ISSUE TITLE
Blocks such as ore blocks do not connect

### ISSUE THREAD

**Issue by DerpOKat21** [PepperCode1/Continuity#583]
In all showcases of Continuity, blocks such as blocks of ores and different types of wood will connect, but do not connect for me.
![Continuity issue](https://github.com/user-attachments/assets/70dd6d2a-921a-4213-a09c-0d81f00af428)

**Comment by PepperCode1** [comment]
That functionality is not part of the default resource pack. Use a pack like https://modrinth.com/resourcepack/ctm-overhaul.
