### ISSUE TITLE
Repeat method not working correctly

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [PepperCode1/Continuity#6]
**MC** 1.17.1
**Continuity** 1.0.0

1. Install Continuity
2. Install [NAPP](https://www.curseforge.com/minecraft/texture-packs/napp-free-version-1-01) and/or [FJGlass](https://www.curseforge.com/minecraft/texture-packs/faithful-jappa-ctm-glass) texture packs
3. Install [Lambdabettergrass](https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass) and activate its resource pack (I know, this one is not an optifine TP, but it's needed for the example testing)

Expected result: all textures connect as intended.

Actual result: if only NAPP is installed and Continuity resource packs are loaded and placed below it, only glass and glass panes connect; if Continuity packs are disabled or placed above NAPP then no textures connect; if FJGlass is installed and placed above NAPP, glass and glass panes also do not connect; Lambdabettergrass works and connects as inteded in all cases.

There's another connected textures mod - [ConnectedBlockTextures](https://github.com/HyperCubeMC/connected-block-textures). With it installed instead of Continuity, all NAPP textures connect, except for glass and glass panes; if FJGlass is installed, then glass and glass panes also connect. Lambdabettergrass does not work, no grass textures are connected.

What am I doing wrong?

**Comment by PepperCode1** [comment]
With only Continuity, everything works exactly like in Optifine, which means this is a compatibility issue with LambdaBetterGrass.

**Comment by SplendidAlakey** [comment]
I don't think so. In fact, I was incorrect to say that Lambdabettergrass didn't connect with ConnectedBlockTextures mod, I just confused it with a texture from Continuity texture pack. So when I enabled Continuity resource pack and saw a new connected grass texture, I assumed it was from LBG, I was wrong.

But either way, I completely removed all other mods, left only Fabric API and Continuity, as well as disabled all texture packs other than NAPP. Here are the results:

**Continuity + NAPP**: having Continuity RP enabled, disabled and placed either above/below NAPP does not change the outcome - no textures connect, other than glass
![2021-10-01_00 52 15](https://user-images.githubusercontent.com/86702831/135540616-b264a335-11f3-4049-8148-0b845a85b9ce.png)

**Continuity + NAPP + FJGlass**: no textures connect
![2021-10-01_01 02 31](https://user-images.githubusercontent.com/86702831/135541033-1c5f5ce2-f4ca-47ff-a758-fa09bce776af.png)

**ConnectedBlockTextures + NAPP**: all textures connect, except for glas
![2021-10-01_00 54 51](https://user-images.githubusercontent.com/86702831/135540706-acdd52fe-07c5-492b-8331-d4f7d358c405.png)

**ConnectedBlockTextures + NAPP + FJGlass**: every texture connects
![2021-10-01_00 55 29](https://user-images.githubusercontent.com/86702831/135540795-a0bc06eb-466b-4748-93fc-a890c4838fca.png)

**Comment by PepperCode1** [comment]
The broken glass connections in scenario 2 (Continuity + NAPP + FJGlass) is an incompatibility between the packs. When I tested this on Optifine, it gave me the exact same result. This will not be fixed, unless my testing with Optifine was incorrect. However, the stone connections are indeed broken, so I will fix them sometime soon.

**Comment by PepperCode1** [comment]
The stone actually does not look correct in Optifine. This can be fixed by overriding the stone blockstate to disable texture rotation and reflection via a separate pack, which I have made and attached to this comment. However, since I am basing parity off Optifine and not Connected Block Textures, this issue will not be fixed by the mod itself either, as it will cause more problems than it will solve. To fix the issue completely and properly, it is best to contact the resource pack author and let them know about it.

[NAPP_Stone_Fix.zip](https://github.com/PepperCode1/Continuity/files/7263079/NAPP_Stone_Fix.zip)
