### ISSUE TITLE
Issues with water on chunk borders

### ISSUE THREAD

**Issue by IgvmCorporation** [PepperCode1/Continuity#60]
![2022-02-21_21 09 01](https://user-images.githubusercontent.com/100183915/155067514-96da0f72-c82f-48ec-aa09-2a9ecaffa85c.png)
![2022-02-21_21 09 08](https://user-images.githubusercontent.com/100183915/155067583-31e5d9d3-4a9e-415b-8847-aa01e4c8f316.png)
![2022-02-21_21 17 16](https://user-images.githubusercontent.com/100183915/155067854-5cb2a604-7008-47c1-b712-6241a6612de3.png)
I have noticed all sorts of visual glitches close to this such as water disappearing through the glass in the chunk that you are in, the top texture of water not loading through connected glass, and other kinds of visual glitches. I am using only fabric API, sodium, indium, and continuity for these screenshots.

**Comment by PepperCode1** [comment]
Try without Sodium.

**Comment by IgvmCorporation** [comment]
It works without using sodium and indium, but I use those mods for performance. Is there a way to fix this while using sodium?

**Comment by TheNukeLore** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by TheNukeLore** [comment]
Nothing from continuity’s side, sodium’s end and currently no fix.

**Comment by PepperCode1** [comment]
You can follow the issue here: CaffeineMC/sodium-fabric#38. The only current solution is to not use Sodium or compile one of the fix pull requests yourself.
