### ISSUE TITLE
Continuity v1.1.0 crashes the game at launch

### ISSUE THREAD

**Issue by Scarlaid** [PepperCode1/Continuity#61]
Like the title said
Lastest version (v1.1.0) from CurseForge, instantly broke
Older version, e.g v1.0.3 works fine

Lastest log: [latest.log](https://github.com/PepperCode1/Continuity/files/8124900/latest.log)
<details><summary>Mods used to run the game</summary>
<p>

![image](https://user-images.githubusercontent.com/90851437/155336193-b289fb8c-53dd-4a65-8c9f-a5aa53333140.png)

</p>
</details>

**Comment by machiecodes** [comment]
Man downloaded every mod possible holy jeebus

**Comment by Scarlaid** [comment]
Personal usage xD

**Comment by PepperCode1** [comment]
Your download was corrupted and the Continuity jar file is empty. Try downloading it again.

**Comment by Scarlaid** [comment]
ohh okay, it ran after a quick redownload, thanks
