### ISSUE TITLE
Dynmap?

### ISSUE THREAD

**Issue by generrosity** [PepperCode1/Continuity#63]
Hello!

I'm just a helper on the Dynmap discord, and run a little fabric server and use Continuity myself.

Dynmap has supported the original 'CTM v1' (?) format of texture pack for some time now, but the single dev is more on the backend coding rather than texture packs and things. I know all the CTM code for dynmap is only 1.5k lines in one class - much smaller than what you have!

I was wondering how hard it would be to impliment more CTM into dynmap - or if you might be interested in contibuting to the codebase? Is that even something you might be interested in? The dev is reasonably happy with PRs from others (and would likely be appreciative to have CTM issues hit on the head for once)

Just wondering if of interest - thanks!

**Comment by PepperCode1** [comment]
Not an issue; Dynmap CTM support is being discussed elsewhere.
