### ISSUE TITLE
Support of custom item

### ISSUE THREAD

**Issue by un-pogaz** [PepperCode1/Continuity#64]
The Optifine supports a variant of CTM fot the items
Continuity does it support it too, that would be a good plus

example: change the "axolotl in a bucket" texture to match with the Variant color of this one.
[test axolot.zip](https://github.com/PepperCode1/Continuity/files/8186470/test.axolot.zip)
![2022-03-04_15 52 14](https://user-images.githubusercontent.com/46523284/156787513-2793a510-dee0-43fc-9491-ad587fa4223d.png)

**Comment by PepperCode1** [comment]
Use CIT Resewn. Continuity will not be adding custom item texture features.

**Comment by machiecodes** [comment]
Copium
