### ISSUE TITLE
Overlay textures has issues with light source blocks

### ISSUE THREAD

**Issue by efffauw** [PepperCode1/Continuity#65]
![2022-03-04_23 21 43](https://user-images.githubusercontent.com/93001604/156792076-444ecce8-2331-4d96-b928-21af4deb6f72.png)
![2022-03-04_23 18 30](https://user-images.githubusercontent.com/93001604/156792113-0476c4ce-91e9-4839-8997-a07e933619d0.png)
![Screenshot (92)](https://user-images.githubusercontent.com/93001604/156792125-3534419a-8d0c-4f08-9a1d-6632ff92c57b.png)

**Comment by RaptaG** [comment]
Is there any progress in this so far?

**Comment by PepperCode1** [comment]
I cannot fix this because FRAPI/Indigo/Indium do not allow me to, but the issue is still open because I would like this to be resolved eventually.

**Comment by RaptaG** [comment]
:C I understand, I hope someday the complications will be resolved

**Comment by PepperCode1** [comment]
This was fixed in 3.0.0-beta.4 for 1.19.4 and newer.

**Comment by VL4DST3R** [comment]
After the last update for me it just no longer generates overlays for things like glowstone. Is this the "fix"?
