### ISSUE TITLE
Underwater lighting error

### ISSUE THREAD

**Issue by f4nem14s** [PepperCode1/Continuity#67]
I use sodium, indium and iris shaders. This error appears with and without shaders.
![2022-03-08_11 52 32](https://user-images.githubusercontent.com/93697465/157169414-f2bd3038-4088-44dc-a1d8-032bf30e1736.png)

**Comment by ezzzhong** [comment]
![2022-05-19_03 59 07](https://user-images.githubusercontent.com/71432076/169137740-58147843-56fd-4979-a263-23cf8ccc406e.png)
left: connected texture
right: unconnected texture

**Comment by PepperCode1** [comment]
This is a Indigo/Indium issue, which will be investigated and resolved soon, hopefully.

**Comment by PepperCode1** [comment]
This has been fixed with Fabric API 0.58.0 and Indium 1.0.7.
