### ISSUE TITLE
[FEATURE REQUEST] Emmisive texture support

### ISSUE THREAD

**Issue by dajix350** [PepperCode1/Continuity#7]
It would be great if you considered added Optifine's emissive textures support to this pack. I usually use [this pack](https://www.planetminecraft.com/texture-pack/emissive-ore-borders-for-1-17) when using Optifine, but it requires both connected and emissive textures. Could you consider integrating it?

**Comment by PepperCode1** [comment]
I have considered it many times but currently it is not possible to do because of API limitations. If those are ever resolved, I will definitely add emissives.

**Comment by dajix350** [comment]
Couldn't you reuse some code from your CTM fabric port, which does have emissive textures, I am not a programmer, so correct me if I am wrong.

**Comment by dajix350** [comment]
I just had an idea last night to make emissive textures. If you didn't know, as of 1.17 it is possible to make [`Emissive textures in vanilla minecraft`](https://www.planetminecraft.com/texture-pack/emissive-ores-no-optifine/), but sodium breaks the mechanics it uses (vanilla shaders). If you can fix that sodium bug with an Indium style patch, then you can promote the vanilla emissive texture format.

**Comment by ghost** [comment]
ok so to get emissive textures even using sodium on continuity you can download CTMF and disable the CTMF connected textures, then use a CTMF emissive texture pack

**Comment by dajix350** [comment]
@woo0ps Thanks for suggesting a workaround, it will do for now. I am still wondering why CTMF and have emmisive textures, but this can't. @PepperCode1 said there were API limitations, but wouldn't they apply to both mods?

**Comment by mr-pi12** [comment]
> @woo0ps Thanks for suggesting a workaround, it will do for now. I am still wondering why CTMF and have emmisive textures, but this can't. @PepperCode1 said there were API limitations, but wouldn't they apply to both mods?

I'm guessing it might be because of the different supported formats of continuity and CTMF and the different methods used to read the formats and connect the textures? I'm not sure if it is though.
