### ISSUE TITLE
Culling fix not working on the connection of two differently colored glasses.

### ISSUE THREAD

**Issue by Balazs0718** [PepperCode1/Continuity#70]
![image](https://user-images.githubusercontent.com/101470638/158026616-844e17bf-6715-41e5-9a0c-144476cb5875.png)
![image](https://user-images.githubusercontent.com/101470638/158026649-a3f1af21-e037-454d-8307-eacc3a806f29.png)
Issue only happens with two differently colored glass pieces connecting, not when next to solid blocks. Tried disabling and reenabling everything but it did not work.

**Comment by Julienraptor01** [comment]
I think this is the sodium transluancy sorting problem. If it's that there is no fix possible currently except of removing sodium or waiting so that they solve the problem.

**Comment by PepperCode1** [comment]
The culling fix is only for the top and bottom sides of glass panes, not full glass blocks. The glass blocks not culling is intended behavior and works the same way in vanilla. The rendering errors you see are caused by CaffeineMC/sodium-fabric#38.
