### ISSUE TITLE
Glass doesnt look proper when seen through other glass

### ISSUE THREAD

**Issue by CasualWolfGamer** [PepperCode1/Continuity#75]
![2022-03-21_21 19 36](https://user-images.githubusercontent.com/67299330/159408178-4627cd99-7b7d-494d-8c0c-e26a1c746f0f.png)
![2022-03-21_21 36 44](https://user-images.githubusercontent.com/67299330/159409045-6c5d540d-f523-4257-93ad-b6c002a010ea.png)

**Comment by Julienraptor01** [comment]
Isn't this sodium's transluancy sorting problem ? https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by PepperCode1** [comment]
Test this without Sodium first, to check if it is the above mentioned issue.

**Comment by Continous** [comment]
This is a sodium issue. Confirmed through my own testing.
