### ISSUE TITLE
Not working on 1.18.2 with Sodium and Indium

### ISSUE THREAD

**Issue by n-chicken** [PepperCode1/Continuity#77]
Hi

I tried messing with the two configs but it apparently doesn't connect glass or sandstone

[Here's the logs](http://ix.io/3TiD)

These are the mods I'm using:

```
indium-1.0.2+mc1.18.2.jar
modmenu-3.1.0.jar
continuity-1.1.0+1.18.2.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
iris-mc1.18.2-1.2.1-rc2-0cc372f0-dirty.jar
fabric-api-0.47.10+1.18.2.jar
```

**Comment by PepperCode1** [comment]
You did not apply the default resource pack. Without it, no textures are connected.

**Comment by n-chicken** [comment]
Whoops missed that one. Thanks for the quick response!
