### ISSUE TITLE
Connected textures do not seem to work with colored panes

### ISSUE THREAD

**Issue by TheRealDadbeard** [PepperCode1/Continuity#78]
Only the non colored panes are connected properly. It's the stay true modpack.

MC 1.18.2
Fabric 0.13.3
Continuity 1.1.0

![2022-03-29_13 31 03](https://user-images.githubusercontent.com/23340600/160603218-f898cbe5-e9e2-4034-ba90-249d0fbcaae7.png)

**Comment by efffauw** [comment]
Do you mean the [Stay True](https://www.curseforge.com/minecraft/texture-packs/stay-true) resource pack because the [Stay True](https://www.curseforge.com/minecraft/modpacks/stay-true) modpack doesn't have a fabric version?

**Comment by PepperCode1** [comment]
You need to enable the `continuity/default` resource pack.

**Comment by LuckyDanCZ** [comment]
I also have this problem. 
I tried enabling the default pack but it still doesn't work for me
