### ISSUE TITLE
Major incompatibility with Sodium

### ISSUE THREAD

**Issue by Diplotomodon** [PepperCode1/Continuity#8]
When using Continuity with the latest build of Sodium installed, it breaks almost every texture modified within the resource pack. This happens with pretty much any pack that makes use of Optifine connected textures, and without Sodium they work completely as intended.

![2021-10-01_16 41 55](https://user-images.githubusercontent.com/86527037/135685826-2b3cc2bf-ca49-44b7-82fe-2a98343a89c0.png)

**Comment by TheNukeLore** [comment]
You need indium

**Comment by Diplotomodon** [comment]
Works with indium. Thanks 👍
