### ISSUE TITLE
Unable to bake model

### ISSUE THREAD

**Issue by voltavidTony** [PepperCode1/Continuity#84]
I am trying to use the Patrix resource pack, which uses connected textures extensively. However, my world turns almost entirely into the missing texture blocks when I activate continuity. As seen in the log, almost every block fails to compile.
The error is that it cannot invoke materialFinder because the return value of getRenderer() is null.

I have tried running just continuity without any other mods, but the issue persists.

Current mods:
- Sodium
- Phosphor
- Lithium
- Iris
- Mod Menu
- Fabric API
- Continuity

Log file:
[2022-04-04-5.log](https://github.com/PepperCode1/Continuity/files/8406665/2022-04-04-5.log)

**Comment by PepperCode1** [comment]
Install Indium. It is required if you use Sodium.

**Comment by voltavidTony** [comment]
Oops. Well, I guess this thread exists now for future users
