### ISSUE TITLE
Continuity not working for me with the following mods:

### ISSUE THREAD

**Issue by Ralle3xy** [PepperCode1/Continuity#88]
I'm currently running Minecraft on 1.18.1, so It's been somewhat difficult to find the correct version for the corresponding mod. 
I have some problems with the Continuity mod and It doesn't work with the following mods that I'm currently using:

![Screenshot 2022-04-14 040601](https://user-images.githubusercontent.com/103616466/163299688-0cc9d7c3-4413-4dee-9c0a-89db2d5f2540.png)

**Comment by PepperCode1** [comment]
This configuration should work. Did you enable the default packs?

**Comment by Ralle3xy** [comment]
> This configuration should work. Did you enable the default packs?

Oh... Hahaha, my fault. I didn't know you had to enable the resource packs😅.  Well, thank you for the fast response, and good job with this mod! Keep up the good work! 😄 

Have a great one!
