### ISSUE TITLE
Continuity for 1.16.5?

### ISSUE THREAD

**Issue by abscosmos** [PepperCode1/Continuity#89]
Would you be willing to update/backport/compile (idk) this mod for 1.16.5?

**Comment by machiecodes** [comment]
copecopecopecopecopecopecopecope

**Comment by PepperCode1** [comment]
Some of Continuity's newer features (primarily emissives) require that certain bugs are fixed in FRAPI implementations. Since these fixes were not ported to any version below 1.18.2, I will not be porting current versions of Continuity to anything below 1.18.2 either.
