### ISSUE TITLE
Texture bugs

### ISSUE THREAD

**Issue by igoticecream** [PepperCode1/Continuity#9]
Hello,

I'm using the following pack which uses Optifine/MCPatcher format: https://www.planetminecraft.com/texture-pack/connectibles/

I'm noticing some texture bugs on some of the blocks. First I thought it was a texture pack bug, but loading the same pack with OptiFine the issue is not there, so it looks like a Continuity thing.

I'm attaching 4 screenshots that could help you. The screenshots with an ocean on the left are from OptiFine.

![2021-10-02_14 28 38](https://user-images.githubusercontent.com/3914859/135716410-7563853b-e779-42e2-bfa7-061a066577e2.png)
![2021-10-02_14 28 50](https://user-images.githubusercontent.com/3914859/135716414-546b21c9-0b2c-44d5-9a34-c0bc9cba53b3.png)
![2021-10-02_14 30 24](https://user-images.githubusercontent.com/3914859/135716417-9556e865-db07-4c12-a2a7-40939e300dc9.png)
![2021-10-02_14 30 35](https://user-images.githubusercontent.com/3914859/135716419-89e28e03-f38c-4ada-aa72-6d303b4e218d.png)

Thank you.

**Comment by AlsoSylv** [comment]
Is the third screenshot with sodium? If so, you need indium

**Comment by igoticecream** [comment]
Yes, 3 and 4 are from sodium, I'm using `indium-1.0.0+mc1.17.1.jar` other connected textures works fine

**Comment by AlsoSylv** [comment]
Can you attach a log file?

**Comment by igoticecream** [comment]
Sure

[latest.log](https://github.com/PepperCode1/Continuity/files/7271460/latest.log)

**Comment by igoticecream** [comment]
I'm closing because it's resolved already (not on an official release but in [this commit](https://github.com/PepperCode1/Continuity/commit/7c97a94618af268aaf44a370ca0532e8898d54ee))

Using `continuity-1.0.1+1.17-build.10.jar` from [the latest action artifacts](https://github.com/PepperCode1/Continuity/actions/runs/1292971615) the issue is gone
