### ISSUE TITLE
Incompatibility with Inspecio

### ISSUE THREAD

**Issue by SyberiaK** [PepperCode1/Continuity#92]
When i have Continuity + Inspecio installed, there are no connected textures.

**Comment by PepperCode1** [comment]
Duplicate of #68. Inspecio's developer said that an update for Fabric that will fix the issue will not be released, so you will have to either uninstall Inspecio or switch to Quilt and update to Inspecio 1.4.0.

**Comment by SyberiaK** [comment]
Thanks, i found that it updates without switching, so i'm very happy now :)
