### ISSUE TITLE
My game crashes when i load a world 

### ISSUE THREAD

**Issue by mike12408** [PepperCode1/Continuity#99]
when I log in with this mod it crashes when I load any world single-player and multiplayer

I have a lot of mods and I used to play with my friend's SMP 

This is a picture of the mod folder 
![unknown_2022 05 20-22 43](https://user-images.githubusercontent.com/88698592/169564158-4bd7ea4d-559c-4e45-8d3c-ffe1a9a9d4c4.png)

the copy exit code is -1

this is the crash report
[crash-2022-05-20_22.44.52-client.txt](https://github.com/PepperCode1/Continuity/files/8741662/crash-2022-05-20_22.44.52-client.txt)

**Comment by PepperCode1** [comment]
The client player is null. I have seen this crash before and I do not know what causes it but I know that it is not related to Continuity.
